opnsense/plugins

net/haproxy/Makefile
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/ServiceController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogErrorfile.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Menu/Menu.xml
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/statistics.volt
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportErrorFiles.php
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportLuaScripts.php
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

This is the first batch of fixes for our new HAProxy plugin.
@fichtner: BTW, feel free to open a new issue if you found flaws or quirks that should be fixed (or discussed).

fixes for net/haproxy

---

net/haproxy/Makefile
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/+MANIFEST
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

The GUI option to add an X-Forwarded-For header was previously ignored. :(

net/haproxy: fix option to add X-Forwarded-For header

---

net/haproxy/Makefile
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/+MANIFEST
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

This contains fixes for issues #25, #26, #27, #28, #29 and #30.
Please **do not commit** until issue https://github.com/opnsense/core/issues/1095 is resolved.

net/haproxy: SSL fixes & more – version 1.4

---

net/haproxy/Makefile
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/setup.sh
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/+MANIFEST

net/haproxy: fix chroot logging

---

net/l2tp/src/etc/inc/plugins.inc.d/if_l2tp.inc
net/pppoe/src/etc/inc/plugins.inc.d/if_pppoe.inc
net/pptp/src/etc/inc/plugins.inc.d/if_pptp.inc

Without quotes throws exception.

Fix function_exists(url_safe)

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml

Cosmetic fix, but proper names are less confusing :)

security/acme-client: fix DNS-01 provider titles

---

net/quagga/src/opnsense/scripts/quagga/setup.sh
net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/quagga

This will create the directories if needed.
Merge when the script is hooked.

Add quagga directory structure init script

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFNetwork.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/isis.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/rip.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/zebra.conf

Hi,
this is my first pull. 
Added the zebra.conf since it is reqiured to start quagga itself. 
Also fixed some minor typos.

Some updates to quagga package

---

net-mgmt/snmp/pkg-descr
net/quagga/Makefile
net/quagga/pkg-descr

Quagga: dependency
SNMP: minimal package description

Add some metadata to some plugins

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/RipController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/RipController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/rip.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/Menu/Menu.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/RIP.php
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/RIP.xml
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/rip.volt
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/quagga
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ripd.conf

[WIP] RIP Quagga

---

net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ripd.conf

Try to fix #105 
Waiting for feedback of the original author of the ticket.

try to fix #105

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/rip.xml

Quagga improve strings

---

net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/general.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/rip.volt

Make the plugin look like described by @jschellevis 
Screenshot:

Quagga design

---

security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

- none
- try to solve [disconnection issue](https://forum.opnsense.org/index.php?topic=4792.0) (mostly during auto-renewal)

security/acme-client: bugfix release 1.5

---

net/quagga/Makefile
net/quagga/src/opnsense/scripts/quagga/bgp.rb

@fichtner I know the script is not beautiful but the output of quagga sadly is that hard to parse (I hate it when programs create tables with empty fields...)
@mimugmail can you run the script and look at the output?
The output should be JSON and from this JSON the GUI should be built.

add parser for quagga show ip bgp

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/accounts.volt
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt

none
- fix translation strings that have been broken in #122 ([via forum post](https://forum.opnsense.org/index.php?topic=5053.0))

security/acme-client: Bugfix release 1.6

---

security/acme-client/Makefile
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

security/acme-client: fix $backend is not declared

---

net/quagga/src/etc/inc/plugins.inc.d/quagga.inc

Das Dashboard sollte nun den richtigen Status anzeigen.
gleich auf Stable ins release

Quagga: integrate better into the services

---

net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml

I added validation for remote-as as requested in #138 
With this validation should be completed for BGP

Added BGP validation as requested in #138

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/GeneralController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/Ospf6settingsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/RipController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/ServiceController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BgpController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/GeneralController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/IsisController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Ospf6Controller.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/OspfController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/RipController.php

all files are looking this way:
(C)
empty line
namespace
use
empty line
phpdoc if existing
class

move includes, namespace after the copyright headers, remove unused

---

net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospf.volt
net/quagga/src/opnsense/scripts/quagga/quagga.rb

this has now a good size for a review
* add the missing part
* Fix a bug in the backend + in the frontend
* Tabs: Remove 'OSPF' as we are already on the OSPF diagnostics page
* add neighbor to the GUI

fix bug in ospf backend script, add neighbor

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospf.volt

This is an additional diagnostics page for OSPFv2 which looks stable.

Quagga (OSPF): add interfaces

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/DiagnosticsController.php
net/quagga/src/opnsense/scripts/quagga/quagga.rb
net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf

this will add the methods to parse
* overview
* linkstate and
* route
if it is like the output in #141. There is currently no way to call it

Quagga: add some ospfv3 diagnostics calls to quagga.rb

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/Menu/Menu.xml
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospfv3.volt

Quagga: Add OSPFv3 Diagnostics

---

net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsgeneral.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospf.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospfv3.volt

Note: The table in general does not work as it breaks the HTML inside.

Quagga: add bootgrid to diagnostics pages

---

net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/IndexController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/StatisticsController.php
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/statistics.volt

I promise I have tested it ;)
Fun fact: german already has the translation for one of them.

translate title names in the HAProxy plugin

---

net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml

net/haproxy: support IPv6 listen addresses in frontend

---

net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/Menu/Menu.xml
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsgeneral.volt

this will add the IPv6 routing table display tab to Diagnostics -> General
As discussed

add IPv6 routing table support; replace icon

---

net/quagga/Makefile
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/GeneralController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/Ospf6settingsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/RipController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/ServiceController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Ospf6Controller.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/diagnostics.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6Interface.xml
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf6.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/Menu/Menu.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.php
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsbgp.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsgeneral.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospf.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospfv3.volt
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
net/quagga/src/opnsense/scripts/quagga/diag-bgp.sh
net/quagga/src/opnsense/scripts/quagga/quagga.rb
net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
net/quagga/src/opnsense/www/js/quagga/lodash.js

This should work
This is release `1.2` of quagga for stable (everything without the new BGPv4 stuff)

Quagga 1.2

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml

Via [forum post](https://forum.opnsense.org/index.php?topic=5311.0).
Looks like a rather silly copy'n'paste error on my side. :(

net-mgmt/zabbix-agent: listen address validation fails

---

net/haproxy/Makefile
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

none
- fix handling of check interval in healthcheck and server settings (#175)

net/haproxy: release 1.16

---

net/quagga/Makefile
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPASPath.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

This one fixes #171 
Small update to the if clause.
Please only merge into master, I'm still searching for more errors ... 
@fabianfrz @fichtner please review.

Update to bgpd.conf templating

---

security/tinc/src/opnsense/scripts/OPNsense/Tinc/lib/objects.py
security/tinc/src/opnsense/scripts/OPNsense/Tinc/tincd.py

When tinc is configured to use switch mode, it needs to use a tap interface instead of tun.

Fix tinc plugin in switch mode

---

security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt

https://github.com/opnsense/plugins/commit/393557c22046ca420f9cf1f8a13baa5b30d9bbb1 broke it

security/acme-client: fix typo s/taging/staging/

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/DiagnosticsController.php
net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/general.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml
net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/Menu/Menu.xml
net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/log.volt
net/quagga/src/opnsense/scripts/quagga/quagga.rb
net/quagga/src/opnsense/scripts/quagga/setup.sh
net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ripd.conf
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/zebra.conf

@fichtner this is the template and GUI related work for logging in the quagga plugin. the syslog config is currently not included in the service file.
This is for #205

add logging to quagga

---

README.md
net/zerotier/Makefile

Hi,
Updated to reflect change in the tag line on the Zerotier home page.
Please can this be merged in. Thank you.
-=david=-

net/zerotier: Update tag line and bump version.

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt

- update acme.sh to version 2.7.2 (https://github.com/opnsense/plugins/issues/210)
- Rename Certificate "Name" to "Common Name" for better clarity (https://github.com/opnsense/plugins/pull/214)
- Fix title in "Renew" and "Revoke" dialogs
- Add dependency to BIND to fix nsupdate support

security/acme-client: release 1.9

---

net-mgmt/collectd/Makefile
net-mgmt/collectd/src/opnsense/mvc/app/controllers/OPNsense/Collectd/forms/general.xml
net-mgmt/collectd/src/opnsense/mvc/app/models/OPNsense/Collectd/General.xml
net-mgmt/collectd/src/opnsense/mvc/app/views/OPNsense/Collectd/general.volt

- Add more precise description to FQDNLookup
- Second validator for network collector (IP and hostname)
- Add progress to Save button
Please review @fabianfrz @fichtner

Collectd: multiple changes as requested in #217

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

closes #213 
I don't have accounts for any of these new providers, so I can't test it. The GUI and backend is still working, though... :)

security/acme-client: add support for new DNS API hooks

---

net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/ServiceController.php

Add Filter reload to quagga start and reload action

---

net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/Api/ServiceController.php
net/mdns-repeater/src/opnsense/mvc/app/views/OPNsense/MDNSRepeater/index.volt
net/mdns-repeater/src/opnsense/service/conf/actions.d/actions_mdnsrepeater.conf

MDNS: add status indicator

---

www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/+TARGETS
www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/newsyslog.conf

C-ICAP: Add logrotate to access.log and server.log

---

dns/dyndns/Makefile
net/siproxd/Makefile
net/siproxd/pkg-descr
net/siproxd/src/etc/inc/plugins.inc.d/siproxd.inc
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/Api/DomainController.php
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/Api/GeneralController.php
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/Api/ServiceController.php
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/Api/UserController.php
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/GeneralController.php
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/UserController.php
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/forms/dialogEditSiproxdDomain.xml
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/forms/dialogEditSiproxdUser.xml
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/forms/general.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/ACL/ACL.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/Domain.php
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/Domain.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/General.php
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/General.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/Menu/Menu.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/User.php
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/User.xml
net/siproxd/src/opnsense/mvc/app/views/OPNsense/Siproxd/general.volt
net/siproxd/src/opnsense/scripts/OPNsense/Siproxd/setup.sh
net/siproxd/src/opnsense/service/conf/actions.d/actions_siproxd.conf
net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/+TARGETS
net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd
net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd.conf
net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd_passwd.cfg

Siproxd plugin as requested in #246 
In #246 are some screenshots how it looks like. 
Current problem are the "Current registrations", the newlines are not correctly formatted. Perhaps you have some ideas? I could als try to write a script but a oneliner would be smarter I think.
setup.sh needs a chmod 755 as always when I contribute :)

Siproxd plugin

---

security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/IndexController.php
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/Menu/Menu.xml
security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/info.volt
security/tor/src/opnsense/service/scripts/tor/setup.sh

@fichtner this the info page - at the moment it shows the hidden service hostnames.

Tor: add info page

---

net-mgmt/collectd/src/opnsense/mvc/app/controllers/OPNsense/Collectd/GeneralController.php
net/relayd/src/www/load_balancer_setting.php
security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/GeneralController.php

Typos: make "Settings" upper case

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

none
- add missing field for DuckDNS (https://github.com/opnsense/plugins/issues/287)

security/acme-client: Bugfix release 1.11

---

net-mgmt/collectd/Makefile
net-mgmt/collectd/src/opnsense/mvc/app/controllers/OPNsense/Collectd/forms/general.xml
net-mgmt/collectd/src/opnsense/mvc/app/models/OPNsense/Collectd/General.xml
net-mgmt/collectd/src/opnsense/service/templates/OPNsense/Collectd/collectd.conf

As discussed in #296 and requested in #297

net-mgmt/collectd: add prefix and postfix input fields

---

www/c-icap/Makefile
www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/virus_scan.conf

www/c-icap: fix sizelimit

---

net/siproxd/Makefile
net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/forms/general.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/General.xml
net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd.conf

fixed some bugs, add a new field to enable proxy auth (unsure if model version bump is required)

net/siproxd: fixed bugs requested by @NicholasRush

---

net/siproxd/src/opnsense/mvc/app/controllers/OPNsense/Siproxd/forms/general.xml
net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/General.xml
net/siproxd/src/opnsense/mvc/app/views/OPNsense/Siproxd/general.volt
net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd.conf

@fichtner can you help me with the save buttons?
1. It's not in the middle, I'm not sure why:
2. It's working with the save buttons, but I left formid as general, is this ok?

net/siproxd: fixed model and save buttons

---

net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf

Doesn't need a version bump, should be ok for the next bigger change to be included :)

net/quagga: fix message for log

---

sysutils/monit/Makefile
sysutils/monit/src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/StatusController.php
sysutils/monit/src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/general.xml
sysutils/monit/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
sysutils/monit/src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
sysutils/monit/src/opnsense/scripts/OPNsense/Monit/post-install.php
sysutils/monit/src/opnsense/service/templates/OPNsense/Monit/monitrc

- new Monit options #293 : logfile, statefile, eventqueue, httpd, mmonit
- special chars in e-mail password #267

sysutils/monit: additional Monit options

---

security/tor/Makefile
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/ServiceController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/IndexController.php
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/Menu/Menu.xml
security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/diagnostics.volt
security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/error.volt
security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/info.volt
security/tor/src/opnsense/scripts/tor/tor_diag
security/tor/src/opnsense/service/conf/actions.d/actions_tor.conf

@fichtner the diagnostics page shows the
* circuit(s)
* active connections
Screenshots:
The screenshots can be reused for the docs

Tor: add a diagnostics page

---

security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/GeneralController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/IndexController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/hidservauth.xml
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/General.xml
security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/general.volt
security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc

follow up for #307 
make it possible to authenticate as a client

hidden services: add auth for clients

---

security/acme-client/Makefile
security/acme-client/src/etc/inc/plugins.inc.d/acmeclient.inc
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

- compatibility with HAProxy plugin version 2.0 (refs #330)
- fix missing fields for Hurricane Electric (#334)

security/acme-client: release 1.12

---

mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/2tld.inc.local
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/antivirus.conf
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/antivirus.wl
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/greylist.conf
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/mx_check.conf
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/phishing.conf
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/ratelimit.conf
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/spf.conf
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/surbl-whitelist.inc.local

@mimugmail try this patch for #353

rspamd: fix templates (don't render unless the model exists)

---

net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml

via https://forum.opnsense.org/index.php?topic=6316.0
Cosmetic change, no version bump required.

net/haproxy: aliases cannot be used

---

mail/rspamd/src/opnsense/mvc/app/controllers/OPNsense/Rspamd/IndexController.php
mail/rspamd/src/opnsense/mvc/app/controllers/OPNsense/Rspamd/forms/settings.xml
mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml
mail/rspamd/src/opnsense/mvc/app/views/OPNsense/Rspamd/index.volt
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/+TARGETS
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/redis.conf

requires the rspamd plugin from #371

add redis plugin to rspamd plugin

---

databases/redis/src/opnsense/mvc/app/controllers/OPNsense/Redis/forms/settings.xml
databases/redis/src/opnsense/mvc/app/models/OPNsense/Redis/Redis.xml
databases/redis/src/opnsense/service/conf/actions.d/actions_redis.conf

databases/redis: add requested changes by fichtner

---

www/web-proxy-sso/Makefile
www/web-proxy-sso/src/opnsense/mvc/app/controllers/OPNsense/ProxySSO/Api/ServiceController.php
www/web-proxy-sso/src/opnsense/mvc/app/controllers/OPNsense/ProxySSO/forms/general.xml
www/web-proxy-sso/src/opnsense/mvc/app/models/OPNsense/ProxySSO/ProxySSO.php
www/web-proxy-sso/src/opnsense/mvc/app/models/OPNsense/ProxySSO/ProxySSO.xml
www/web-proxy-sso/src/opnsense/scripts/OPNsense/ProxySSO/kerberos_test.sh

It is about #343 
I made option where user can set name differ from default.

Proxy sso update

---

security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/Api/ServiceController.php
security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/forms/version.xml
security/clamav/src/opnsense/scripts/OPNsense/ClamAV/freshclam.sh
security/clamav/src/opnsense/scripts/OPNsense/ClamAV/versions.sh
security/clamav/src/opnsense/service/conf/actions.d/actions_clamav.conf

ClamAV can store the signature database in files .CVD and files .CLD. You need to consider both types of files.

Checking .CLD and .CVD files.

---

security/tor/Makefile
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/general.xml
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/relay.xml
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/General.xml
security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc

@paride this should fix both of your issues.
If you have time you can apply this patch using the opnsense-patch utility.
The commit id is 774b2bc

security/tor: fix help string, add memory limit; closes #384

---

security/tor/Makefile
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/General.xml
security/tor/src/opnsense/scripts/tor/tor_diag

security/tor: fix control socket issue

---

security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/Api/ServiceController.php
www/c-icap/src/opnsense/mvc/app/controllers/OPNsense/CICAP/Api/ServiceController.php

When c-icap click "Save" in the upper right corner of the screen does not change a red square to the green triangle. You have to manually reload the page.

Waiting for service startup.

---

security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/IndexController.php
security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/error.volt

also for the ticket of @lattera. This is the part of the frontend.
closes #387

block page if no socket exists

---

security/clamav/Makefile
security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/Menu/Menu.xml
security/clamav/src/www/diag_logs_clamav.php

Added Logviewer for clamd.log and freshclam.log

security/clamav: reworked menu, added logviewer

---

net-mgmt/zabbix-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf

With this PR the plugin can go stable. But please don't forget to chmod the setup.sh script.
You can decide if it's for 17.7.9 or 18.1 to fill the Changelog ;)

net-mgmt/zabbix-proxy: update template and chmod

---

mail/postfix/Makefile
mail/postfix/src/opnsense/scripts/OPNsense/Postfix/setup.sh
mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf

mail/postfix: add newaliases to setup.sh

---

net/arp-scan/Makefile

I hope to really had well understood what I have to do to push this plugins into official release. Thank you for your support, if something else is missed please let me know in useful times.

stable release

---

README.md
net/iperf/Makefile

forgot to change the name in the Makefile and add the plugin to the plugin list

iperf: add entry to readme and fix makefile

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/AccountsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/ActionsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ServiceController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/CertificatesController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/IndexController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/ValidationsController.php

PR: https://github.com/opnsense/core/issues/1954
Same here, want to keep version.

security/acme-client: sync service start

---

net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/ServiceController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/IndexController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/StatisticsController.php
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt

PR: https://github.com/opnsense/core/issues/1954
Skipping version bump as 2.0 is about to be released and this would make a good inclusion.
BTW: I **love** the new help tabs!!

net/haproxy: sync service start

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/src/etc/inc/plugins.inc.d/zabbixagent.inc
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/Api/ServiceController.php
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/IndexController.php
net-mgmt/zabbix-agent/src/opnsense/mvc/app/views/OPNsense/ZabbixAgent/index.volt
net-mgmt/zabbix-agent/src/opnsense/service/conf/actions.d/actions_zabbixagent.conf

PR: https://github.com/opnsense/core/issues/1954
The view title change will be omitted from merges to stable/17.7, on opnsense-devel this is already auto-generated from Menu.xml for easier maintenance.

net-mgmt/zabbix-agent: sync service start and small fixes

---

net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/IndexController.php
net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/OverviewController.php

This is for 18.1 and / or after 17.7.9. :)

net/zerotier: titles are now auto-generated from Menu.xml

---

net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt

This is for https://github.com/opnsense/core/issues/1922 and also affects https://github.com/opnsense/plugins/issues/340
There is no rush for this, take your time. :)

net/haproxy: adjust subtabs to 18.1 layout and fix glitches

---

mail/rspamd/Makefile
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/redis.conf

use the redis port given in the config for redis.

mail/rspmd: redis port

---

net/haproxy/Makefile
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/IndexController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt

- new option to hide introduction pages (#340)
- fix wrong introduction for "Advanced" tab (regression introduced in https://github.com/opnsense/plugins/pull/414/commits/8cdcbdaaf85cc45b6c5a61a8ddf91ac8aabb320b)

net/haproxy: Release 2.3

---

net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/DiagnosticsController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/GeneralController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Ospf6Controller.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/OspfController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/RipController.php
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/general.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/rip.volt

Port of the commit of @fichtner to add spinners and remove titles.

net/frr: port the commit b888990; closes #425

---

security/tor/Makefile
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/relay.xml
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/Relay.xml
security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc

closes #385
just close this old feature request.

security/tor: fix a bug in tor model; Add ContactInfo to tor relay;

---

net/shadowsocks/Makefile
net/shadowsocks/pkg-descr
net/shadowsocks/src/etc/inc/plugins.inc.d/shadowsocks.inc
net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/Api/GeneralController.php
net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/Api/ServiceController.php
net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/GeneralController.php
net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/forms/general.xml
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/ACL/ACL.xml
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/General.php
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/General.xml
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/Menu/Menu.xml
net/shadowsocks/src/opnsense/mvc/app/views/OPNsense/Shadowsocks/general.volt
net/shadowsocks/src/opnsense/service/conf/actions.d/actions_shadowsocks.conf
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/+TARGETS
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/shadowsocks.conf
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/shadowsocks_libev

Requested in #467 
Very simple plugin.

net/shadowsocks: New plugin

---

dns/dyndns/src/www/services_dyndns_edit.php
dns/rfc2136/src/www/services_rfc2136_edit.php
net-mgmt/snmp/src/www/services_snmp.php
net/igmp-proxy/src/www/services_igmpproxy_edit.php
net/l2tp/src/www/vpn_l2tp.php
net/pppoe/src/www/vpn_pppoe_edit.php
net/pptp/src/www/vpn_pptp.php
net/relayd/src/www/load_balancer_monitor_edit.php
net/relayd/src/www/load_balancer_pool_edit.php
net/relayd/src/www/load_balancer_setting.php
net/relayd/src/www/load_balancer_virtual_server_edit.php
net/upnp/src/www/services_upnp.php

Error: Attribute "type" not allowed on element "i" at this point.

HTML Compliance - Attribute "type" on Element <i>

---

dns/dyndns/src/www/services_dyndns_edit.php
dns/rfc2136/src/www/services_rfc2136_edit.php
net-mgmt/snmp/src/www/services_snmp.php
net/igmp-proxy/src/www/services_igmpproxy_edit.php
net/l2tp/src/www/vpn_l2tp.php
net/l2tp/src/www/vpn_l2tp_users_edit.php
net/pppoe/src/www/vpn_pppoe_edit.php
net/pptp/src/www/vpn_pptp.php
net/pptp/src/www/vpn_pptp_users_edit.php
net/relayd/src/www/load_balancer_pool_edit.php
net/relayd/src/www/load_balancer_setting.php
net/relayd/src/www/load_balancer_virtual_server_edit.php
net/upnp/src/www/services_upnp.php
net/wol/src/www/services_wol.php
net/wol/src/www/services_wol_edit.php

Error: Attribute "for" not allowed on element "div" at this point.
Attributes for element "div": http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-div-element
HTML attribute reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
The "Output" element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output
Attributes for element "output": http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-output-element

HTML Compliance - Attribute "for" on Element <div>

---

mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/dialogEditPostfixDomain.xml
mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Domain.xml

Allow to add ports, did some basic validation.
Closes #478

mail/postfix: change FieldType of destination

---

net-mgmt/lldpd/src/opnsense/mvc/app/views/OPNsense/Lldpd/general.volt

Add auto-refresh, thanks to @fabianfrz :)
@fichtner I think this can go directly to RC2, but you can decide better about timeline etc.

net-mgmt/lldpd: Add auto-refresh for neighbor tab

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

- update acme.sh to 2.7.5 (#418)
- fix missing fields for several DNS providers (#481)

security/acme-client: release 1.13

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

Add Output all Enable fields to make separation clearer.
This can be something for 18.1.1 .. doesn't hurry .. :)

net-mgmt/telegraf: Add graphite and graylog output

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Helper text colour change and revision bump

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/bootstrap-dialog.less
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Fix tooltip and many other corrections.

---

misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/bootstrap/_variables.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Audit background was incorrect.

---

net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/forms/general.xml
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/General.xml
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/shadowsocks.conf

- add Server to label
- updated helptext
- added cipher
- changed to hostnamefield type, only available with 18.1

security/shadowsocks: minor update

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/bootstrap/_variables.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Green was a little too bright.

---

net/freeradius/Makefile
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/eap.xml

Updated the label since with EAL-TTLS it only has to validata the root CA. This can go stable at any time you want :)

net/freeradius: update label

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml

https://forum.opnsense.org/index.php?topic=7075.0

net-mgmt/telegraf: change defaults for _server in output

---

net/zerotier/Makefile
net/zerotier/src/opnsense/service/templates/OPNsense/zerotier/zerotier

Preserve the '/var/db/zerotier-one' directory on reboot

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/jquery.bootgrid.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/jquery.tokenize.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/nv.d3.css

Changes to some colours. There is no scss file for these to be compiled from so these are hard coded.

Theme needs these files in its own folder.

---

net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/Ospf6settingsController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/RipController.php

code cleanup - use the new methods
BGP will be a separate pull request

net/frr: shorten code for RIP and OSPF

---

net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php

net/frr: simplify BGP API Controller

---

net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/Ospf6settingsController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/ExitaclController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/GeneralController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/HiddenserviceController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/HiddenserviceaclController.php
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/SocksaclController.php

see https://github.com/opnsense/core/commit/b739c49892a3dc52029f863f20e0975dde476388
Now everything should be fine here.

net/frr and security/tor: remove session close from search action

---

net/relayd/Makefile
net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/Api/SettingsController.php

The xxxBase functions from ApiMutableModelControllerBase doesn't work.
No idea why :disappointed:

net/relayd: revert back from ApiMutableModelControllerBase xxxBase

---

net/shadowsocks/Makefile
net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/forms/local.xml
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/Local.xml
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/ss_local.conf

Add local address from forum request https://forum.opnsense.org/index.php?topic=7234.0
Please chmod the rc.d file :)

net/shadowsocks: add local_address

---

sysutils/monit/src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php

Sorry, a last minute fix. :innocent:

sysutils/monit: fix test deletion

---

sysutils/monit/src/opnsense/mvc/app/views/OPNsense/Monit/index.volt

From #563 review.
Thanks @fabianfrz :smiley:

sysutils/monit: add missing translation

---

security/tinc/src/opnsense/service/templates/OPNsense/Tinc/tinc_deploy.xml

I've noticed that incorrect port is being saved in host config files, so I fixed it.

Tinc: Hosts: Fix host port

---

mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml

mail/postfix: update helptext

---

sysutils/monit/Makefile
sysutils/monit/src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
sysutils/monit/src/opnsense/mvc/app/controllers/OPNsense/Monit/IndexController.php
sysutils/monit/src/opnsense/mvc/app/views/OPNsense/Monit/index.volt

Fixes for opnsense-devel compatibility. Please ACK/NAK. :)

sysutils/monit: cleanups for upcoming core switch

---

net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

Please just merge so my tester can retry if it works now.

net/frr: fix bgp v6, add activate to config

---

mail/rspamd/src/opnsense/mvc/app/controllers/OPNsense/Rspamd/forms/settings.xml
mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/phishing.conf

https://rspamd.com/doc/modules/phishing.html

mail/rspamd: add map's tp phishing and helptext

---

mail/rspamd/src/opnsense/mvc/app/controllers/OPNsense/Rspamd/forms/settings.xml
mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/+TARGETS
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/milter_headers.conf

add file for milter headers

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml

none
none
- add working default values (#491)

net-mgmt/zabbix-agent: Release 1.3

---

sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/Api/ServiceController.php
sysutils/nut/src/opnsense/mvc/app/views/OPNsense/Nut/index.volt
sysutils/nut/src/opnsense/service/conf/actions.d/actions_nut.conf

- switches Service to new codebase
- last update stupidly removed reconfigure 
Now local mode and remote client works charmly .. still missing diagnostics.
Sorry for the double PR today :/

sysutils/nut: new apimutable service + reconfigure fix

---

mail/postfix/Makefile
mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml

mail/postfix: change model field type for relay_host

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

- add support for ClouDNS (#574)
none
none

[WIP] security/acme-client: release 1.14

---

net/freeradius/Makefile
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users

- redesign users template to allow multi adds
- add Framed-Route attribute for OpenVPN 
- add Framed-IPv6-Address attribute
Seems there is a merge conflict

net/freeradius: add routes and v6 address

---

misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

css changes and version bump to 0.3

Tukan Theme Update

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/bootstrap-select/css/bootstrap-select.css
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/bootstrap-select.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css

css and scss updates - bump revision

Theme Cicada update

---

net-mgmt/net-snmp/Makefile
net-mgmt/net-snmp/pkg-descr
net-mgmt/net-snmp/src/etc/inc/plugins.inc.d/netsnmp.inc
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/Api/GeneralController.php
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/Api/ServiceController.php
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/Api/UserController.php
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/GeneralController.php
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/forms/dialogEditNetsnmpUser.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/forms/general.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/ACL/ACL.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/General.php
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/General.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/Menu/Menu.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/User.php
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/User.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/views/OPNsense/Netsnmp/general.volt
net-mgmt/net-snmp/src/opnsense/scripts/OPNsense/Netsnmp/setup.sh
net-mgmt/net-snmp/src/opnsense/service/conf/actions.d/actions_netsnmp.conf
net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/+TARGETS
net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd
net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd.conf
net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd_usercredentials.conf

- Replacement for the old snmp plugin
- API enabled of course
- Supports SNMPv3
This is a first draft to test. Currently doesn't support selecting listening IFs in this stage. Also it looks very limited in UI, but it should fit all needs at first, more to come ...

net-mgmt/net-snmp: new plugin

---

misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Rene reports the last theme PR did not include the fixes for firewall etc, so he sent me this one.  
@fabianfrz - checked with sass and all appears good.

Tukan Update

---

sysutils/smart/Makefile
sysutils/smart/src/www/diag_smart.php

@fichtner The issue had to do with the old short open tag as it seems and I fixed some other stuff as well. Please note that this is only partial tested because my VM has no smart support and the commands do not show anything. Also it states that a parameter may be added (`-T permissive`)
The PHP code works and the buttons are bootstrap styled now.

Fix diag smart

---

www/web-proxy-sso/src/opnsense/mvc/app/views/OPNsense/ProxySSO/index.volt

jQuery 3 migration.

---

net-mgmt/zabbix-proxy/Makefile
net-mgmt/zabbix-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
net-mgmt/zabbix-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml
net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/+TARGETS
net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf
net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.psk

Hi,
This PR add the possibility to configure PSK based encryption for the communication with the Zabbix server (https://www.zabbix.com/documentation/3.0/manual/encryption/using_pre_shared_keys).
Best regards,
Fabian

Add Possibility to Configure PSK based Encryption on UI

---

net/relayd/Makefile
net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/Api/SettingsController.php
net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/forms/virtualserver.xml
net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Relayd.xml
net/relayd/src/opnsense/mvc/app/views/OPNsense/Relayd/index.volt
net/relayd/src/opnsense/service/templates/OPNsense/Relayd/relayd.conf

The interface is mandatory for 'route to' redirections.

net/relayd: add interface for transport type route

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/scripts/nginx/setup.php
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

there is not much that can fail - may go to stable

www/nginx: add HTTPS backends

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/tokenize2.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/tokenize2.css

Tokenizer2 file for rebellion

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

.bootstrap-dialog.type-success .modal-header color fix for both themes - cicada and tukan

.bootstrap-dialog.type-success .modal-header color fix

---

security/acme-client/Makefile
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

none
- fix OCSP always enabled (#794)
none

security/acme-client: release 1.17

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

www/nginx: (bugfix) add host header

---

www/nginx/Makefile
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/IndexController.php
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/limit_request_connection.xml
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/limit_zone.xml
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/httprequestlimit.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

allow to limit the rate of requests per minute or second

www/nginx: add request limits

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

net-mgmt/telegraf: add prometheus output and pf input

---

dns/bind/Makefile
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
dns/bind/src/opnsense/scripts/OPNsense/Bind/dnsbl.sh

- remove double dots, remove one dot at the beginning
- removed pornall since it's too big (130MB text), takes a looooong time  to load, sometimes crashes due to full swap. As discusses with @fichtner in IRC I'm loading porntop1m instead to not break the script

dns/bind: remove list pornall (way too big) and list fixes

---

net/wireguard/Makefile
net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServiceController.php
net/wireguard/src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
net/wireguard/src/opnsense/service/conf/actions.d/actions_wireguard.conf

When this PR is approved we can go 1.0

net/wireguard: add some debugging tabs

---

dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Menu/Menu.xml
dns/bind/src/www/diag_logs_bind.php

@fichtner do we need to bump? I think we already have ...

dns/bind: add log to UI

---

net/relayd/Makefile
net/relayd/src/opnsense/mvc/app/views/OPNsense/Relayd/index.volt

The scheduler was always set to Round Robin in the UI.
Solves #824

net/relayd: wrong scheduler setting in UI

---

security/tor/Makefile
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/relay.xml
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/Relay.xml
security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc

security/tor: allow to enable directory page

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Fix for IPsec widget change, Update to sidebar, revision bump

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner would be nice if you could merge this!
I am currently very satisfied with 13px font size. the readability fits!

font-size and padding-fix

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt

Add the port to the overview list and make it sortable by port and server
closes #873

www/nginx: add port to selection

---

net/vnstat/Makefile
net/wireguard/Makefile
net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf

net/wireguard: add psk to peers

---

net/freeradius/Makefile
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/dictionary
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users

[net/freeradius] Add attribute enabled check in config files

---

net-mgmt/net-snmp/Makefile
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/forms/dialogEditNetsnmpUser.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/User.xml
net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd.conf

net-mgmt/net-snmp: let the user enable read-write access

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

tukan / cicada toogle-button chrome outline fix
@fichtner fix for chrome browser

tukan / cicada toogle-button chrome outline fix

---

misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner 
.nav > li.disabled color fix (hover, focus)

.nav > li.disabled color fix for tukan

---

security/openconnect/Makefile
security/openconnect/src/opnsense/mvc/app/models/OPNsense/Openconnect/General.xml

security/openconnect: allow upper-case characters for username

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner a few entries that are no longer needed - also for opnsense theme

a few entries that are no longer needed

---

net/zerotier/src/opnsense/mvc/app/views/OPNsense/Zerotier/overview.volt

Fixed closing td-tag which messes up the ui

---

www/nginx/src/opnsense/scripts/nginx/setup.php

fix for #902
the value of a not existing ca may not be iterable. It is just a warning but should be fixed.

www/nginx: guard loop parameter with an if

---

net/ntopng/Makefile
net/ntopng/src/opnsense/mvc/app/controllers/OPNsense/Ntopng/forms/general.xml

net/ntopng: add helptext

---

net/wireguard/Makefile
net/wireguard/src/etc/inc/plugins.inc.d/wireguard.inc
net/wireguard/src/etc/rc.d/opnsense-wireguard
net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/opnsense-wireguard

- closes #910 
- closes #866 
Downside: devel testers have to recreate firewall rules in wireguard tab (if any)

net/wireguard: fix rc stuff

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner Firewall: Log Files: Live View color modification for tukan and cicada

Firewall: Log Files: Live View color themes modification

---

security/openconnect/Makefile
security/openconnect/src/opnsense/mvc/app/controllers/OPNsense/Openconnect/forms/general.xml
security/openconnect/src/opnsense/mvc/app/models/OPNsense/Openconnect/General.xml
security/openconnect/src/opnsense/scripts/OPNsense/Openconnect/generate_certs.php
security/openconnect/src/opnsense/scripts/OPNsense/Openconnect/setup.sh
security/openconnect/src/opnsense/service/conf/actions.d/actions_openconnect.conf
security/openconnect/src/opnsense/service/templates/OPNsense/Openconnect/openconnect.conf

closes #898 
Only master .. need a devel pkg for testing with 18.7.5 ..

security/openconnect: add groups and client certificates

---

net/wireguard/Makefile
net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Menu/Menu.xml
net/zerotier/Makefile
net/zerotier/src/opnsense/mvc/app/models/OPNsense/Zerotier/Menu/Menu.xml

closes https://github.com/opnsense/core/issues/2814

menu: reorder WireGuard and ZeroTier

---

www/nginx/Makefile
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

via: https://forum.opnsense.org/index.php?topic=9977.0
the headers are not added when configured globally

nginx header problems

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner fix colors for firewall muted-text for both themes

Cicada / Tukan firewall muted-text fix

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@franco some fixes and optimizations for tukan and cicada

some fixes and optimizations

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner tukan/cicada - sidebar - cut off modification fix

tukan/cicada - sidebar - cut off modification fix

---

security/softether/Makefile
security/softether/pkg-descr
security/softether/src/etc/inc/plugins.inc.d/softether.inc
security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/Api/GeneralController.php
security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/Api/ServiceController.php
security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/GeneralController.php
security/softether/src/opnsense/mvc/app/controllers/OPNsense/Softether/forms/general.xml
security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/ACL/ACL.xml
security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/General.php
security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/General.xml
security/softether/src/opnsense/mvc/app/models/OPNsense/Softether/Menu/Menu.xml
security/softether/src/opnsense/mvc/app/views/OPNsense/Softether/general.volt
security/softether/src/opnsense/scripts/OPNsense/Softether/setup.sh
security/softether/src/opnsense/service/conf/actions.d/actions_softether.conf
security/softether/src/opnsense/service/templates/OPNsense/Softether/+TARGETS
security/softether/src/opnsense/service/templates/OPNsense/Softether/softether_server

At it's current stage it's just a  UI for the service wrapper. All configuration is done via SoftEthers own management client which offers a huge bunch of options, doesn't make sense to reinvent the wheel.

security/softether: new plugin

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner small fix for table width
before fix:
with fix:

tukan / cicada table width fix

---

www/nginx/pkg-descr
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/security_rule.conf

avoid duplicated security headers in responses

www/nginx: hide upstream headers

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/+TARGETS
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/newsyslog.conf

@fichtner @fabianfrz I'm using here and is working well...

simple log rotation routine based on newsyslog @franco

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/Api/SettingsController.php
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/IndexController.php
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/dialogAlias.xml
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/dialogUserparameter.xml
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/settings.xml
net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml
net-mgmt/zabbix-agent/src/opnsense/mvc/app/views/OPNsense/ZabbixAgent/index.volt
net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agentd.conf

- add support for UserParameters ([documentation](https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_agentd))
- add support for Item Key Aliases ([documentation](https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_agentd))
none
- cleanup: remove default comments from template (this was requested some time ago, but it took me some time to accept it's uselessness)

net-mgmt/zabbix-agent: release 1.4

---

www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
www/nginx/src/opnsense/www/js/nginx/src/nginx_config.js

* fix some issues with input configuration
* clean up js like core
* add satisfiy, max post body size, cache size to upstream and server
@mimugmail this is half of your request - the proxy_* stuff will be separate.

www/nginx: add request size limitation, satisfy and fix some generic bugs

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

this are the other fields requested by @mimugmail

www/nginx: add fields for proxy server

---

misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/bootstrap-select-1.13.3.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/nv.d3.css
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/nv.d3.css

@fichtner tukan / cicada some short corrections for nvd3

tukan / cicada some short corrections for nvd3

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/nv.d3.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

@fichtner sorry, i missed a correction i did already for tukan!
cicada - little tooltip fix

cicada - little tooltip fix

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/bootstrap-select-1.13.3.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/bootstrap-select-1.13.3.css

Added new bootstrap file.

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/bootstrap-select-1.13.3.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/bootstrap-select-1.13.3.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css

@fichtner cicada / tukan missing scss files

cicada / tukan missing scss files

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Bring into line with other themes.
scss code generated using http://sebastianpontow.de/css2compass

Update Rebellion sidebar elements

---

mail/postfix/Makefile
mail/postfix/pkg-descr
mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf

mail/postfix: allow tls wrapper mode

---

dns/dnscrypt-proxy/Makefile

Fix typo in PLUGIN_COMMENT, "supportung" to "supporting"

Update os-dnscrypt-proxy Makefile

---

dns/bind/pkg-descr
dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/general.xml
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/General.xml
dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf

- hide version
- hide hostname
- add rate-limiting

dns/bind: add some small options

---

dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dnsbl.xml
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
dns/bind/src/opnsense/service/templates/OPNsense/Bind/+TARGETS
dns/bind/src/opnsense/service/templates/OPNsense/Bind/duckduckgo.db
dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

@mimugmail In order to create "clean" pull requests: created a new branch and reverted the www/nginx commit d0f64ef in this pull request. Hope this is ok like this

dns/bind: Add duck duck go

---

dns/bind/pkg-descr
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
dns/bind/src/opnsense/scripts/OPNsense/Bind/dnsbl.sh

Most wished DNSBL, finally closes #1033 
No bump needed as 1.4 not yet released.

dns/bind: add StevenBlack blacklist

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
www/nginx/src/opnsense/scripts/nginx/read_log.php
www/nginx/src/opnsense/scripts/nginx/tls_ua_fingerprint.php
www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf

adds a new API endpoint with aggregated fingerprints so we can use them later for the frontend where we can offer to store them in our database file as well as config.xml.
ran bmake style-fix as well as I added some phpdoc.

www/nginx: TLS fingerprint log API, phpdoc

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

color fixes for waning, pagination-border, firewall and help text

tukan / cicada - some small color fixes

---

mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml

@mimugmail please test this. I think half of your model is missing

mail/rspamd: fix model (missing properties), constraint bugs

---

security/openconnect/Makefile
security/openconnect/pkg-descr
security/openconnect/src/opnsense/mvc/app/models/OPNsense/Openconnect/General.xml

Closes #1121 
Also added changelog to pkg-descr

security/openconnect: allow more characters to group name

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

firefox/chrome/safari
note: some css properties are not or not yet supported in firefox

tukan/cicada - unify scrollbar colors to theme

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css

internal-autofill field
@fichtner can you update that without a new makefile? it is really just a very small update

cicada - small chrome update

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Menu/Menu.xml
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_highwinds.php
security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf

- automatically upload certificates to Highwinds CDN (proof-of-concept, support for other APIs possible)
none
- rename "Restart Actions" to "Automation" (the old name has always been rather clumsy)
- change "Automation" position in Menu (it's optional, the new position reflects this)

security/acme-client: release 1.19

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/Api/DhcpController.php
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/Api/LeaseController.php
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/DhcpController.php
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/LeaseController.php
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dhcp.xml
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSDhcp.xml
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSLease.xml
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/general.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Dhcp.php
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Dhcp.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/General.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Lease.php
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Lease.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Menu/Menu.xml
net/freeradius/src/opnsense/mvc/app/views/OPNsense/Freeradius/dhcp.volt
net/freeradius/src/opnsense/mvc/app/views/OPNsense/Freeradius/lease.volt
net/freeradius/src/opnsense/scripts/Freeradius/setup.sh
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/+TARGETS
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mac2ip
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-dhcp_sqlippool
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-sqlippool
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/queries.conf
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/sites-enabled-dhcp

net/freeradius: add dhcp relay server

---

net/vnstat/Makefile
net/vnstat/pkg-descr
net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/Api/ServiceController.php
net/vnstat/src/opnsense/mvc/app/views/OPNsense/Vnstat/general.volt
net/vnstat/src/opnsense/service/conf/actions.d/actions_vnstat.conf

net/vnstat: add Reset button to volt

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

small improvements for .text-danger, .btn-danger and .fw_block classes

Tukan / Cicada - small color fixes

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Menu/Menu.xml
dns/dnscrypt-proxy/src/www/diag_logs_dnscrypt.php

dns/dnscrypt-proxy: add logging to UI

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/AccountsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ActionsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ValidationsController.php
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/accounts.volt
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/validations.volt

- possible breaking change: the API endpoint to update individual certs/accounts/etc. has been renamed from "set" to "update"
- bulk deleting does not work (#1163)
- migrate to mutable controller (required to fix #1163)

security/acme-client: release 1.21

---

net/haproxy/Makefile
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php

none
- bulk deleting does not work (#1164)
- migrate to mutable controller (required to fix #1164)

net/haproxy: release 2.14

---

www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml

this is an invalid configuration, which was implemented by accident.
@fichtner please note that this includes a breaking change, which should be mentioned at the release.
closes #1175

www/nginx: fix checkrule "=" does not exist

---

net/ntopng/Makefile
net/ntopng/pkg-descr
net/ntopng/src/opnsense/scripts/OPNsense/Ntopng/setup.sh
net/ntopng/src/opnsense/service/templates/OPNsense/Ntopng/ntopng
net/ntopng/src/opnsense/service/templates/OPNsense/Ntopng/ntopng.conf

datadir moved to new direction
https://forum.opnsense.org/index.php?topic=10922.0

net/ntopng: new datadir

---

mail/postfix/Makefile
mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf

mail/postfix: fixed typo in wrapper mode

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/mvc/app/controllers/OPNsense/Dnscryptproxy/Api/DnsblController.php
dns/dnscrypt-proxy/src/opnsense/mvc/app/controllers/OPNsense/Dnscryptproxy/forms/dnsbl.xml
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Dnsbl.php
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Dnsbl.xml
dns/dnscrypt-proxy/src/opnsense/mvc/app/views/OPNsense/Dnscryptproxy/general.volt
dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh
dns/dnscrypt-proxy/src/opnsense/service/conf/actions.d/actions_dnscryptproxy.conf
dns/dnscrypt-proxy/src/opnsense/service/templates/OPNsense/Dnscryptproxy/dnscrypt-proxy.toml
dns/dnscrypt-proxy/src/opnsense/service/templates/OPNsense/Dnscryptproxy/dnscrypt_proxy

Closes #1183 
I copied the BIND DNSBL functionality to dnscrypt-proxy.
This would avoid triple forwards when someone needs Unbound for DNS, BIND for DNSBL and dnscrypt for privacy. 
As dnscrypt has excellent overrides / forwarding, in most cases also Unbound would not be mandatory now.

dns/dnscrypt-proxy: add blacklist support

---

net/vnstat/Makefile
net/vnstat/pkg-descr
net/vnstat/src/opnsense/service/templates/OPNsense/Vnstat/vnstat

net/vnstat: make db persistEnt in MFS installation 

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFNetwork.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf

net/frr: add route summarization via area range

---

www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

seems like i need to clean up my branch after a squashed commit…
Forum: https://forum.opnsense.org/index.php?topic=11620.msg53410#msg53410

www/nginx: remove hardcoded HSTS header

---

net/freeradius/pkg-descr
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/general.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/General.xml
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-sql

Created a draft PR :) 
Regarding #1092

net/freeradius: add remote mysql support

---

net-mgmt/zabbix4-proxy/Makefile
net-mgmt/zabbix4-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf

net-mgmt/zabbix4-proxy: fix old directory name

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

added hosting.de DNS Provider in the list of available APIs

update letsencrypt plugin: added DNS Service hosting.de

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php

* support DNS-01 with hosting.de API (#1234)
none
- streamline log messages, use "AcmeClient" instead of "LE"

[WIP] security/acme-client: release 1.22

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

this was the problem:
now its fixed for both themes:

Themes - Tukan /Cicada - Page content main section view fix

---

www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/security_headers.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/security_rule.conf

www/nginx: bugfix csp

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/bootstrap-dialog.less
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/bootstrap-dialog.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-dialog.less
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-dialog.css

bootstrap-dialog - color fix for both themes

bootstrap-dialog - color fix

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

net-mgmt/telegraf: add graphite tag support

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/Api/ServiceController.php
net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml

none
- relax validation masks for UserParameter input fields  (#1252)
- fix service restart not working
- migrate to mutable service controller

net-mgmt/zabbix-agent: release 1.5

---

security/acme-client/Makefile
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

none
- renewal interval is ignored #1221
none

security/acme-client: release 1.23

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/bootstrap-select-1.13.3.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/tokenize2.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/bootstrap-select-1.13.3.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/tokenize2.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/tokenizer2.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/tokenize2.css

tukan / cicada - chrome (tokenize, bootstrap-select) focus color fix

---

security/clamav/Makefile
security/clamav/src/opnsense/service/templates/OPNsense/ClamAV/clamd.conf

security/clamav: remove deprecated defaults and rename options

---

net/freeradius/Makefile
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-ldap

Fixed:
- quotes around password missing
- group filter set in WebGUI not written

net/FreeRADIUS: fix missing LDAP parameters

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/etc/nginx/opnsense_http_vhost_plugins/vts.conf
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/ServiceController.php
www/nginx/src/opnsense/scripts/nginx/vts.php
www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf

this needs the VTS module to be compiled in and has currently no graphical frontend 
/api/nginx/service/vts

www/nginx: add basic VTS support

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/RIP.xml

net/frr: allow ipsec VTI selection

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Themes cicada/tukan - firewall live log update

---

net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php

cert should not be a constant but a 'cert' string

Fixing Typo

---

security/clamav/Makefile
security/clamav/src/opnsense/service/templates/OPNsense/ClamAV/freshclam.conf

See https://forum.opnsense.org/index.php?topic=12562.0;topicseen

security/clamav: remove deprecated config

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

modal background-color fix for both themes

Themes - Tukan/Cicada - modal fix for 19.7

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

.text-info color changed - better readability
@fichtner sorry franco -> my last change for the next release. it forgot these little fix for tukan. would be great if you could merge this too. regards rené

Themes - Tukan/Cicada - .text-info color changed - better readability and few other fixes

---

www/nginx/pkg-descr
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

logging: disable is currently not correctly detected and will fail.

www/nginx: fix logging issue

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

see my screenshot with the wrong colors! This is now been fixed!

Themes - Tukan/Cicada - "The settings have been applied" color fix

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Themes - Cicada / Tukan - general changes

Themes - Cicada / Tukan - general changes

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Dnsbl.xml
dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh

dns/dnscrypt-proxy: add 7 new dnsbl blacklists

---

dns/bind/Makefile
dns/bind/pkg-descr
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Domain.php
dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
dns/bind/src/opnsense/scripts/OPNsense/Bind/dnsbl.sh

Added new lists and marked zone management as experimental so the code can be released to stable branch.

dns/bind: add new lists, mark zone management as experimental

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Themes - Tukan/Cicada dropdown-menu shadow

Themes - Tukan/Cicada dropdown-menu shadow and other fixes

---

security/openconnect/Makefile
security/openconnect/pkg-descr
security/openconnect/src/opnsense/mvc/app/models/OPNsense/Openconnect/General.xml

security/openconnect: add pin-sha256 to certificate hash

---

www/nginx/pkg-descr
www/nginx/src/etc/inc/plugins.inc.d/nginx.inc

www/nginx: add xmlrpc support

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/OspfController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFRouteMaps.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf

net/frr: add route-maps to OSPF

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/upstream.conf

closes #1362
This is required for application servers, which do not have session sync.

www/nginx: ip hash

---

net/frr/Makefile
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt

net/frr: use correct table fields for OSPF route-maps

---

net/haproxy/Makefile
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml

none
- allow hyphens in server, frontend and backend names (#1346)
none

net/haproxy: release 2.16

---

vendor/os-sunnyvalley/Makefile
vendor/os-sunnyvalley/pkg-descr
vendor/os-sunnyvalley/src/etc/pkg/fingerprints/SunnyValley/trusted/updates.sunnyvalley.org.20190702
vendor/os-sunnyvalley/src/etc/pkg/repos/SunnyValley.conf

This plugin contains the vendor package repository information.
Vendor-provided package repository hosts os-sensei package and related dependencies.
https://github.com/opnsense/plugins/issues/1394

Introducing vendor/sunnyvalley plugin.

---

net/frr/Makefile
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf

Just fix this issue : https://github.com/opnsense/plugins/issues/1400

Fix frr ospfd template on redistribute config section

---

dns/bind/Makefile
dns/bind/pkg-descr
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
dns/bind/src/opnsense/scripts/OPNsense/Bind/dnsbl.sh
dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Dnsbl.xml
dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh

Add update and extra WindowsSpyBlocker list

---

security/maltrail/Makefile
security/maltrail/pkg-descr
security/maltrail/src/opnsense/mvc/app/views/OPNsense/Maltrail/general.volt

security/maltrail: add note to general tab regarding restart

---

security/maltrail/pkg-descr
security/maltrail/src/opnsense/mvc/app/controllers/OPNsense/Maltrail/forms/general.xml
security/maltrail/src/opnsense/mvc/app/models/OPNsense/Maltrail/General.xml
security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf

security/maltrail: add whitelist support

---

www/nginx/Makefile
www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
www/nginx/src/opnsense/scripts/nginx/tls_ua_fingerprint.php
www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf

this patch should increase performance (cpu, memory in web interface calls) and the log is now some kind of rotated.
Currently it may fill the disk.
Forum: https://forum.opnsense.org/index.php?topic=13282.0;topicseen

www/nginx TLS logrotate

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Themes - Cicada/Tukan - sensei color update

Themes - Cicada/Tukan - sensei color update

---

dns/bind/Makefile
dns/bind/pkg-descr
dns/bind/src/opnsense/service/templates/OPNsense/Bind/domain.db

dns/bind: fix template generation

---

sysutils/smart/src/opnsense/service/conf/actions.d/actions_smart.conf

os-smart: Fix duplicate descriptions.

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

color fix for both themes and smaller height of .page-content-head, .content-box-head

OPNsense 19.7.3: Colour of info logo is orange instead of green

---

security/etpro-telemetry/Makefile
security/etpro-telemetry/src/etc/cron.d/etpro-telemetry.cron
security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/send_heartbeat.py
security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/telemetry/__init__.py
security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/telemetry/state.py
security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/telemetry/system.py
security/etpro-telemetry/src/opnsense/scripts/suricata/metadata/rules/et-telemetry.xml

updated statistics, docs in https://github.com/opnsense/docs/commit/4831f5f2ddef4cd3a9cdeeed86e57bef439e51f5

ETPro Telemetry

---

net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMapfile.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M2_8_0.php
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: more additions for release 2.19

---

dns/unbound-plus/Makefile
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/Api/ServiceController.php
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/forms/dnsbl.xml
dns/unbound-plus/src/opnsense/mvc/app/models/OPNsense/Unboundplus/Dnsbl.xml
dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.sh
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/+TARGETS
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/dnsbl.inc
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/whitelist.inc

@fichtner I know you'll have a deeper look into dnsbl.sh :)

dns/unbound-plus: add whitelisting

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/general.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/General.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Menu/Menu.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
net-mgmt/telegraf/src/www/diag_logs_telegraf.php

See: https://github.com/opnsense/plugins/issues/1437

net-mgmt/telegraf: Fix 'Round Interval' setting not working, Add 'debug', 'quiet' setting and log viewer

---

security/maltrail/Makefile
security/maltrail/pkg-descr
security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf

security/maltrail: fix typo in template generation

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Themes - Tukan/Cicada - some fixes and improvements

Themes - Tukan/Cicada - some fixes and improvements

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6Interface.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf

Closes #1418 
* add changelog for 1.12 to respect other commits
* fix network type for ospfv3
* add passive-interface for ospfv3

net/frr: add some OSPFv3 features and fixes

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

closes #1518
Maybe as an advanced option?

Add OCSP Stapling for nginx

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf

@fichtner this bug may prevent a template reload so it should be merged for the next release.

www/nginx: fix broken template

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css

Theme Cicada - link fix
https://github.com/opnsense/plugins/issues/1538

Theme Cicada - link fix

---

misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css

Theme Cicada - missing last fix

---

www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

see: #1544
also fixes a bug that a directive may be ignored.

www/nginx: allow to configure request buffer size

---

net/relayd/Makefile
net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Migrations/M1_0_2.php
net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Relayd.xml
net/relayd/src/opnsense/service/templates/OPNsense/Relayd/relayd.conf

Relayd bugfix

---

vendor/sunnyvalley/Makefile
vendor/sunnyvalley/pkg-descr

Make the plugin description more informative

os-sunnyvalley: description update

---

dns/unbound-plus/Makefile
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/Api/MiscellaneousController.php
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/Api/ServiceController.php
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/MiscellaneousController.php
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/forms/miscellaneous.xml
dns/unbound-plus/src/opnsense/mvc/app/models/OPNsense/Unboundplus/Menu/Menu.xml
dns/unbound-plus/src/opnsense/mvc/app/models/OPNsense/Unboundplus/Miscellaneous.php
dns/unbound-plus/src/opnsense/mvc/app/models/OPNsense/Unboundplus/Miscellaneous.xml
dns/unbound-plus/src/opnsense/mvc/app/views/OPNsense/Unboundplus/dnsbl.volt
dns/unbound-plus/src/opnsense/mvc/app/views/OPNsense/Unboundplus/miscellaneous.volt
dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.sh
dns/unbound-plus/src/opnsense/service/conf/actions.d/actions_unboundplus.conf
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/+TARGETS
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/miscellaneous.conf

Introduces Miscellaneous submenu, adding CSVListField for private-domain to clear user questions regarding private IPs in unbound.

dns/unbound-plus: add private-domain feature

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

also clean up some whitespaces.

[www/nginx] #1561 advanced buffering

---

sysutils/nut/pkg-descr
sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/forms/settings.xml
sysutils/nut/src/opnsense/service/templates/OPNsense/Nut/ups.conf

Closes #964 
As we didn't release 1.6 yet no need to bump version

sysutils/nut: fix permissions for blazer_ser driver

---

mail/postfix/Makefile
mail/postfix/pkg-descr
mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf

mail/postfix: fix sort order in smtpd restrictions

---

dns/bind/Makefile
dns/bind/pkg-descr
dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Record.xml

dns/bind: add new ressource records types

---

mail/rspamd/Makefile
mail/rspamd/pkg-descr
mail/rspamd/src/opnsense/mvc/app/controllers/OPNsense/Rspamd/forms/settings.xml
mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/+TARGETS
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/history_redis.conf

mail/rspamd: add history rows

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

Closes #1598 
While here also fix a bug where multiple sets would be possible

net/frr: fix route-maps with ipv6 prefix-lists

---

net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/rip.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/RIP.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ripd.conf

Closes #1595 
While here fix migration error message from RIP

net/frr: add default-metric to RIP

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/+TARGETS
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-dhcp_sqlippool
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-sql
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-sqlippool
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/queries.conf
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/queries2.conf

Finally ... 
Closes #1604 
Closes #1322

net/freeradius: fix sqlite support

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Themes - Tukan/Cicada - Sensei color fixes

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/settings.xml
net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml
net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/+TARGETS
net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agent.psk
net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agentd.conf

net-mgmt/zabbix-agent: Add PSK encryption

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/tokenize2.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/nv.d3.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/tokenize2.css

short redesign (colors and visual improvements)

Theme/Cicada - update

---

security/maltrail/Makefile
security/maltrail/pkg-descr
security/maltrail/src/opnsense/mvc/app/models/OPNsense/Maltrail/Sensor.xml

security/maltrail: fix remoteserver labeling

---

net-mgmt/zabbix4-proxy/Makefile
net-mgmt/zabbix4-proxy/pkg-descr
net-mgmt/zabbix4-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
net-mgmt/zabbix4-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml
net-mgmt/zabbix4-proxy/src/opnsense/mvc/app/views/OPNsense/Zabbixproxy/general.volt
net-mgmt/zabbix4-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf

Closes #1550 
Add ProxyOfflineBuffer, switch to new ServiceControlUI function and small indent fix for save button

net-mgmt/zabbix4-proxy: add ProxyOfflineBuffer

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsgeneral.volt
net/frr/src/opnsense/scripts/quagga/quagga.rb

fix null route parsing (missing in regular expression)
add "via" to IPv4 routing table (was missing)
closes #1580

Frr null routes

---

net/haproxy/Makefile
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

none
none
- update stats socket permission for easier (non-root) monitoring (#1232)

net/haproxy: release 2.20

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Hard to read tables when using a warning colour.

Colour Change to table warning

---

sysutils/mail-backup/Makefile
sysutils/mail-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Mailer.php

Fixes the issue reported in #1617 and #1540.

sysutils/mail-backup: bugfix release 1.1

---

net-mgmt/zabbix4-proxy/Makefile
net-mgmt/zabbix4-proxy/pkg-descr
net-mgmt/zabbix4-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
net-mgmt/zabbix4-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml

net-mgmt/zabbix4-proxy: allow multiple listen address

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/mvc/app/controllers/OPNsense/Dnscryptproxy/Api/WhitelistController.php
dns/dnscrypt-proxy/src/opnsense/mvc/app/controllers/OPNsense/Dnscryptproxy/forms/dialogEditDnscryptproxyWhitelist.xml
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Whitelist.xml

dns/dnscrypt: add description field

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml

See:
* https://support.cloudflare.com/hc/de/articles/200170786-Wiederherstellen-von-urspr%C3%BCnglichen-Besucher-IPs-Protokollieren-von-Besucher-IP-Adressen-mit-mod-cloudflare-
* https://support.cloudflare.com/hc/en-us/articles/206776727-What-is-True-Client-IP-
Requested via Forum

www/nginx: Add header for Cloudflare

---

README.md
net/tayga/Makefile
net/tayga/pkg-descr
net/tayga/src/etc/inc/plugins.inc.d/tayga.inc
net/tayga/src/etc/rc.d/opnsense-tayga
net/tayga/src/opnsense/mvc/app/controllers/OPNsense/Tayga/Api/GeneralController.php
net/tayga/src/opnsense/mvc/app/controllers/OPNsense/Tayga/Api/ServiceController.php
net/tayga/src/opnsense/mvc/app/controllers/OPNsense/Tayga/GeneralController.php
net/tayga/src/opnsense/mvc/app/controllers/OPNsense/Tayga/forms/general.xml
net/tayga/src/opnsense/mvc/app/models/OPNsense/Tayga/ACL/ACL.xml
net/tayga/src/opnsense/mvc/app/models/OPNsense/Tayga/General.php
net/tayga/src/opnsense/mvc/app/models/OPNsense/Tayga/General.xml
net/tayga/src/opnsense/mvc/app/models/OPNsense/Tayga/Menu/Menu.xml
net/tayga/src/opnsense/mvc/app/views/OPNsense/Tayga/general.volt
net/tayga/src/opnsense/scripts/OPNsense/Tayga/setup.sh
net/tayga/src/opnsense/service/conf/actions.d/actions_tayga.conf
net/tayga/src/opnsense/service/templates/OPNsense/Tayga/+TARGETS
net/tayga/src/opnsense/service/templates/OPNsense/Tayga/tayga
net/tayga/src/opnsense/service/templates/OPNsense/Tayga/tayga.conf

net/tayga: New plugin

---

README.md
sysutils/munin-node/Makefile
sysutils/munin-node/pkg-descr
sysutils/munin-node/src/etc/inc/plugins.inc.d/muninnode.inc
sysutils/munin-node/src/opnsense/mvc/app/controllers/OPNsense/Muninnode/Api/GeneralController.php
sysutils/munin-node/src/opnsense/mvc/app/controllers/OPNsense/Muninnode/Api/ServiceController.php
sysutils/munin-node/src/opnsense/mvc/app/controllers/OPNsense/Muninnode/GeneralController.php
sysutils/munin-node/src/opnsense/mvc/app/controllers/OPNsense/Muninnode/forms/general.xml
sysutils/munin-node/src/opnsense/mvc/app/models/OPNsense/Muninnode/ACL/ACL.xml
sysutils/munin-node/src/opnsense/mvc/app/models/OPNsense/Muninnode/General.php
sysutils/munin-node/src/opnsense/mvc/app/models/OPNsense/Muninnode/General.xml
sysutils/munin-node/src/opnsense/mvc/app/models/OPNsense/Muninnode/Menu/Menu.xml
sysutils/munin-node/src/opnsense/mvc/app/views/OPNsense/Muninnode/general.volt
sysutils/munin-node/src/opnsense/scripts/OPNsense/Muninnode/setup.sh
sysutils/munin-node/src/opnsense/service/conf/actions.d/actions_muninnode.conf
sysutils/munin-node/src/opnsense/service/templates/OPNsense/Muninnode/+TARGETS
sysutils/munin-node/src/opnsense/service/templates/OPNsense/Muninnode/munin-node.conf
sysutils/munin-node/src/opnsense/service/templates/OPNsense/Muninnode/munin_node

Initial commit, needs chmod as usual.

sysutils/munin-node: New plugin

---

dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.py

Fix for these cases: https://regex101.com/r/bvFdTx/1
Old regex: https://regex101.com/r/26kAMb/1

DNSBL - Fix regex for domains starting with number

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/scripts/systemhealth/logformats/freeradius.py

Add log parser for upcoming feature in core.
This changes can already be merged and will take effect as soon as the core will be updated.
**Before**
**After**
**Additional context**
#1701 and opnsense/core#3941
**Special thanks to @AdSchellevis for making this possible**

net/freeradius: Add log parser to display logs correctly

---

security/tinc/src/opnsense/scripts/OPNsense/Tinc/tincd.py

The bug and the proposed solution are described at https://github.com/opnsense/plugins/issues/1686.

security/tinc: fix a bug in IPv6 support

---

mail/postfix/Makefile
mail/postfix/pkg-descr
mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf

https://forum.opnsense.org/index.php?topic=15968.msg73130#msg73130

mail/postfix: add more antispam features

---

net/firewall/Makefile
net/firewall/pkg-descr
net/firewall/src/etc/inc/plugins.inc.d/pfplugin.inc
net/firewall/src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/FilterController.php
net/firewall/src/opnsense/mvc/app/controllers/OPNsense/Firewall/FilterController.php
net/firewall/src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/dialogFilterRule.xml
net/firewall/src/opnsense/mvc/app/models/OPNsense/Firewall/ACL/ACL.xml
net/firewall/src/opnsense/mvc/app/models/OPNsense/Firewall/FieldTypes/FilterRuleField.php
net/firewall/src/opnsense/mvc/app/models/OPNsense/Firewall/Filter.php
net/firewall/src/opnsense/mvc/app/models/OPNsense/Firewall/Filter.xml
net/firewall/src/opnsense/mvc/app/models/OPNsense/Firewall/Menu/Menu.xml
net/firewall/src/opnsense/mvc/app/views/OPNsense/Firewall/filter.volt
net/firewall/src/opnsense/scripts/pfplugin/rollback_cancel
net/firewall/src/opnsense/scripts/pfplugin/rollback_timer
net/firewall/src/opnsense/service/conf/actions.d/actions_pfplugin.conf

https://github.com/opnsense/plugins/issues/1720

Initial version of firewall api plugin.

---

net/tayga/src/etc/rc.d/opnsense-tayga
net/tayga/src/opnsense/service/templates/OPNsense/Tayga/tayga
net/tayga/src/opnsense/service/templates/OPNsense/Tayga/tayga.conf

@mimugmail, I found and fixed some minor bugs.
It now works without any manual configuration on the console. And it keeps working after a reboot.
(I have not done any serious stability testing yet. It would be great if someone else could test this, too.)

net/tayga: bugfixes for TUN interface and Tayga IPv6 addresses

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt

and make it searchable.
Did some troubleshooting with customer and it was really easy to disable rules when having the rule numer in place

www/nginx: add NAXSI rule ID to volt 

---

dns/bind/Makefile
dns/bind/pkg-descr

dns/bind: update plugin to version 9.16

---

security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php

add export of fullchain.pem, solves [1732](https://github.com/opnsense/plugins/issues/1732)

security/acme-client: add export of fullchain.pem

---

net/haproxy/Makefile
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/rc-wrapper.sh

net/haproxy: override "graceful" restart

---

www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/vts.volt

Looks like a typo to me, but please may some once double check that I didn't break anything.

removed typo "upstremModel"

---

security/maltrail/Makefile
security/maltrail/pkg-descr
security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf

... to reflect latest changes and bump version

security/maltrail: disable alienvault, update changelog

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

- add support for dnsapi SchlundTech (#1728)
- add support for dnsapi Euserv (#1779)
- add support for dnsapi Leaseweb (#1670)
none
- sftp export: make the "fullchain" filename configurable (#1776)

securiy/acme-client: release 1.31

---

dns/unbound-plus/Makefile
dns/unbound-plus/pkg-descr
dns/unbound-plus/src/opnsense/mvc/app/controllers/OPNsense/Unboundplus/forms/miscellaneous.xml
dns/unbound-plus/src/opnsense/mvc/app/models/OPNsense/Unboundplus/Miscellaneous.xml
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/+TARGETS
dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/dot.conf

Finally there's DNS over TLS :)

dns/unbound-plus: add DoT support

---

security/stunnel/Makefile
security/stunnel/pkg-descr
security/stunnel/src/etc/inc/plugins.inc.d/stunnel.inc
security/stunnel/src/opnsense/mvc/app/controllers/OPNsense/Stunnel/Api/ServiceController.php
security/stunnel/src/opnsense/mvc/app/controllers/OPNsense/Stunnel/Api/ServicesController.php
security/stunnel/src/opnsense/mvc/app/controllers/OPNsense/Stunnel/ServicesController.php
security/stunnel/src/opnsense/mvc/app/controllers/OPNsense/Stunnel/forms/dialogService.xml
security/stunnel/src/opnsense/mvc/app/models/OPNsense/Stunnel/ACL/ACL.xml
security/stunnel/src/opnsense/mvc/app/models/OPNsense/Stunnel/Menu/Menu.xml
security/stunnel/src/opnsense/mvc/app/models/OPNsense/Stunnel/Stunnel.php
security/stunnel/src/opnsense/mvc/app/models/OPNsense/Stunnel/Stunnel.xml
security/stunnel/src/opnsense/mvc/app/views/OPNsense/Stunnel/services.volt
security/stunnel/src/opnsense/scripts/stunnel/generate_certs.php
security/stunnel/src/opnsense/service/conf/actions.d/actions_stunnel.conf
security/stunnel/src/opnsense/service/templates/OPNsense/Stunnel/+TARGETS
security/stunnel/src/opnsense/service/templates/OPNsense/Stunnel/rc.conf.d
security/stunnel/src/opnsense/service/templates/OPNsense/Stunnel/stunnel.conf
security/stunnel/src/opnsense/service/templates/OPNsense/Syslog/local/stunnel.conf

https://github.com/opnsense/plugins/issues/1829
this PR contains the core functionality of our stunnel plugin, excluding support for a local ident server.

stunnel: initial release 

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

Added Telegraf InfluxDB v2 Output Support

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

- add support for dnsapi ArvanCloud (#1834)
- add support for dnsapi Hetzner (#1870)
none
- restore proper sorting in DNS API list

securiy/acme-client: release 1.34

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml

Reported here: https://forum.opnsense.org/index.php?topic=17700.0

net/freeradius: fix Login-Time validation

---

misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Colours incorrect on firewall.

Correct colours in text-info and circle::before

---

net/wireguard/Makefile
net/wireguard/src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt

net/wireguard: remove beta warning

---

net/chrony/Makefile
net/chrony/pkg-descr
net/chrony/src/etc/inc/plugins.inc.d/chrony.inc
net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/Api/GeneralController.php
net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/Api/ServiceController.php
net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/GeneralController.php
net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/forms/general.xml
net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/ACL/ACL.xml
net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/General.php
net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/General.xml
net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/Menu/Menu.xml
net/chrony/src/opnsense/mvc/app/views/OPNsense/Chrony/general.volt
net/chrony/src/opnsense/scripts/OPNsense/Chrony/setup.sh
net/chrony/src/opnsense/service/conf/actions.d/actions_chrony.conf
net/chrony/src/opnsense/service/templates/OPNsense/Chrony/+TARGETS
net/chrony/src/opnsense/service/templates/OPNsense/Chrony/chrony.conf
net/chrony/src/opnsense/service/templates/OPNsense/Chrony/chronyd

Just a really small plugin where ntp has problems to correctly synchronize time.
I experienced this rarely on virtual environments but chrony seems to do the trick.

net/chrony: New plugin

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php

acme-client: add support for Linode Cloud API

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr
net-mgmt/zabbix-agent/src/opnsense/scripts/systemhealth/logformats/zabbix_agentd.py

net-mgmt/zabbix-agent: logformat file for WebUI

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr

- switch to Zabbix Agent 5.0, a new major release (#1938)
- fix GUI logformat (#1954)
none

net-mgmt/zabbix-agent: release 1.8

---

security/acme-client/Makefile
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf

- add ability to rerun automations (#1962)
none
none

security/acme-client: release 1.36

---

dns/bind/src/opnsense/scripts/OPNsense/Bind/dnsbl.sh
dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh

These links were updated to reflect the current hosting platform that allows for last-modified header.

Updated Project Block List URL

---

dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindDomain.xml

dns/bind: enhance help-text for domain transfer

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf

net/frr: fix ospf6 router-id changes with frr7

---

mail/rspamd/Makefile
mail/rspamd/pkg-descr
mail/rspamd/src/opnsense/mvc/app/controllers/OPNsense/Rspamd/forms/settings.xml
mail/rspamd/src/opnsense/mvc/app/models/OPNsense/Rspamd/RSpamd.xml
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/+TARGETS
mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/options.inc

mail/rspamd: add option to set a nameserver

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/main.css

interfaces / netstat color fixes
sensei / some color fixes
ipsec / color fix

Cicada/Vicuna Theme Updates

---

net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

update bgp as-path command

---

misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css

Tukan Theme Updates

---

mail/postfix/Makefile
mail/postfix/pkg-descr

mail/postfix: bump version

---

net/frr/Makefile
net/frr/pkg-descr

net/frr: bump version

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsKas.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

security/acme-client: add support for All-Inkl.com domain API

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 2.25

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPASPath.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPPrefixLists.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPRouteMaps.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt

net/frr: add description fields to BGP

---

sysutils/hw-probe/Makefile
sysutils/hw-probe/pkg-descr
sysutils/hw-probe/src/opnsense/mvc/app/controllers/OPNsense/Hwprobe/Api/GeneralController.php
sysutils/hw-probe/src/opnsense/mvc/app/controllers/OPNsense/Hwprobe/Api/ServiceController.php
sysutils/hw-probe/src/opnsense/mvc/app/controllers/OPNsense/Hwprobe/GeneralController.php
sysutils/hw-probe/src/opnsense/mvc/app/controllers/OPNsense/Hwprobe/forms/general.xml
sysutils/hw-probe/src/opnsense/mvc/app/models/OPNsense/Hwprobe/ACL/ACL.xml
sysutils/hw-probe/src/opnsense/mvc/app/models/OPNsense/Hwprobe/General.php
sysutils/hw-probe/src/opnsense/mvc/app/models/OPNsense/Hwprobe/General.xml
sysutils/hw-probe/src/opnsense/mvc/app/models/OPNsense/Hwprobe/Menu/Menu.xml
sysutils/hw-probe/src/opnsense/mvc/app/views/OPNsense/Hwprobe/general.volt
sysutils/hw-probe/src/opnsense/service/conf/actions.d/actions_hwprobe.conf

Requested by @lattera 
Sends anonymized hardware diagnostics to bsd-hardware.info, great tool to share insights when diagnosing problems

sysutils/hw-probe: New plugin

---

net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFNetwork.xml

Area can only be used one time.

net/frr: Update help-text in OSPF

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPCommunityLists.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPRouteMaps.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

net/frr: add community-lists to BGP

---

net/frr/src/etc/rc.syshook.d/carp/50-frr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
net/frr/src/opnsense/scripts/frr/carp_event_handler
net/frr/src/opnsense/scripts/frr/lib/__init__.py
net/frr/src/opnsense/scripts/frr/lib/base.py
net/frr/src/opnsense/scripts/frr/lib/events/__init__.py
net/frr/src/opnsense/scripts/frr/lib/events/ospfd.py
net/frr/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd_carp.conf
net/frr/src/opnsense/service/templates/OPNsense/Syslog/local/routing_frr.conf

Implement https://github.com/opnsense/plugins/issues/2091 and fix some minor validation / presentation issues in existing forms.

FRR: OSPF influence interface cost via carp

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php

security/acme-client: fix certificate chain when CA changes

---

net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

net/frr: Add BGP neighbor timers and graceful restart

---

net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf

Followup for #1443 to support IPv6 gateway address as well.

net/wireguard: add IPv6 gateway support for PBR via PF

---

net/wireguard/Makefile
net/wireguard/pkg-descr

net/wireguard: bump version

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf

net/frr: add IntegerField for auto-cost calculation

---

net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/general.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
net/frr/src/opnsense/service/templates/OPNsense/Quagga/ripd.conf
net/frr/src/opnsense/service/templates/OPNsense/Quagga/zebra.conf

net/frr: Add FRR profile selection (defaults directive)

---

security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php

security/acme-client: fix challenge alias mode

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsHexonet.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsLexicon.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsLinode.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsLinodeV4.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNamesilo.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNetcup.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

see plugin changelog for further details

security/acme-client: release 2.2

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/+TARGETS
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-dhcp_sqlippool
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-mac2ip

net/freeradius: Fix DHCP support

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsAli.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsInfomaniak.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/lecert.php
security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf

security/acme-client: release 2.3

---

net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/MaintenanceController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/ServiceController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/StatisticsController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/MaintenanceController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/maintenanceCronjobs.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/maintenance.volt
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

Final bug fixes and improvements for os-haproxy 3.0, refs https://github.com/opnsense/plugins/pull/2214.

net/haproxy: finishing touches for release 3.0

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/main.css

Theme Cicada/Vicuna little design update
included requested cross-out/strikeout text in the row for disabled rules/nat
https://forum.opnsense.org/index.php?topic=21634.15

Theme Cicada/Vicuna little design update

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M3_1_0.php

net/haproxy: release 3.1

---

net/wireguard/src/opnsense/service/conf/actions.d/actions_wireguard.conf

Make Wireguard rebootable via cron Job
#2268

Update actions_wireguard.conf | Make Wireguard rebootable via Croin

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

net-mgmt/telegraf: add datadog output

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/etc/inc/plugins.inc.d/freeradius.inc

net/freeradius: Add HA config sync

---

mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/dialogEditPostfixHeadercheck.xml
mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml

mail/postfix: more typo fixes.

---

net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Client.xml
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/clients.conf

net/freeradius: Add IPv6 support to client IP and harden loose model

---

net-mgmt/zabbix5-proxy/Makefile
net-mgmt/zabbix5-proxy/pkg-descr
net-mgmt/zabbix5-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
net-mgmt/zabbix5-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml
net-mgmt/zabbix5-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf

Closes #2275 and #2097 
* Allow setting ConfigFrequency
* Allow setting DataSenderFrequency
* Allow setting StartVMwareCollectors

net-mgmt/zabbix-proxy: Add multiple settings to GUI

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf

Hi!
Just corrected version of https://github.com/opnsense/plugins/pull/1991
also added a hook for post-conf.
fixes https://github.com/opnsense/plugins/issues/2006
Thanks!

www/nginx: insert correct SNI name. Add hook

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf

Fix for 
https://github.com/opnsense/plugins/issues/2111

fix(Issue: 2111) Nginx Apply load balancing for UDP

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt

Added columns to grid of many views and fixed width of boolean column to save space for smaller screens.
Changed columns:
- Locations
- _WAF Enabled_ changed to _WAF Status_ (enabled/disabled/learning)
- Additional optional columns: upstream, XSS score, SQLi score, WAF policies
- Upstreams
- Added: HTTPS enabled
- Added optional: load balancing algorithm
- Servers
- Added optional: locations, file system root
- WAF policies:
- Added optional: rules
- WAF rules:
- Added: match type, score
- Added optional: match value

www/nginx: Grid view improvements

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 3.2

---

misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/jquery.bootgrid.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Minor colour corrections

---

net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml

Minor edit to make error message clearer.

Minor update to Server.xml

---

net-mgmt/net-snmp/Makefile
net-mgmt/net-snmp/pkg-descr
net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/forms/general.xml
net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/General.xml
net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd.conf

- Add boolean variable for AgentX support to model
- Add to checkbox to General form.
- Add agentx config to template.
- Answers https://github.com/opnsense/plugins/issues/1200
(split out from multi-plugin patch previously submitted)

net-mgmt/net-snmp: Add support for agentx

---

net/chrony/Makefile
net/chrony/pkg-descr
net/chrony/src/opnsense/service/templates/OPNsense/Chrony/chrony.conf

net/chrony: add makestep to default config

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NaxsiIdentifierConstraint.php
www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NgxBusyBufferConstraint.php

@AdSchellevis merge it when you feel ready
closes #2343

www/nginx: source code migration for Phalcon 4

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt

security/acme-client: release 2.5

---

sysutils/puppet-agent/Makefile
sysutils/puppet-agent/pkg-descr
sysutils/puppet-agent/src/etc/inc/plugins.inc.d/puppetagent.inc
sysutils/puppet-agent/src/opnsense/mvc/app/controllers/OPNsense/PuppetAgent/Api/ServiceController.php
sysutils/puppet-agent/src/opnsense/mvc/app/controllers/OPNsense/PuppetAgent/Api/SettingsController.php
sysutils/puppet-agent/src/opnsense/mvc/app/controllers/OPNsense/PuppetAgent/IndexController.php
sysutils/puppet-agent/src/opnsense/mvc/app/controllers/OPNsense/PuppetAgent/forms/general.xml
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/ACL/ACL.xml
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/Menu/Menu.xml
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/PuppetAgent.php
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/PuppetAgent.xml
sysutils/puppet-agent/src/opnsense/mvc/app/views/OPNsense/PuppetAgent/index.volt
sysutils/puppet-agent/src/opnsense/service/conf/actions.d/actions_puppetagent.conf
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/+TARGETS
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/puppetagent.conf
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/rc.conf.d

depends on https://github.com/opnsense/tools/pull/228

Add puppet-agent plugin

---

net/relayd/src/opnsense/mvc/app/views/OPNsense/Relayd/status.volt

for https://github.com/opnsense/plugins/issues/2232
minor visual improvements on the status page.
o reset cursor pointer on status widgets
o in host column add one button spacing for better alignment
o add a space between buttons and text

net/relayd: Usability improvements 

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/scripts/OPNsense/Telegraf/setup.sh
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf

net-mgmt/telegraf: add telegraf.d as config include

---

dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc

Added missing `break` for All-Inkl

dns/dyndns All-Inkl: Added missing break

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap

net/freeradius: remove LEAP

---

mail/fetchmail/Makefile
mail/fetchmail/src/opnsense/scripts/OPNsense/Fetchmail/setup.sh

mail/fetchmail: fix fetchmailrc permissions

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr
net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/settings.xml
net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml

see changelog for further details

net-mgmt/zabbix-agent: release 1.9

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsDomeneshop.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsIonos.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNamecheap.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

see changelog for further details

security/acme-client: release 2.6

---

net/haproxy/pkg-descr
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

see changelog for further details

net/haproxy: release 3.4

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Menu/Menu.xml
dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/setup.sh

Fix logging due to Phalcon4 update
Closes #2440

dns/dnscrypt-proxy: fix logging

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/general.xml
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/General.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
net-mgmt/telegraf/src/opnsense/scripts/OPNsense/Telegraf/setup.sh
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

Add unbound statistics and change permissions (add group wheel)

net-mgmt/telegraf: add unbound

---

net/haproxy/Makefile
net/haproxy/pkg-descr

net/haproxy: release 3.5

---

dns/dnscrypt-proxy/src/opnsense/service/templates/OPNsense/Dnscryptproxy/dnscrypt-proxy.toml

Closes #2490 
No version bump due to #2518

dns/dnscrypt-proxy: rename label in templating

---

net-mgmt/collectd/Makefile
net-mgmt/collectd/pkg-descr
net-mgmt/collectd/src/opnsense/mvc/app/controllers/OPNsense/Collectd/forms/general.xml
net-mgmt/collectd/src/opnsense/mvc/app/models/OPNsense/Collectd/General.xml
net-mgmt/collectd/src/opnsense/service/templates/OPNsense/Collectd/collectd.conf

net-mgmt/collectd: Add tcpconns and ipstats plugins

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/eap.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/clients.conf
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap

net/freeradius: fix secret and allow ecdh curve selection

---

net/chrony/Makefile
net/chrony/pkg-descr
net/chrony/src/opnsense/service/conf/actions.d/actions_chrony.conf

net/chrony: Adjust chronyc timeouts

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/lecert.php
security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf

security/acme-client: release 3.2

---

net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogResolver.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: add support for additional resolver options

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/etc/rc.syshook.d/start/50-haproxy
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogResolver.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml

net/haproxy: release 3.6

---

sysutils/puppet-agent/pkg-descr
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/Menu/Menu.xml
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/PuppetAgent.xml
sysutils/puppet-agent/src/opnsense/mvc/app/views/OPNsense/PuppetAgent/index.volt
sysutils/puppet-agent/src/opnsense/scripts/systemhealth/logformats/puppet_agent.py
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/+TARGETS
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/newsyslog.conf
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/puppetagent.conf

This PR adds the following:
* add log file
* add introduction page
* add menu icon
* add version number to model
* add plugin changelog
Related to https://github.com/opnsense/plugins/pull/2570.

sysutils/puppet-agent: additions for release 1.0

---

net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalSettings.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: additions for release 3.6

---

misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Override colour given in the vpn_ipsec.php file

Override colour given in the vpn_ipsec.php file

---

net/freeradius/Makefile
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/general.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/General.xml
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users

Added support for Extreme networks EXOS switch Extreme-Netlogin-Extended-VLAN VSA and policy for GEN2
Tested with multiple switches.

Added support for Extreme networks EXOS switches VLAN and policy management

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogLua.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M3_3_0.php
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/maintenance.volt
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportLuaScripts.php
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 3.7

---

dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc

Use the right URL for FreeDNS

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

net/telegraf: Add skip_verify also to influxv2

---

net/wireguard/Makefile
net/wireguard/pkg-descr
net/wireguard/src/etc/inc/plugins.inc.d/wireguard.inc

net/wireguard: rename WireGuard to WireGuard (Group) in filter rules

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeFritzbox.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeSynologyDsm.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdGeneric.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdRestartGui.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdRestartHaproxy.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdRestartNginx.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdUploadHighwinds.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdUploadSftp.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M3_1_0.php
security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/+TARGETS
security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/syslog-filter.conf

security/acme-client: release 3.5

---

sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/forms/settings.xml

/ref https://forum.opnsense.org/index.php?topic=25581.0

add more info what actually happens when nut is enabled

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr
net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agentd.conf

for #2129
depends on https://github.com/opnsense/tools/pull/251

net-mgmt/zabbix-agent: add variants support / release 1.10

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php

security/acme-client: release 3.6

---

net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/settings.xml

net-mgmt/zabbix-agent: update help text

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalDefaults.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/setup.sh
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 3.8

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php

security/acme-client: fix acme.sh deploy hook error handling

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsDynv6.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/HttpOpnsense.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/TlsalpnAcme.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidationFactory.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/validations.volt

security/acme-client: additions for release 3.6

---

net-mgmt/zabbix-proxy/Makefile
net-mgmt/zabbix-proxy/pkg-descr
net-mgmt/zabbix-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
net-mgmt/zabbix-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml
net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf.in

net-mgmt/zabbix-proxy: Add Allowed Stats IP

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsGcloud.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt

security/acme-client: release 3.7

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M3_5_0.php
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 3.9

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

net-mgmt/telegraf: add timeout to unbound input

---

security/openconnect/Makefile
security/openconnect/pkg-descr
security/openconnect/src/opnsense/mvc/app/models/OPNsense/Openconnect/General.xml

I'm very sorry for everyone with more that 64 to type :)
Closes #2735

security/openconnect: allow username to be 64 characters long

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

net/frr: add "all" parameter to BGP neighbor

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

www/nginx: default_server for https servers

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/AccountsController.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/accounts.volt

security/acme-client: release 3.8

---

net/haproxy/pkg-descr
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: additions for release 3.9

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsSelfhost.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Adding Selfhost DNS for acme.sh
https://github.com/acmesh-official/acme.sh/pull/3873

Adding Selfhost DNS for acme.sh

---

www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml

Nginx model was modified in 5a61822 but model version was not incremented.

www/nginx: model was modified in 5a61822 but version not incremented

---

net/wireguard/Makefile
net/wireguard/pkg-descr
net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml

net/wireguard: Allow 100 instances

---

net/mdns-repeater/src/etc/inc/plugins.inc.d/mdnsrepeater.inc
net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/IndexController.php
net/mdns-repeater/src/opnsense/mvc/app/models/OPNsense/MDNSRepeater/ACL/ACL.xml
net/mdns-repeater/src/opnsense/mvc/app/models/OPNsense/MDNSRepeater/Menu/Menu.xml

Extracted from https://github.com/opnsense/plugins/pull/2762 for easier review.

mDNS repeater: cosmetic fixes

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh

Closes #2776 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253893
https://stackoverflow.com/questions/16414410/delete-empty-lines-using-sed (short version not valid anymore)

net/dnscrypt-proxy: replace sed syntax which breaks in F13

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr
net-mgmt/zabbix-agent/src/opnsense/service/conf/actions.d/actions_zabbixagent.conf

... to allow restart via cron.

net-mgmt/zabbix-agent: Add description to restart action

---

net/mdns-repeater/src/etc/rc.syshook.d/carp/50-mdns
net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/forms/general.xml
net/mdns-repeater/src/opnsense/mvc/app/models/OPNsense/MDNSRepeater/MDNSRepeater.xml
net/mdns-repeater/src/opnsense/service/templates/OPNsense/MDNSRepeater/mdnsrepeater

Only run the repeater on one node.
Fixes https://github.com/opnsense/plugins/issues/2595.

Add CARP hook for mDNS repeater.

---

dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/Api/AccountsController.php
dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/settings.xml
dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
dns/ddclient/src/opnsense/mvc/app/views/OPNsense/DynDNS/index.volt
dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf

merges https://github.com/opnsense/plugins/pull/2791 and https://github.com/opnsense/plugins/pull/2808

dns/ddclient: Use interface as ip source + custom service

---

dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf

DNS-O-Matic service, tested and it's working.

dns/ddclient add dns-o-matic

---

net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/sites-enabled-inner-tunnel

net/freeradius: Update sites-enabled-inner-tunnel

---

dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf

Add FreeDNS (freedns.afraid.org) service.
Tested and it's working.

dns/ddclient add FreeDNS

---

dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf

Add DNS Made Easy.
I'm not able to test, because I do not use the service.
But according to the [ddclient example](https://github.com/ddclient/ddclient/blob/master/ddclient.conf.in#L275) it should work.

dns/ddclient add DNS Made Easy

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsTransip.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

security/acme-client: Add support for Transip DNS API

---

net/chrony/Makefile
net/chrony/pkg-descr
net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/forms/general.xml
net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/General.xml
net/chrony/src/opnsense/service/templates/OPNsense/Chrony/chrony.conf

net/chrony: add fallbackpeer and no cert check

---

net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/Api/SettingsController.php
net/relayd/src/opnsense/mvc/app/views/OPNsense/Relayd/index.volt

closes https://github.com/opnsense/plugins/issues/2959

net/relayd - add listen address and port (range) to Virtual Server tab

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr

Added support for Zabbix Agent 6.0/

net-mgmt/zabbix-agent: Zabbix Agent 6.0

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml

security/acme-client: release 3.10

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr

net-mgmt/zabbix-agent: release 1.12

---

net-mgmt/zabbix-proxy/Makefile
net-mgmt/zabbix-proxy/pkg-descr

Added support for Zabbix Proxy 6.0.

net-mgmt/zabbix-proxy: Zabbix Proxy 6.0

---

vendor/sunnyvalley/Makefile
vendor/sunnyvalley/pkg-descr

Update Plug-in Description to reflect the new name, Zenarmor.

os-sunnyvalley: Update Product name to reflect the new name: Zenarmor

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/settings.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/nginx.conf

Hi!
Can we add headers_more module support please?)
thanks!
Tools pr https://github.com/opnsense/tools/pull/275

www/nginx: add headers_more support

---

www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf

like for http server add support for custom configuration in stream server

add support for custom configuration

---

www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/streamserver.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf

Allow to set the limit of UDP server responses
closes #2875

www/nginx #2875 fix - allow to set proxy_responses

---

sysutils/apcupsd/Makefile
sysutils/apcupsd/pkg-descr
sysutils/apcupsd/src/etc/inc/plugins.inc.d/apcupsd.inc
sysutils/apcupsd/src/opnsense/mvc/app/controllers/OPNsense/Apcupsd/Api/ServiceController.php
sysutils/apcupsd/src/opnsense/mvc/app/controllers/OPNsense/Apcupsd/Api/SettingsController.php
sysutils/apcupsd/src/opnsense/mvc/app/controllers/OPNsense/Apcupsd/IndexController.php
sysutils/apcupsd/src/opnsense/mvc/app/controllers/OPNsense/Apcupsd/StatusController.php
sysutils/apcupsd/src/opnsense/mvc/app/controllers/OPNsense/Apcupsd/forms/general.xml
sysutils/apcupsd/src/opnsense/mvc/app/models/OPNsense/Apcupsd/ACL/ACL.xml
sysutils/apcupsd/src/opnsense/mvc/app/models/OPNsense/Apcupsd/Apcupsd.php
sysutils/apcupsd/src/opnsense/mvc/app/models/OPNsense/Apcupsd/Apcupsd.xml
sysutils/apcupsd/src/opnsense/mvc/app/models/OPNsense/Apcupsd/Menu/Menu.xml
sysutils/apcupsd/src/opnsense/mvc/app/views/OPNsense/Apcupsd/index.volt
sysutils/apcupsd/src/opnsense/mvc/app/views/OPNsense/Apcupsd/status.volt
sysutils/apcupsd/src/opnsense/service/conf/actions.d/actions_apcupsd.conf
sysutils/apcupsd/src/opnsense/service/templates/OPNsense/Apcupsd/+TARGETS
sysutils/apcupsd/src/opnsense/service/templates/OPNsense/Apcupsd/apcupsd
sysutils/apcupsd/src/opnsense/service/templates/OPNsense/Apcupsd/apcupsd.conf
sysutils/apcupsd/src/www/widgets/include/apcupsd.inc
sysutils/apcupsd/src/www/widgets/widgets/apcupsd.widget.php

This is a plugin to configure the apcupsd service, it includes a widget for the dashboard
Originally started by @Gibbon99 and @mrzaz (please mention their contribution too), repo here: https://github.com/Gibbon99/apcupsd and my fork: https://github.com/xbb/apcupsd where you can see the full changelog/commit list
The source of this pull request is from my fork which includes improvements and the dashboard widget too
I cleared the changelog for the new initial version and set "devel" version 0.1 in the Makefile, also set myself as maintainer.
Forum thread: https://forum.opnsense.org/index.php?topic=21487.0
Configuration page:
Status page:
Widget:

sysutils/apcupsd: new plugin

---

www/nginx/src/opnsense/scripts/nginx/ngx_functions.js
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

Hi! can fix https://forum.opnsense.org/index.php?topic=28831.0 i hope
njs module now requires js_import directive (http://nginx.org/en/docs/http/ngx_http_js_module.html#js_include) and the use of the export statement in .js
Thanks!

www/nginx: njs0.7.1 compatibility (fixes startup error)

---

net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

Enables basic HTTP Authentication in Telegraf agains Elasticsearch

Enables basic HTTP Authentication agains Elasticsearch

---

security/crowdsec/+POST_INSTALL.post
security/crowdsec/+POST_INSTALL.pre
security/crowdsec/Makefile
security/crowdsec/pkg-descr
security/crowdsec/src/etc/rc.d/oscrowdsec
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/forms/general.xml
security/crowdsec/src/opnsense/mvc/app/models/OPNsense/CrowdSec/General.xml
security/crowdsec/src/opnsense/mvc/app/views/OPNsense/CrowdSec/general.volt
security/crowdsec/src/opnsense/scripts/OPNsense/CrowdSec/hub-upgrade.sh

This is ready for GA, can it be merged in 22.1 too? I don't know if you add new plugins to a stable release
thanks

security/crowdsec: v1.0

---

net/freeradius/Makefile
net/freeradius/pkg-descr
net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml

net/freeradius: Remove TTLS-GTC from default eap type

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsActive24.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Add new ACME challenge tyoe:
- Active24

acme-client: Add Active24 challenge type

---

net-mgmt/netdata/Makefile
net-mgmt/netdata/pkg-descr
net-mgmt/netdata/src/opnsense/service/templates/OPNsense/Netdata/netdata

See https://github.com/opnsense/plugins/issues/3002

net-mgmt/netdata: Remove MFS support for /var/log

---

sysutils/munin-node/Makefile
sysutils/munin-node/pkg-descr
sysutils/munin-node/src/opnsense/service/templates/OPNsense/Muninnode/munin_node

See https://github.com/opnsense/plugins/issues/3002

sysutils/munin-node: Remove MFS support for /var/log

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeVault.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsCf.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

see plugin changelog for further information

security/acme-client: release 3.12

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsUdr.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Add new ACME challenge tyoe:
- udr
refs https://github.com/opnsense/plugins/issues/3035

Add udr challenge type

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsMythicBeasts.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsMythicbeasts.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Add new API for ACME challenge types:
- Mythic Beasts
refs https://github.com/opnsense/plugins/issues/2998

acme-client: Add Mythic Beasts API for challenge types

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr
net-mgmt/zabbix-proxy/Makefile
net-mgmt/zabbix-proxy/pkg-descr

fixes https://github.com/opnsense/plugins/issues/3054
depends on https://github.com/opnsense/tools/pull/317

add Zabbix Agent/Proxy 6.2, remove 5.4

---

net/wireguard/Makefile
net/wireguard/pkg-descr
net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml

Closes #3101 
No idea why name in endpoint was HostnameField ...

net/wireguard: adjust naming validation

---

security/crowdsec/Makefile
security/crowdsec/pkg-descr
security/crowdsec/src/etc/inc/plugins.inc.d/crowdsec.inc
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/ServiceController.php
security/crowdsec/src/opnsense/mvc/app/models/OPNsense/CrowdSec/General.xml

Fixes https://github.com/opnsense/plugins/issues/3115

security/crowdsec 1.0.1: fixed live logs

---

net/freeradius/src/opnsense/service/conf/actions.d/actions_freeradius.conf

Added description to Cron action so can be set a Cron Job to Start and Stop FreeRADIUS.

 net/reeradius: Cron for Start and Stop

---

www/nginx/Makefile
www/nginx/pkg-descr
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/settings.xml
www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf

Hi!
For discussion. possibly closes https://github.com/opnsense/plugins/issues/2876
Thanks!

www/nginx: autoblock TTL

---

security/maltrail/Makefile
security/maltrail/pkg-descr
security/maltrail/src/opnsense/mvc/app/controllers/OPNsense/Maltrail/forms/general.xml
security/maltrail/src/opnsense/mvc/app/models/OPNsense/Maltrail/General.xml
security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf

add hostheader checking
https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L118-L119

security/maltrail: add hostheader checking

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/ServiceController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAcl.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMapfile.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalPeers.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/rc.conf.d

net/haproxy: release 3.12

---

net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalStats.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: add support for Prometheus exporter

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
www/nginx/src/opnsense/service/templates/OPNsense/Nginx/nginx.conf

Fixes https://forum.opnsense.org/index.php?topic=17637.0
See more details in linked issue https://github.com/opnsense/plugins/issues/3172

Allow dynamic proxy_ssl_name. Fixes #3172

---

dns/bind/Makefile
dns/bind/pkg-descr

Please for the next release only in devel (after patch day)

dns/bind: update base to 9.18

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/main.css

some color fixes for .bootstrap-tagsinput; .table-custom-categories;router-view;.btn-info

Vicuna - Cicada color fixes

---

security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/Menu/Menu.xml

Hi!
so sorry, somehow missed this
violates the standard menu name
thanks!

security/clamav: typo

---

net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt

- related #3198
As discussed in issue this change will not word-wrap anymore long lines when editing map-files

add css for textarea mapfile.content

---

dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindSlaveDomain.xml

Fixes a regression caused by commit 2fceec58

Restore TSIG key name entry to secondary zones

---

dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Record.xml

dns/bind: add RP record type

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogCpu.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFcgi.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMapfile.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalSettings.xml
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M4_0_0.php
net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

requires https://github.com/opnsense/tools/pull/332
fixes https://github.com/opnsense/plugins/issues/3026

net/haproxy: release 4.0 [only for 23.1]

---

sysutils/puppet-agent/Makefile
sysutils/puppet-agent/pkg-descr
sysutils/puppet-agent/src/opnsense/mvc/app/controllers/OPNsense/PuppetAgent/forms/general.xml
sysutils/puppet-agent/src/opnsense/mvc/app/models/OPNsense/PuppetAgent/PuppetAgent.xml
sysutils/puppet-agent/src/opnsense/service/templates/OPNsense/PuppetAgent/puppetagent.conf

This provides some minor improvements for the Puppet Agent plugin...
* add new options runinterval and runtimeout
* add new option usecacheonfailure
* add default values for Puppet Server + Environment
* don't wipe puppet.conf if service is disabled
@jan-win1993, please review :)

sysutils/puppet-agent: release version 1.1

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css

Cicada little small fix

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsJd.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Add new API for ACME dns challenge type:
* JD Cloud

security/acme: Add JD Cloud API dns challenge type, closes #3315

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/dns-overview.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/dns-overview.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/dns-overview.css

missing .query-error color for all themes and some other fixes for perfection ;-)

all Themes color fixes for unbound reporting

---

misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/dns-overview.css

@AdSchellevis 
I reversed the version number. 
Only the missing "a" on rgba

missed the "a" on rgba

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-tukan/Makefile
misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/main.css

delete wrong margin in .modal-side class for Zenarmor

Themes/Zenarmor plugin - view modal fix

---

www/nginx/src/opnsense/scripts/nginx/setup.php

Hi
Handle possible remaining vts socket  after nginx start failure
ref. https://github.com/opnsense/plugins/pull/3374

www/nginx: handle vts socket state

---

www/nginx/pkg-descr

Hi!
@fichtner sorry, can we have time to update the changelog before 23.1.6 release (since #3387 postponed and this changes in 1.32 already)?
Thanks!

www/nginx: update Changelog

---

security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpClient.php

After an update of my containers, I recently had an issue that SFTP upload stopped working since `ls -la` returned a non-numeric character for the links count:
````
-rw-------    ? user      group             0 Apr 20 11:57 sftp-upload-EdXe2l
````
This PR updates the regex pattern used for parsing directory listings and this fixes cases where `ls -la` returns `?` instead of the expected value. 
The pattern includes all types and perms specified in GNU ls and is less strict in what it matches so that it might fix other possible issues too.

security/acme-client: Use a more general ls parser in SFTP upload

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsDnsservices.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Add new API for ACME dns challenge type: DNS.Services
refs #3399

security/acme-client: Add DNS.Services API for dns challenge type

---

security/crowdsec/Makefile
security/crowdsec/pkg-descr
security/crowdsec/src/opnsense/mvc/app/models/OPNsense/CrowdSec/General.xml
security/crowdsec/src/opnsense/mvc/app/views/OPNsense/CrowdSec/general.volt

https://github.com/opnsense/plugins/issues/3440

crowdsec: update 1.0.5 - fix ban example

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeTruenas.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

security/acme: support TrueNAS Core Server deployhook, closes #3421

---

net/frr/Makefile
net/frr/pkg-descr
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf

net/frr: Add checkbox for bgp neighbor changes

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeProxmoxve.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

security/acme: support for Proxmox VE deployhook, closes #3422

---

net/wol/src/www/widgets/widgets/wake_on_lan.widget.php

Change the link to the current [DHCP Leases Status] page

Update DHCP Leases Status link in wake_on_lan.widget.php

---

vendor/sunnyvalley/src/etc/pkg/repos/SunnyValley.conf.in

The repo hostname has been updated to the product name.

update repository hostname

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/dns-overview.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Update to correct Reporting on Unbound DNS

Reporting Unbound DNS Fix

---

security/intrusion-detection-content-et-open/Makefile
security/intrusion-detection-content-et-open/pkg-descr
security/intrusion-detection-content-et-open/src/opnsense/scripts/suricata/metadata/rules/et-open-extra.xml

Same as PR #3643 with current open-extra plugin
You can pick the one you prefer

Full ET open ruleset as open-extra

---

security/crowdsec/src/opnsense/mvc/app/views/OPNsense/CrowdSec/general.volt

Update security/crowdsec: fix typo

---

sysutils/dec-hw/+POST_INSTALL
sysutils/dec-hw/Makefile
sysutils/dec-hw/pkg-descr
sysutils/dec-hw/src/etc/rc.syshook.d/early/30-powerstat
sysutils/dec-hw/src/opnsense/mvc/app/controllers/OPNsense/dechw/Api/InfoController.php
sysutils/dec-hw/src/opnsense/scripts/dec-hw/powerstat
sysutils/dec-hw/src/opnsense/service/conf/actions.d/actions_dechw.conf
sysutils/dec-hw/src/www/widgets/include/dechw.inc
sysutils/dec-hw/src/www/widgets/widgets/dechw.widget.php

- API endpoint to query the current power supply status
- small dashboard widget
If a better name for this plugins springs to mind, feel free to share :)

dec-hw: dual power supply status for Deciso appliances

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsDnsexit.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

security/acme-client: Add support for DNSExit

---

dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf

dns/ddclient: Add Porkbun ddns support

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php

security/acme-client: small refactoring and bugfix for #3745

---

security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsAurora.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsConoha.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsConstellix.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsExoscale.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsInternetbs.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsPointhq.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsRackspace.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsRage4.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_0_0.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_1_0.php
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh

security/acme-client: release 4.0 [only for 24.1]

---

security/tor/Makefile
security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/forms/relay.xml
security/tor/src/opnsense/mvc/app/models/OPNsense/Tor/Relay.xml
security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc

This is intended to fix #1204.  I wanted it and the syntax looked fairly straightforward, so I took a stab at it.

[os-tor] MyFamily

---

net/ntopng/Makefile
net/ntopng/pkg-descr
net/ntopng/src/opnsense/mvc/app/controllers/OPNsense/Ntopng/forms/general.xml
net/ntopng/src/opnsense/mvc/app/models/OPNsense/Ntopng/General.xml
net/ntopng/src/opnsense/service/templates/OPNsense/Ntopng/ntopng.conf

Closes #3260 
Long standing with just a couple of lines :)

net/ntopng: Allow interface selection

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 4.3

---

www/web-proxy-sso/src/opnsense/mvc/app/models/OPNsense/ProxySSO/Menu/Menu.xml

With the move of squid from core to plugins, the menu was also changed.

ProxySSO - Fix path in menu

---

dns/dnscrypt-proxy/Makefile
dns/dnscrypt-proxy/pkg-descr
dns/dnscrypt-proxy/src/opnsense/service/templates/OPNsense/Dnscryptproxy/dnscrypt-proxy.toml

dns/dnscrypt-proxy: make plugin compatible with 2.1

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/assets/stylesheets/main.scss
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

ACME Command Button fix and some other little fixes

ACME Command Button fix

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_0_0.php

security/acme-client: release 4.2

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsOci.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Reference to [3898](https://github.com/opnsense/plugins/issues/3898), this has been tested as working on my local installation.
Please do let me know if anything needs changing 😸

security/acme-client: add support for Oracle Cloud Infrastructure DNS API

---

README.md
net/udpbroadcastrelay/Makefile
net/udpbroadcastrelay/pkg-descr

net/udpbroadcastrelay: fix typo

Update net/udpbroadcastrelay: fix typo

---

net-mgmt/telegraf/Makefile
net-mgmt/telegraf/pkg-descr
net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf

Add OpenTelemetry output
Closes #3772

net-mgmt/telegraf

---

www/caddy/Makefile
www/caddy/pkg-descr

Changelog for: https://github.com/opnsense/plugins/issues/3935

www/caddy: v1.5.5 changelog

---

www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml

typo Nginx.xml

---

net/shadowsocks/Makefile
net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/forms/general.xml
net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/General.xml
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/shadowsocks.conf
net/shadowsocks/src/opnsense/service/templates/OPNsense/Shadowsocks/ss_local.conf

Ability of Shadowsocks plugin to work with udp ("mode": "tcp_and_udp").
resolves #3888

Shadowsocks plugin tcp_and_udp mode

---

www/caddy/pkg-descr

Updated caddy changelog with recent changes for v1.5.5

www/caddy: Updated changelog with recent changes for v1.5.5

---

www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt

Added lang() function for all user exposed text for translation, I hope I was thorough enough with it.
Of course there is still some text that won't be translated, like some error messages that are returned from the backend (for example the Caddyfile validation messages, they're always english.)

www/caddy: Added lang() function for all user exposed text for translation

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dnsprovider.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Add configuration options for DNS Providers: Netcup and RFC2136

www/caddy: DNS Provider add netcup and RFC2136

---

www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php

Fixes: https://github.com/opnsense/plugins/issues/4006
* Fix crash of searchAction when reverseUuids is null
* Additionally improve performance by using associative arrays and isset() instead of in_array().

www/caddy: Fix crash of searchAction when reverseUuids is null

---

net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr

This should correct issue #4018.

Look at the proper config element when enabling staticd

---

net-mgmt/net-snmp/src/etc/inc/plugins.inc.d/netsnmp.inc

some people seem to like xmlrpc syncs which can also be used for partial restores

net-mgmt/net-snmp - add xmlrpxc section

---

net-mgmt/nrpe/src/etc/inc/plugins.inc.d/nrpe.inc

some people seem to like xmlrpc syncs which can also be used for partial restores

net-mgmt/nrpe - add xmlrpxc section 

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/dashboard.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/dns-overview.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/dashboard.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/dns-overview.css
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/dashboard.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/dns-overview.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/dashboard.css
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/dns-overview.css
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/main.css

vicuna and cicada new colors redesign

Themes update for 24.7

---

net-mgmt/zabbix-agent/Makefile
net-mgmt/zabbix-agent/pkg-descr
net-mgmt/zabbix-proxy/Makefile
net-mgmt/zabbix-proxy/pkg-descr

Sorry for using one PR for both

net-mgmt/zabbix-* 7 variant

---

www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/issues/4074

www/caddy: Add option to disable TLS in domain

---

www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js
www/caddy/src/opnsense/www/js/widgets/CaddyDomain.js

Reference: https://github.com/opnsense/core/commit/4b0a24c25fd22f80881c3231b94e9715368a88f4

www/caddy: Change this.ajaxGet to this.ajaxCall in widgets

---

dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf

Same fix as https://github.com/opnsense/plugins/pull/4048 but for allow-recursion

Fix handling of multiple ACLs in allow-recursion

---

security/intrusion-detection-content-snort-vrt/src/opnsense/scripts/suricata/metadata/rules/snort-vrt.xml

There is a more recent Snort VRT Ruleset Snapshot, this should allow the collection of it
It appears there are no Snort Issues or PRs being tracked
This is my first PR for OPNSense, and probably my 2nd or 3rd PR in Github ever, please help me improve this if necessary

using latest Snort V2 VRT Snapshot available

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/AccountsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomationFactory.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsGcloud.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNsupdate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsTransip.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/HttpOpnsense.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/TlsalpnAcme.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidationFactory.php
security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/logs.volt

security/acme-client: release 4.5

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/bootstrap-select.css

minor changes and additions to fix display issues

theme rebellion fixes for 24.7 new  lobby dashboard

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/bootstrap-select.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/dashboard.css

Missing dashboard.css and minor changes to bootstrap-select. Let me know of any issues whilst I have time!

Rebellion update- added dashboard.css and minor changes for color

---

dns/ddclient/src/opnsense/www/js/widgets/Dyndns.js
dns/ddclient/src/opnsense/www/js/widgets/Metadata/Dyndns.xml

Fixes: https://github.com/opnsense/plugins/issues/4142

dns/ddclient: Add Dyndns widget for new dashboard

---

dns/ddclient/src/opnsense/www/js/widgets/Dyndns.js
security/etpro-telemetry/src/opnsense/www/js/widgets/ETProTelemetry.js
sysutils/dec-hw/src/opnsense/www/js/widgets/DecHW.js
www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js
www/caddy/src/opnsense/www/js/widgets/CaddyDomain.js

Ref: https://github.com/opnsense/core/commit/36560aa67933631eca5bf62a9af985b0809abfbc
Fixes: https://github.com/opnsense/plugins/issues/4154

dashboard: Implement cache safe imports of base classes

---

www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php

Hi!
closes https://github.com/opnsense/plugins/issues/4113
thanks!

www/nginx: LogsController quick fix

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dnsprovider.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/issues/4161

www/caddy: Add Disable Propagation Timeout in DNS Provider Tab.

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/dashboard.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/dashboard.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/dashboard.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/dashboard.css

get rid of unnecessary hover effects on dashboard for both dark themes

Themes Cicada/Vicuna  - dashboard fix for hover effects

---

dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Record.xml

dns/bind: add SSHFP Record Type

---

sysutils/smart/src/opnsense/www/js/widgets/Metadata/Smart.xml
sysutils/smart/src/opnsense/www/js/widgets/Smart.js

I have no idea what I am doing, please review the widget and merge if acceptable.

Create Smart widget XML

---

www/caddy/Makefile
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

PR: https://forum.opnsense.org/index.php?topic=42816
Yay I made a typo.
Reference... where I fixed it but I forgot a spot...: https://github.com/opnsense/plugins/pull/4211/commits/e8907cff3a04a1e3075d078c21e9d0ca3e1a3e58

www/caddy: Fix typo in "TlsInsecureSkipVerify" condition

---

sysutils/smart/src/opnsense/www/js/widgets/Smart.js

Updated the code to use the detailed API instead of the info call.

Update Smart.js to use detailed API

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh

security/acme-client: release 4.6

---

www/caddy/pkg-descr

Update release notes for:
https://github.com/opnsense/ports/pull/202
https://github.com/opnsense/tools/pull/436

www/caddy: Update layer4 module

---

dns/ddclient/src/opnsense/scripts/ddclient/lib/account/digitalocean.py

Add DigitalOcean support to OPNsense native ddclient

dns/ddclient: Add DigitalOcean support

---

security/clamav/Makefile
security/clamav/src/opnsense/service/conf/actions.d/actions_clamav.conf

No idea when they were renamed but this is the correct path
Closes #3893

security/clamav: adjust new rc filenames

---

www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/issues/4329

www/caddy: Fix access on both wildcard and subdomain causing error

---

sysutils/git-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Git.php

chore: Fix typo

---

security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsFornex.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml

Api challenge type for fornex dns 
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_fornex.sh

security/acme-client: Add fornex API dns challenge type

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeSynologyDsm.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsInwx.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M4_2_0.php
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/run_remote_ssh.php
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php

security/acme-client: release 4.7

---

net/haproxy/Makefile
net/haproxy/pkg-descr
net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf

net/haproxy: release 4.4

---

security/tailscale/Makefile
security/tailscale/pkg-descr
security/tailscale/src/opnsense/mvc/app/models/OPNsense/Tailscale/ACL/ACL.xml
security/tailscale/src/opnsense/mvc/app/models/OPNsense/Tailscale/Settings.xml
security/tailscale/src/opnsense/mvc/app/views/OPNsense/Tailscale/status.volt
security/tailscale/src/opnsense/www/js/widgets/Metadata/Tailscale.xml
security/tailscale/src/opnsense/www/js/widgets/Tailscale.js

Adds Tailscale widget to dashboard.
Allow IPv6 advertised subnets, closes #4412
Show online status for peers in status page

security/tailscale dashboard widget, ipv6 advertised routes

---

www/squid/src/etc/inc/plugins.inc.d/squid.inc
www/squid/src/opnsense/service/templates/OPNsense/Syslog/local/squid_access.conf

This pull-request changes the facility from squid-1 to squid and extends the syslog-filter to support multiple squid-processes.
Required for https://github.com/opnsense/plugins/pull/4393#issuecomment-2552996753

www/squid: Squid syslog corrections

---

www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt

A few low impact frontend changes that improve UX. Docs do not need updates.

www/caddy: Some small UX tweaks

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/etc/inc/plugins.inc.d/caddy.inc
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Menu/Menu.xml

Fix: https://github.com/opnsense/plugins/issues/4426
Add changelog for next version.

www/caddy: Refactor caddy.inc and add syslog function

---

www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Layer4Controller.php
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/ReverseProxyController.php
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHeader.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4Openvpn.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/layer4.volt
www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt

Based on this example:
https://github.com/opnsense/core/commit/0e91c2ec81127c4228250a1c583384db92cfc12f
Requires the following commits:
https://github.com/opnsense/core/commit/a7a99fcdfe972dacc1a6beada7607e73a1689d05
https://github.com/opnsense/core/commit/834c42fc1e68eef15fcb731e630cc245d09d57bc
https://github.com/opnsense/core/commit/084ac9489b54209d8952185e29d67b7bc4bb15be
cc @fichtner

www/caddy: Implement reusable grid template

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/dashboard.css
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/main.css

Grid colour changes to improve readability
Dashboard cosmetic colour change for line.

Grid and Dashboard colour change

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeAuthProvider

Fixes: https://github.com/opnsense/plugins/issues/4488

www/caddy: Add copy_headers selectpicker to Auth Provider tab. Authorization header added.

---

security/tailscale/Makefile
security/tailscale/pkg-descr
security/tailscale/src/opnsense/mvc/app/controllers/OPNsense/Tailscale/forms/settings.xml
security/tailscale/src/opnsense/mvc/app/models/OPNsense/Tailscale/Settings.xml
security/tailscale/src/opnsense/service/templates/OPNsense/Tailscale/rc.conf.d
security/tailscale/src/opnsense/www/js/widgets/Tailscale.js

Add advanced option to allow SSH connections from devices in tailnet (requested feature):
https://tailscale.com/kb/1193/tailscale-ssh
Also added the "Disable SNAT" option under advanced which  adds the following to 
tailscaled_env="TS_DEBUG_NETSTACK_SUBNETS=0" the rc config file.
see:
https://github.com/tailscale/tailscale/issues/5573#issuecomment-1847863952

security/tailscale Add option to allow tailscale to manage ssh connections

---

www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt

Fixes: https://github.com/opnsense/plugins/issues/4509

www/caddy: Fix shortcut buttons

---

security/crowdsec/Makefile
security/crowdsec/pkg-descr
security/crowdsec/src/etc/inc/plugins.inc.d/crowdsec.inc
security/crowdsec/src/opnsense/mvc/app/models/OPNsense/CrowdSec/General.xml

Fix for https://github.com/opnsense/plugins/issues/4511

Update crowdsec rule reference ($ -> <>); bump release

---

net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BfdController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/BgpController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Ospf6Controller.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/OspfController.php
net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/StaticController.php
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bfd.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/general.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/rip.volt
net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/static.volt

Requires: https://github.com/opnsense/core/issues/8284

net/frr: Integrate layout_partials/base_apply_button

---

net/frr/pkg-descr
net/frr/src/opnsense/scripts/frr/setup.sh

This cleans up remains after the frr.conf migration.
Fixes: https://github.com/opnsense/plugins/issues/4551

net/frr: Delete per daemon and old watchfrr files

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

... Cleanup tls_configuration macro definition, bump version and add changelog
Fixes: https://github.com/opnsense/plugins/issues/4544

www/caddy: add propagation_timeout and propagation_delay

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/issues/4089
Fixes: https://forum.opnsense.org/index.php?topic=43853.0
Has been requested a few times.

www/caddy: Add client auth mtls to domains

---

misc/theme-cicada/Makefile
misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
misc/theme-vicuna/Makefile
misc/theme-vicuna/src/opnsense/www/themes/vicuna/assets/stylesheets/main.scss
misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/main.css

1. a view color modifications
2. h1 set to 21px instead of 22px

Cicada/Vicuna Theme color modification

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/issues/4619

www/caddy: Add basic_auth support to handlers

---

misc/theme-rebellion/Makefile
misc/theme-rebellion/src/opnsense/www/themes/rebellion/build/css/jquery.bootgrid.css

Corrections to bootgrid search query layout and colour.

Bootgrid Corrections

---

security/wazuh-agent/src/opnsense/mvc/app/controllers/OPNsense/WazuhAgent/forms/settings.xml
security/wazuh-agent/src/opnsense/mvc/app/models/OPNsense/WazuhAgent/WazuhAgent.xml
security/wazuh-agent/src/opnsense/service/templates/OPNsense/WazuhAgent/ossec.conf

This commit makes the agent_name for enrollment configurable.

security/wazuh-agent: make agent_name configurable

---

security/clamav/Makefile
security/clamav/src/opnsense/service/conf/actions.d/actions_clamav.conf

In an environment with above 500 users and ssl decryption clamav is quite memory hungry ..

security/clamav: Add Restart command to cron

---

www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/pull/4721
An oversight during reviewing the pull request.

www/caddy: Fix active health check in template

---

security/crowdsec/+POST_DEINSTALL.post
security/crowdsec/Makefile
security/crowdsec/pkg-descr
security/crowdsec/src/etc/inc/plugins.inc.d/crowdsec.inc
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/AlertsController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/BouncersController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/DecisionsController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/HubController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/MachinesController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/ServiceController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/Api/VersionController.php
security/crowdsec/src/opnsense/mvc/app/controllers/OPNsense/CrowdSec/forms/general.xml
security/crowdsec/src/opnsense/mvc/app/models/OPNsense/CrowdSec/General.xml
security/crowdsec/src/opnsense/mvc/app/views/OPNsense/CrowdSec/general.volt
security/crowdsec/src/opnsense/mvc/app/views/OPNsense/CrowdSec/overview.volt
security/crowdsec/src/opnsense/scripts/OPNsense/CrowdSec/hub-upgrade.sh
security/crowdsec/src/opnsense/scripts/OPNsense/CrowdSec/reconfigure.py
security/crowdsec/src/opnsense/www/js/CrowdSec/crowdsec.js

- added rules for egress traffic
- option to skip rule creation
- enroll to the online console/dashboard by adding an enrollment key in the settings
- renamed alias tables (..blacklist.. -> ..blocklist..)
- general code cleanup

crowdsec: 1.0.10

---

dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml

Add Akamai to option values.
This PR adds a file change originally missed in #4660.

dns/ddclient: Add Akamai to option values.

---

net/frr/Makefile
net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr

Closes: https://github.com/opnsense/plugins/issues/4716

net/frr: Upgrade from frr8 to frr10

---

www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Layer4Controller.php
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/ReverseProxyController.php
www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt

Follow up to: https://github.com/opnsense/plugins/commit/4b4ec29ecaf161cc426dfebb72f5ec658bbd6658
This fix is better code quality.

www/caddy: Fix snake_case usage in controller

---

www/caddy/Makefile
www/caddy/pkg-descr
www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile

Fixes: https://github.com/opnsense/plugins/issues/4700

www/caddy: Add global servers timeouts options

---

security/acme-client/Makefile
security/acme-client/pkg-descr
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsWebsupport.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Process.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SSHKeys.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpClient.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpUploader.php
security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Utils.php
security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/run_remote_ssh.php
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php

see plugin changelog for further information

security/acme-client: release 4.10

---

sysutils/puppet-agent/Makefile
sysutils/puppet-agent/pkg-descr
sysutils/puppet-agent/src/opnsense/mvc/app/views/OPNsense/PuppetAgent/index.volt

sysutils/puppet-agent: switch to Puppet 8

---

devel/grid_example/src/opnsense/mvc/app/controllers/OPNsense/GridExample/Api/ServiceController.php
devel/grid_example/src/opnsense/mvc/app/controllers/OPNsense/GridExample/Api/SettingsController.php
devel/grid_example/src/opnsense/mvc/app/controllers/OPNsense/GridExample/forms/dialogAddress.xml
devel/grid_example/src/opnsense/mvc/app/models/OPNsense/GridExample/GridExample.xml
devel/grid_example/src/opnsense/mvc/app/views/OPNsense/GridExample/index.volt

For documentation purposes: https://github.com/opnsense/docs/issues/659

devel/grid_example: Implement base_bootgrid_table and base_apply_button

---

net/netbird/src/opnsense/mvc/app/controllers/OPNsense/Netbird/Api/ServiceController.php
net/netbird/src/opnsense/mvc/app/views/OPNsense/Netbird/constatus.volt

Small fix to reflect the changes in the field name on the Netbird side. Routes are now called networks.

Netbird fixes

---

security/netbird/src/opnsense/mvc/app/controllers/OPNsense/Netbird/forms/settings.xml

File still had "PFsense" from original plugin source

security/netbird Fix typo in settings.xml
