opnsense/plugins

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This allows to specify the source address which HAProxy will use when connecting to servers. And it fixes a small text bug in `haproxy.conf`.
> net/haproxy new feature "source address"

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- remove default value for `server.checkport` (setting a default value would silently enable this advanced feature everywhere)
- add "checkport" option to health checks (so that health checks can be used as a template to set it for every server)
- disable health check if type is missing (it can't be empty in the current release, but now this old check actually does what it was intended for)
- fix template comment that broke in 991b85651500c9a69f6975027ffb175c1def5395
@manusfreedom: FYI, now you can configure the "checkport" in health checks instead of setting it for every single server.
> net/haproxy: enhance "checkport" option & more fixes

- net/haproxy/src/etc/inc/plugins.inc.d/haproxy.inc
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
* fixes #18  
* changes "chroot" to "enabled", now it's safe to do so; it will only affect new installations, on old installations it will remain "disabled"
> net/haproxy: syslog & security enhancements

- net/haproxy/src/etc/inc/plugins.inc.d/haproxy.inc
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/setup.sh
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
* remove chroot GUI option, because there's no point in running HAProxy in insecure mode anymore (see 5a7459707fd2e5eb703b32fd4715b1818f9ca49e)
* change chroot directory to `/var/haproxy`
> net/haproxy: chroot fixes

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
From the HAProxy documentation:
> Some parameters involve values representing time, such as timeouts. These
> values are generally expressed in milliseconds (unless explicitly stated
> otherwise) but may be expressed in any other unit by suffixing the unit to the
> numeric value.
This obviously improves readability of these values and supports lower and higher values. Previously some values were limited to a value between 100-1000000ms, which was an unnecessary limitation.
> net/haproxy: add support for time format

- net/ftp-proxy/src/etc/rc.d/os-ftp-proxy
The os-ftp-proxy rc.d script returned wrong status. Therefore, the background color of the proxy list was always green.
> fix wrong return code from rc.d script

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This introduces a new frontend parameter: "Default certificate". The only purpose is to enforce a certain sort order for certificates. This makes it possible to choose the "default" certificate which will be used by HAProxy if no SNI is provided by the client or if the client provides an SNI hostname which does not match any certificate.
Previously this was possibly too by adding the certificates to the "Certificates" parameter in the required order, but this turned out to be a hassle and not user-friendly. The new parameter is an advanced parameter and thus hidden to most users as only a few will ever make use of it.
Side note: While it would be possible to just add the "default certificate" as the first certificate to the "bind" option (which is OK for HAProxy, it can handle multiple …
> net/haproxy: add "default certificate" parameter, fixes #51

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Several use-cases for advanced options, because some options may not be used in `default-server` context; I think this will help to solve #51 in particular.
> net/haproxy: add support for advanced server options

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This adds the following new configuration options:
* Default Parameters:  Check Timeout (HAProxy's `timeout check`)
* Backends:  Check Timeout (HAProxy's `timeout check`)
* Servers: Down Interval (HAProxy's `downinter`)
Tested on OPNsense 16.7.11 with HAProxy 1.6.10.
> net/haproxy: make more timeout values configurable

- net/haproxy/Makefile
- net/haproxy/src/etc/inc/plugins.inc.d/haproxy.inc
Thanks to the friendly reminder in opnsense/core/issues/1224 this finally enables XMLRPC sync for HAProxy configuration.
> net/haproxy: enable xmlrpc sync

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This patch add support for custom TCP health checks. It may be used to check for a proper response from SMTP and IMAP servers (or any other TCP service).
Below is an example for a simple SMTP health check:
Which will result in the following HAProxy configuration:
```
option tcp-check
tcp-check connect
tcp-check expect string "220 mail.example.com ESMTP"
```
Currently this is limited to only _one_ send/expect step.
While here, this fixes a help text in HTTP health check options.
> net/haproxy: add support for custom TCP health checks

- net/haproxy/Makefile
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
I've just discovered today that we're using the wrong HAProxy directive in our ACL option "Host matches". According to the HAProxy manual:
```
ACL derivatives :
hdr_dir([<name>[,<occ>]]) : subdir match
hdr_sub([<name>[,<occ>]]) : substring match
- "dir"   : subdir match : check that a slash-delimited portion of the
contents exactly matches one of the provided string patterns.
This may be used with binary or string samples.
- "sub"   : substring match : check that the contents contain at least one of
the provided string patterns. This may be used with binary or
string samples.
```
This patch replaces the wrong `hdr_dir` directive with the more appropiate `hdr_sub` directive. This may be a breaking change for some users, because it's unlikely that `hdr_dir` did what users were expecting. …
> net/haproxy: fix ACL option for "Host matches"

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.php
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- Overhaul model to support configuration injection (used by our Let's Encrypt plugin)
- Allow to use proper time format for more fields (downinter, inter)
- Fix search fields
- Relax mask for description fields
- Enhance isEnabled() to be more accurate
- Improve some validation messages
- Various fixes for the template
> net/haproxy: feature & bugfix release

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/ActionsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/AccountsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ActionsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Menu/Menu.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/lighttpd-acme-challenge.conf
- Full integration with our HAProxy plugin (automatically injects configuration)
- Support for restart actions (pre-defined, configd commands and custom commands)
- Fix for #70: relax field validations for many input fields (name, description, altNames)
- Fix search fields
- Fix forceful re-issue of certificates (required if altNames was changed)
- Fix DNS-01 ISPconfig option (should be a checkbox)
- Respect if an item is disabled
- Do not expose lighttpd version
- Improve some help messages
**And don't forget to click the "Apply" button... :-)**
**Be sure to select your HAProxy frontends:**
Now select the "validation method" and "restart action" for your certificate:
> security/acme-client: feature & bugfix release

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- Show acme status for each certificate in GUI
- Avoid API exception by skipping HAProxy integration if validation method is not configured
- Don't log an error if no restart action was specified
- Rename field "CA Account" to "LE Account" to avoid confusion
> security/acme-client: bugfix release

- net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf
This can happen if you copy a configuration file for configd...
> fix strings in quagga

- net/haproxy/Makefile
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
In light of #84 it became clear that the HAProxy plugin is lacking with this regard too.
- none
- fix CA/intermediate certificate handling if a certificate (chain) was (properly) imported into OPNsense
> net/haproxy: bugfix release 1.13

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/validations.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
- GUI: hide HTTP-01 validation methods when not selected (similar to DNS-01)
- GUI: hide parameters for restart actions when not selected
- Advanced: make the timeout for (custom) restart commands configurable
- properly import CA certificates (closes #84)
- do not make keys world-readable
- remove DNS-01 and HTTP-01 prefixes from validation names (they are obsolete now)
- avoid log message on missing restart action (fixes df2a727)
NOTE: Deleting an imported Let's Encrypt **CA** will automatically delete _all_ LE certificates that are referenced.
For reference: A Let's Encrypt CA will _only_ be imported on issue or renewal of a LE certificate. It may be required to forcefully renew an existing certificate to allow the CA to be imported.
> security/acme-client: bugfix release 1.3

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
This renames the option field "Validation Method" to "Challenge Type" to better comply with official Let's Encrypt wording.
The menu item "Validation Method" remains unchanged, because IMHO it defines a configured (unique) method to handle the selected challenge type.
> security/acme-client: adopt official LE wording

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- support new `ssl_fc` option in ACLs to reliably test for SSL/TLS connections
- fix missing newline in exported certificate ([via forum post](https://forum.opnsense.org/index.php?topic=4947.0))
> net/haproxy: bugfix release 1.14

- net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
- net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ripd.conf
@fichtner this must go to the stable branch before release. It will map OPNsense names to real interface names like Quagga expects. Otherwise interfaces and passive interfaces will not work (core functionality will do).
> Quagga: use correct interfaces

- net/ftp-proxy/src/opnsense/mvc/app/views/OPNsense/FtpProxy/index.volt
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
- net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
- net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/accounts.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/settings.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/validations.volt
- security/tinc/src/opnsense/mvc/app/views/OPNsense/Tinc/index.volt
* quagga
* haproxy
* ftp-proxy
* acme-client
* tinc
Feedback from plugin maintainers is welcome.
> Translation: Fix some plugins

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
Fix null object when a validation method use a removed HA Proxy frontend
> [AcmeClient] Fix non-object error

- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPASPath.xml
- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPRouteMaps.xml
- net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
- net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Hi,
this PR is for adding as-path ACLs via route-maps to the neighbors.
Example config after adding all:
```
router bgp 65001
network 192.168.0.0/24
neighbor 1.1.1.1 remote-as 65333
neighbor 1.1.1.1 update-source em0
neighbor 1.1.1.1 route-map TESTMAP in
neighbor 1.1.1.1 route-map RR out
neighbor 1.1.1.2 remote-as 65334
neighbor 1.1.1.2 update-source em0
neighbor 1.1.1.2 route-map TESTMAP out
!
ip as-path access-list 1 permit _4500$
ip as-path access-list 1 permit 4444
ip as-path access-list 2 permit .$
ip as-path access-list 3 deny 3456
ip as-path access-list 4 permit 23
ip as-path access-list 6 permit 444
!
route-map RR permit 10
match as-path 1
set local-preference 300
route-map RR permit 20
match as-path 2
set community 4444:33
route-map TESTMAP permit 10
set local-preference 320
``` …
> Quagga: Add AS-Path Lists and Route-Maps to BGP

- sysutils/monit/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
- sysutils/monit/src/opnsense/scripts/OPNsense/Monit/post-install.php
Fix issues from #145 
- import sender address from system notification settings on install
- change regular expression for validation to allow display-name syntax from RFC 5322
> Monit: import sender address and fix validation regexp

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/statistics.volt
The (nonfunctional) sub tabs are now hidden if the HAProxy service is not running (or to be more precise: if stats cannot be retrieved).
closes #154
> net/haproxy: hide statistics tabs if service is not enabled

- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/DiagnosticsController.php
- net/quagga/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsgeneral.volt
- net/quagga/src/opnsense/service/conf/actions.d/actions_quagga.conf
New tab in Diagnostics - General, Displaying the running configuration as plain text. 
This might be easier for CLI guys migrating to UI / OPN
E.g. me or OutBackDingo are plain CLI guys and it would be nice to see what changes in UI do to the running-config.
> Quagga: New tab in general diagnostics 

- sysutils/monit/Makefile
- sysutils/monit/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
- sysutils/monit/src/opnsense/scripts/OPNsense/Monit/post-install.php
When synchronizing the config the hostname of the MASTER is set for the System check on the BACKUP node. Using the variable $HOST will set the correct hostname on the BACKUP node.
> sysutils/monit: set variable $HOST as system name for proper sync to cluster nodes

- sysutils/monit/Makefile
- sysutils/monit/src/opnsense/mvc/app/controllers/OPNsense/Monit/forms/general.xml
- sysutils/monit/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
- sysutils/monit/src/opnsense/scripts/OPNsense/Monit/post-install.php
To add multiple mail server as described in [Setting-a-mail-server-for-alert-delivery](https://mmonit.com/monit/documentation/monit.html#Setting-a-mail-server-for-alert-delivery) the mailserver type was changed to CSVListField.
This pull request is a fix for #181
> sysutils/monit: set mailserver type to CSVListField, fix validation

- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
The FreeBSD port `security/acme.sh` installs DNS API hook scripts in `/usr/local/share/examples/acme.sh`. This is a non-default location for acme.sh, thus we need to tell acme.sh where to find these scripts.
> security/acme-client: configure DNS API hook location for acme.sh

- net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml
Fixes yet another silly copy'n'paste error on my side. (#194)
Just a cosmetic fix, no version bump required.
> net-mgmt/zabbix-agent: fix validation mask for listenIP (again)

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
A user reported an issue with acme on IRC. After some debugging it turned out that a whitespace in the certificate name was causing this issue. This PR extends the validation mask to disallow several characters that are not valid in this context. We're not using an advanced regex here to make sure all IDN domains are still supported.
Besides that, the "Certificate Name" was changed to "Common Name" to improve clarity. It was misinterpreted as an arbitrary identifier by some users, but now it's clear that this name is part of the certificate.
Furthermore the altNames field size was increased from 16384 to 65536.
> security/acme-client: tighten validation masks, "Name" -> "Common Name"

- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Trying to add a altName after https://github.com/opnsense/plugins/pull/214/commits/ad715d00edffab5e0fdb8fece7003d6eb5ff7713 results in the following error:
`Error at /usr/local/opnsense/mvc/app/models/OPNsense/Base/BaseModel.php:370 - preg_match(): Compilation failed: number too big in {} quantifier at offset 35 (errno=2)`
Looks like we've hit a [limit in pcre](http://pcre.sourceforge.net/pcre.txt). I've lowered the maximum size to 65535.
> security/acme-client: fix 'Compilation failed: number too big'

- net/haproxy/src/etc/rc.syshook.d/50-haproxy.restart
- net/haproxy/src/etc/rc.syshook.d/50-haproxy.stop
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/rc-wrapper.sh
- net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/rc.conf.d
fixes #195
From the [official HAProxy documentation](https://www.haproxy.org/download/1.7/doc/management.txt):
> HAProxy supports a graceful and a hard stop. The hard stop is simple, when the
> SIGTERM signal is sent to the haproxy process, it immediately quits and all
> established connections are closed. The graceful stop is triggered when the
> SIGUSR1 signal is sent to the haproxy process. It consists in only unbinding
> from listening ports, but continue to process existing connections until they
> close. Once the last connection is closed, the process leaves.
> 
> The hard stop method is used for the "stop" or "restart" actions of the service
> management script. The graceful stop is used for the "reload" action which
> tries to seamlessly reload a new configuration in a new …
> net/haproxy: switch to using HAProxy's hard stop mode by default

- net/quagga/src/opnsense/scripts/quagga/quagga.rb
this is a bugfix for a disabled page, so there is no need for a new version bump
> bugfix in neighbors in quagga.rb

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
This prevents resetting of the cloudflare "proxy" status (if this host is proxied/protected by cloudflare) of the updated DNS record.
> Fix cloudflare proxy status reset on dyndns update

- net/zerotier/Makefile
- net/zerotier/src/etc/inc/plugins.inc.d/zerotier.inc
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/Api/ZerotierController.php
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/IndexController.php
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/forms/global.xml
- net/zerotier/src/opnsense/mvc/app/models/OPNsense/Zerotier/Zerotier.xml
- net/zerotier/src/opnsense/mvc/app/views/OPNsense/Zerotier/index.volt
- net/zerotier/src/opnsense/service/templates/OPNsense/zerotier/zerotier
https://github.com/opnsense/plugins/issues/247
This commit improves upon the way that Zerotier starts and stops and how
networks are added/removed and activated/deactivated. There is now a "Global"
tab on the Zerotier page that enables or disables the service which is
honoured between reboots. Additionally, the service needs to be active in
order for networks to be added and removed. If the service is not active, then
the tab "Networks" will be disabled and the user will not be able to
add/remove or activate/deactivate Zerotier networks.
This should fix the observed problems raised in the issue.
The "Global" tab will be extended later to include further information and
actions, especially when Zerotier API usage is developed.
-=david=-
> bugfix/247 Improve Zerotier Start/Stop Behaviour

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- allow to configure acme.sh's log level (advanced option)
- write import events to the system log (#256)
- update acme.sh to version 2.7.4
- fix log file display in GUI (https://github.com/opnsense/plugins/issues/69)
- switch default log level for acme.sh from 2 to 1
> security/acme-client: release 1.10

- www/c-icap/src/opnsense/mvc/app/models/OPNsense/CICAP/Antivirus.xml
No defaults for a required field and "N" instead of "0" for a BooleanField.
> C-icap: Fix defaults in the model

- www/c-icap/src/opnsense/mvc/app/controllers/OPNsense/CICAP/forms/general.xml
- www/c-icap/src/opnsense/mvc/app/models/OPNsense/CICAP/General.xml
- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/c-icap.conf
access.log is quite useless as it doesn't log any useful and detected viruses are sent to server.log.
Discussed in #268
> C-ICAP: Allow disabling access.log

- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/virus_scan.conf
> C-ICAP: fix typo for maxsize value

- security/tor/Makefile
- security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/ServiceController.php
- security/tor/src/opnsense/mvc/app/views/OPNsense/Tor/general.volt
@fichtner with this patch there will be a button for reloading the service.
This also fixes a bug: the old version sent the request to the wrong API endpoint which lead to a service restart - reconfigure in contrast renders the new template too. (restart is meant for service management).
> Tor: add a button to reload the service; code quality

- security/tor/src/opnsense/service/scripts/tor/get_hostnames
- security/tor/src/opnsense/service/scripts/tor/make_hidden_service_dirs.php
- security/tor/src/opnsense/service/scripts/tor/setup.sh
- security/tor/src/opnsense/service/scripts/tor/tor_helper.php
@fichtner I got a bug report in the forum:
https://forum.opnsense.org/index.php?topic=5995.0
This includes the fixes for this and another hidden service bug.
> Tor: fix permission issue

- net/quagga/Makefile
- net/quagga/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
- net/quagga/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/quagga/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
Please remove the source branch when merged.
This should fix https://forum.opnsense.org/index.php?topic=6054.0
> Add OSPF Router ID

- www/c-icap/src/opnsense/mvc/app/controllers/OPNsense/CICAP/forms/general.xml
- www/c-icap/src/opnsense/mvc/app/models/OPNsense/CICAP/General.xml
- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/c-icap.conf
In /var/log/c-icap/server.log is not displayed the user name
Wed Sep 13 10:52:41 2017, 79793/3542196480, VIRUS DETECTED: Eicar-Test-Signature , http client ip: 192.168.12.101, http user: -, http url: http://www.eicar.org/download/eicar.com
> Allow RemoteProxyUsers in c-icap

- net/zerotier/Makefile
- net/zerotier/src/etc/inc/plugins.inc.d/zerotier.inc
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/Api/NetworkController.php
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/Api/SettingsController.php
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/OverviewController.php
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/forms/dialogNetwork.xml
- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/forms/settings.xml
- net/zerotier/src/opnsense/mvc/app/models/OPNsense/Zerotier/Menu/Menu.xml
- net/zerotier/src/opnsense/mvc/app/models/OPNsense/Zerotier/Zerotier.xml
- net/zerotier/src/opnsense/mvc/app/views/OPNsense/Zerotier/index.volt
- net/zerotier/src/opnsense/mvc/app/views/OPNsense/Zerotier/overview.volt
- net/zerotier/src/opnsense/service/conf/actions.d/actions_zerotier.conf
This commit brings basic API functionality to the Zerotier plugin. It allows
the user to retrieve "Global" Zerotier information, peers that are talking
with this node and details on configured (and enabled) networks.
This version of the plugin provides a space for the Zerotier API key to be
input and saved, but it is not used for Basic API functionality. The
zerotier-cli client is used directly to query for global, peers and network
information.
If the API functionality is extended to allow for creating and modifying
Zerotier information from this plugin, then the API key will be required at
that point. It is introduced here for the sake of convenience for later down
the line.
Various other small changes include general code cleanups, renaming of some UI
facing labels and improved layout …
> net/zerotier: Add Basic API Functionality

- net/zerotier/src/opnsense/mvc/app/controllers/OPNsense/Zerotier/Api/SettingsController.php
- net/zerotier/src/opnsense/service/templates/OPNsense/zerotier/local.conf
There is potential for an invalid local.conf to be written out during first
save. Whilst it doesn't stop Zerotier from starting, it does cause it to
return a 1 as an error code, thus fooling configd that the service has failed
to start. Adding in a default '{}' resolves this issue.
-=david=-
> net/zerotier: Prevent invalid 'local.conf' on initial save.

- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
I only found this missing help text to make some confusions, with this it's ready for production.
The last dot is debateable, it's a sentence but doesn't belong to the link. 
You decide @fichtner
> net-mgmt/telegraf: fix helptext, ready for stable

- net/freeradius/Makefile
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap
Reported by Dominian via IRC
Default install loads EAP but false closing bracket when client eap authentication is disabled.
> net/freeradius: fix super stupid mistake

- net/postfix/Makefile
- net/postfix/pkg-descr
- net/postfix/src/etc/inc/plugins.inc.d/postfix.inc
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/Api/AntispamController.php
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/Api/DomainController.php
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/Api/GeneralController.php
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/Api/ServiceController.php
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/DomainController.php
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/GeneralController.php
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/antispam.xml
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/dialogEditPostfixDomain.xml
- net/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/ACL/ACL.xml
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Antispam.php
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Antispam.xml
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Domain.php
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Domain.xml
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.php
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- net/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Menu/Menu.xml
- net/postfix/src/opnsense/mvc/app/views/OPNsense/Postfix/domain.volt
- net/postfix/src/opnsense/mvc/app/views/OPNsense/Postfix/general.volt
- net/postfix/src/opnsense/scripts/OPNsense/Postfix/setup.sh
- net/postfix/src/opnsense/service/conf/actions.d/actions_postfix.conf
- net/postfix/src/opnsense/service/templates/OPNsense/Postfix/+TARGETS
- net/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
- net/postfix/src/opnsense/service/templates/OPNsense/Postfix/master.cf
- net/postfix/src/opnsense/service/templates/OPNsense/Postfix/postfix
- net/postfix/src/opnsense/service/templates/OPNsense/Postfix/transport
This has to stay in master for a while, perhaps a release with 18.1 would be nice. 
ATM it supports:
Postfix general features like mydomain etc.:
An rspamd integration with plugin warning:
- Domainrouting 
What you can expect within the next dev releases is full certificate und cipher management.
I want to push it now to master to better test the integration with rspamd plugin.
Please review! :)
> net/postfix: New plugin

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
In HAProxy "use_server" will only work for backends. Besides that, the specified server **must already be defined** for the backend. Otherwise HAProxy will refuse to start with the "unable to find server" error message.
http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#use-server
This patch rephrases the "use_server" option, add a note and improve the help text.
It's related to #264 and a similar report on IRC.
> net/haproxy: "use_server" will only work for backends

- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- mail/postfix/src/opnsense/scripts/OPNsense/Postfix/setup.sh
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/+TARGETS
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/recipient_access
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/sender_access
Just add some basic additional security before release.
sender and recipient access is only a stub and will be ignored. Can be later added for advanced filtering based on mail addresses.
> Postfix sender restrictions

- sysutils/smart/src/www/diag_smart.php
Small fix. Prevents empty form dropdowns when no SMART devices are available (i.e. running in a VM with a vdisk)
> Suppress output when no SMART devices available

- net/siproxd/Makefile
- net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd.conf
Fixed a copy and paste issue in net/siproxd/src/opnsense/service/templates/OPNsense/Siproxd/siproxd.conf: `rtp_port_high` was not set from the UI.
On my setup, RTP relaying failed because of this issue. SIP calls were established but audio didn't work. Error messages:
ERROR: rtp_relay_start_fwd: no RTP port available or bind() failed
were logged.
The fix was tested under 17.7 latest as of today.
> net/siproxd: fixed rtp_port_high in template

- net/freeradius/Makefile
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/general.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/General.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/+TARGETS
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/dictionary
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-counter
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/radiusd.conf
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/sites-enabled-default
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users
- Reintroduce radiusd.conf with dynamic lib dir
- Let the user choose to log to file or via syslog
- Add dictionary file
- Let the user enable logging of good/bad pass 
- Let the user enable daily session limit for captive portal
I need this in master for a devel pkg but needs some more testing by community, so stable better for 17.7.9 or 18.1 with some more additions. :)
> net/freeradius: add extended logging and daily session limit

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns.inc
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
Major changes:
* Add `Route53 (v6)` in supported service list
* It shared the same code block as `Route53`, uses `$this->_useIPv6` to determine maintaining `A` or `AAAA` records.
> Add support for route53 IPv6

- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- mail/postfix/src/opnsense/scripts/OPNsense/Postfix/generate_certs.php
- mail/postfix/src/opnsense/scripts/OPNsense/Postfix/setup.sh
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
- Let the user choose whether the SMTP MUST be encrypted or MAY be encrypted
- Let the user choose certficate and CA, looks good under https://de.ssl-tools.net/mailservers
> mail/postfix: add smtp security enforcement and certificate selection

- net/haproxy/Makefile
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
none
- do not enable HSTS unconditionally (now works as described in #380)
- enable HSTS only for HTTP frontends
> net/haproxy: bugfix release 2.1

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
none
- fix for rules parameters (values could not be saved, leading to invalid rules)
> net/haproxy: bugfix release 2.2

- net/frr/Makefile
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
this will add buttons like in the tor plugin with one exception:
in the view bgp -> neighbors: the table has not enough space so it is only the icon there.
@fichtner should we bump the version?
> add service reload button like in security/tor

- net/freeradius/Makefile
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/Api/LdapController.php
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/LdapController.php
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/general.xml
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/ldap.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/General.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Ldap.php
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Ldap.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Menu/Menu.xml
- net/freeradius/src/opnsense/mvc/app/views/OPNsense/Freeradius/ldap.volt
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/+TARGETS
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-ldap
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/sites-enabled-default
This update adds basic LDAP support. It allows to bind via LDAP and LDAPS, certification validation is disabled ATM, will follow after 18.1 or so. Also there's no search filter option available yet, but I need a devel pkg for the community to test. Perhaps this can go stable with 18.1, depends on the guys in the forums :)
> net/freeradius: Add basic LDAP support to FreeRADIUS

- databases/redis/src/opnsense/mvc/app/controllers/OPNsense/Redis/forms/settings.xml
Does not start the translation
Traceback (most recent call last):
File "./scripts/collect.py", line 70, in <module>
fOut.write(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 44: ordinal not in range(128)
> Fix label.

- dns/dyndns/src/www/services_dyndns.php
- net/igmp-proxy/src/www/services_igmpproxy.php
Error: The element button must not appear as a descendant of the a element.
Specification:
http://w3c.github.io/html/textlevel-semantics.html#the-a-element
"Allowed ARIA role attribute values: link (default - do not set), button, checkbox, radio, switch, tab or treeitem"
"The <a> element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g., buttons or other links)."
> HTML Compliance - Element <button> Descendant of <a> Element

- sysutils/scp-backup/Makefile
- sysutils/scp-backup/pkg-descr
- sysutils/scp-backup/src/opnsense/mvc/app/controllers/OPNsense/ScpBackup/Api/GeneralController.php
- sysutils/scp-backup/src/opnsense/mvc/app/controllers/OPNsense/ScpBackup/GeneralController.php
- sysutils/scp-backup/src/opnsense/mvc/app/controllers/OPNsense/ScpBackup/forms/general.xml
- sysutils/scp-backup/src/opnsense/mvc/app/models/OPNsense/ScpBackup/ACL/ACL.xml
- sysutils/scp-backup/src/opnsense/mvc/app/models/OPNsense/ScpBackup/General.php
- sysutils/scp-backup/src/opnsense/mvc/app/models/OPNsense/ScpBackup/General.xml
- sysutils/scp-backup/src/opnsense/mvc/app/models/OPNsense/ScpBackup/Menu/Menu.xml
- sysutils/scp-backup/src/opnsense/mvc/app/views/OPNsense/ScpBackup/general.volt
- sysutils/scp-backup/src/opnsense/scripts/OPNsense/ScpBackup/ScpBackup.php
- sysutils/scp-backup/src/opnsense/service/conf/actions.d/actions_scpbackup.conf
This simple plugin takes a few parameters, such as hostname and username and
schedules a cron job to remotely scp the config.xml file at regular intervals.
It uses the public/private keypair of the built-in root user as the source of
the key exchange. This means that the public key must be copied to the remote
host and added to the authorized_keys file (for the defined user).
The remote file is backed up as `config-YYYY-DD-MM-HH-MM.xml`, for example:
`config-2018-01-02-15-40.xml`. It's possible to change the remote location of
where the config file is backed up to.
The cron job can be modified under System/Settings/Cron and the schedule
adjusted to suit the backup frequency requirements.
-=david=-
closes #457
> A new plugin to allow SCP config backups to a remote host.

- dns/dyndns/src/www/services_dyndns_edit.php
- dns/rfc2136/src/www/services_rfc2136_edit.php
- net-mgmt/snmp/src/www/services_snmp.php
- net/igmp-proxy/src/www/services_igmpproxy_edit.php
- net/l2tp/src/www/vpn_l2tp.php
- net/l2tp/src/www/vpn_l2tp_users_edit.php
- net/pppoe/src/www/vpn_pppoe_edit.php
- net/pptp/src/www/vpn_pptp.php
- net/pptp/src/www/vpn_pptp_users_edit.php
- net/relayd/src/www/load_balancer_monitor_edit.php
- net/relayd/src/www/load_balancer_pool_edit.php
- net/relayd/src/www/load_balancer_setting.php
- net/relayd/src/www/load_balancer_virtual_server_edit.php
- net/relayd/src/www/status_lb_vs.php
- net/relayd/src/www/widgets/widgets/load_balancer_status.widget.php
- net/upnp/src/www/services_upnp.php
- net/wol/src/www/services_wol.php
- net/wol/src/www/services_wol_edit.php
- net/zerotier/src/opnsense/mvc/app/views/OPNsense/Zerotier/overview.volt
- sysutils/smart/src/www/diag_smart.php
- sysutils/smart/src/www/widgets/widgets/smart_status.widget.php
width, align, valign, cellpadding, cellspacing, border, summary, bgcolor
Error: The width attribute on the table element is obsolete. Use CSS instead.
Error: The align attribute on the table element is obsolete. Use CSS instead.
Error: The valign attribute on the table element is obsolete. Use CSS instead.
Error: The cellpadding attribute on the table element is obsolete. Use CSS instead.
Error: The cellspacing attribute on the table element is obsolete. Use CSS instead.
Error: The border attribute on the table element is obsolete. Use CSS instead.
Error: The summary attribute on the table element is obsolete. Consider describing the structure of the table in a caption element or in a figure element containing the table; or, simplify the structure of the table so that no description is …
> HTML Compliance - Obsolete table attributes

- dns/dyndns/src/www/services_dyndns_edit.php
Without it, when selecting Route53 v6, the options needed for Route53 would not be shown
> Use Route53 options for IPv6 as well

- dns/dyndns/Makefile
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
It was easier to re-add the pull request ;-)
Now, if the RR for a hostname has both IPv4 and IPv6 addresses, the correct RR is chosen by the current RR type.
>  Added check for RR type (re-added)

- security/tor/Makefile
- security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/ExitaclController.php
- security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/GeneralController.php
- security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/HiddenserviceController.php
- security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/HiddenserviceaclController.php
- security/tor/src/opnsense/mvc/app/controllers/OPNsense/Tor/Api/SocksaclController.php
the new code does not contain any "foreign code" except the function left
in general as well as the servicecontroller (code originally borrowed from IDS which is now gone).
> security/tor: DRY controller code and fix copyright statements

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- add support for the PROXY protocol (i.e. in combination with postfix or dovecot)
- switch to HAProxy 1.8.4
none
none
> net/haproxy: Release 2.5

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- add support for `http-response set-status` to manipulate HTTP status codes
- fix invalid backend name when using `nbsrv` in ACLs
none
> net/haproxy: release 2.6

- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
When adding network type for ospf in frr it's only reflected in the UI and not actually written to ospfd.conf. With this PR the ospf network type is added to ospfd.conf if it's set for an interface.
> frr: Add OSPF interface net type to ospfd.conf

- sysutils/monit/Makefile
- sysutils/monit/src/opnsense/mvc/app/models/OPNsense/Monit/Monit.xml
Allow parameter in path option for services and tests with 'Execute' action.
Fix for #585
> sysutils/monit: allow parameter in path options

- net-mgmt/lldpd/Makefile
- net-mgmt/lldpd/src/opnsense/mvc/app/controllers/OPNsense/Lldpd/forms/general.xml
- net-mgmt/lldpd/src/opnsense/mvc/app/models/OPNsense/Lldpd/General.xml
- net-mgmt/lldpd/src/opnsense/service/templates/OPNsense/Lldpd/lldpd
Requested here: https://forum.opnsense.org/index.php?topic=7558.0
First I took select_multiple to allow the user to choose interfaces, but this is not really compatible with complex configurations (like described in help text). I think for such a little daemon it's ok to not use validation and only offer a text field.
> net-mgmt/lldp: Ability to set interfaces

- mail/postfix/Makefile
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- mail/postfix/src/opnsense/scripts/OPNsense/Postfix/setup.sh
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/+TARGETS
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/smtp_auth
- Add new field for relayhost / smarthost
- Add smtp authentication to authenticate local instance against a smarthost
Request from https://forum.opnsense.org/index.php?topic=7538.0
> mail/postfix: add smarthost and smtp authentication

- net/relayd/Makefile
- net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/Api/SettingsController.php
- net/relayd/src/opnsense/mvc/tests/app/compound/OPNsense/Relayd/RelaydTest.php
- net/relayd/src/opnsense/service/conf/actions.d/actions_relayd.conf
- net/relayd/src/opnsense/service/templates/OPNsense/Relayd/relayd.conf
This PR adds PHPunit tests for the plugin API controllers.
And it fixes some potential bugs that came up during testing. :slightly_smiling_face: 
The SettingsController uses a single model object now to avoid caching problems.
1. install PHPunit
`# pkg install phpunit6-php71`
2. run phpunit
:bangbang: The test will purge the relayd configuration. :bangbang:
`# phpunit /usr/local/opnsense/mvc/tests/app/compound/OPNsense/Relayd/RelaydTest.php`
> net/relayd: add PHPunit API controller tests

- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
The help message on the Freeradius User form is off for the enabled, username and password fields.
Username and Password have regex mask validation patterns, but the help message was placed on the wrong field.
Fixed this by moving the 'Allowed characters' text to the correct help field.
> FreeRadius: Fix help message on User dialog

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- support rise/fall parameters in backends and health checks
- support set-path in ACLs
- fix X-Forwarded-For option disappeared (#647)
none
> net/haproxy: release 2.7

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Hello, 
I made few changes to add domain key length field to the GUI, giving the user the ability to specify the desired key length.
Also deleting --keylength paramter from acme client on revoke as it's not needed because the script will seek the cert installation path.
I tested on many scenarios and it's working properly.
> security/acme-client: Add the ability to specify domain key length

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M2_7_0.php
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This addition makes it pretty easy to configure cookie-based persistence. A new setting was added to the "Edit Backend Pool" configuration page:
When enabling cookie-based persistence, the following HAProxy options will be added or changed:
```
backend example_backend
stick-table type ip size 50k expire 30m
-    stick on src
+    cookie SRVCOOKIE prefix
timeout connect 30s
timeout server 30s
-    server websrv1 10.0.0.1:80 check inter 1000 
+    server websrv1 10.0.0.1:80 check inter 1000  cookie 5aff65dd69e5e163736656
frontend example_frontend
default_backend example_backend
+    # remove quotes from persistence cookie
+    http-request replace-header Cookie '^(.*?; )?(SRVCOOKIE=)"([^;"]*)"(;.*)?$' \1\2\3\4
```
The cookie value is derived from each server's unique ID. This value is …
> net/haproxy: support for cookie-based persistence

- security/acme-client/Makefile
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Fixes #333.
This workaround solved the issue in an artificial test scenario. Let's hope it fixes this annoyance for everyone.
> security/acme-client: fix node no longer exists error

- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
Although the help text states that the "source address" field in servers/backends supports port ranges, the validation mask prevents this configuration.
This patch fixes the validation mask to support port ranges (and while here, IPv6 addresses too).
> net/haproxy: fix validation for source address fields

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Add support to other DNS APIs:
autoDNS (InternetX)
Azure DNS
DirectAdmin 
DreamHost DNS
INWX 
KingHost DNS
Knot (knsupdate) DNS
Namesilo.com DNS
selectel.com / selectel.ru
Servercow 
UnoEuro
Zilore DNS
zonomi.com
> security/acme-client: add support to multiple dns api providers

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
The tokenizer was removed for _some_ fields in https://github.com/opnsense/plugins/commit/701b3812f32c2b5ecc7c05ba42aaad205e3a85f2. For certain fields, the sort order is important. Without using tokenizer, the sort order is no longer visible to the user. This effectively breaks functionality.
@AdSchellevis @fichtner Is there a replacement/alternative for tokenizer in 18.7?
> net/haproxy: bring back tokenizer

- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/RIP.xml
Fixes #607
Added missing options, removed invalid and non-implemented ones (Babel, PIM, IS-IS).
> net/frr: cleaned up redistribute options

- .gitignore
- net/haproxy/Makefile
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- www/nginx/Makefile
- www/nginx/src/etc/nginx/views/opnsense_error_404.html
- www/nginx/src/etc/nginx/views/opnsense_server_error.html
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/php-www.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/ruleset.conf
www/nginx:
* add an if check for rules because it may not exist
* give the www php socket to www
* insert whitelist rule 19 (block if no rules loded) to lower the risk of an incorrectly configured system.
* theme for 404 and 50x
security/acme-client:
* rename SSL certificate to X.509 certificate - this is what is is correctly called - I hope nobody is still using SSL and X.509 is not bound to TLS (can probably be used for IKE as well)
* add the ability to restart nginx
global:
* add PhpStorm files to `.gitignore`
> www/nginx: some bugfixes; add a rule for the upcoming naxsi release; add restart action to acme

- net/relayd/Makefile
- net/relayd/src/opnsense/service/templates/OPNsense/Relayd/relayd.conf
Fix failed syntax check of the relayd.conf with check type HTTP.
> net/relayd: relayd.conf template failed with http checks

- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
acme.sh stores some account-related information in
/var/etc/acme-client/home/ca
this leads to "validation failed" messages every time a certificate
with a different account is validated
this is fixed by adding ACCOUNT_JSON_PATH and CA_CONF to account.conf
> fix acme operations when using multiple accounts

- net-mgmt/net-snmp/Makefile
- net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd.conf
'rocommunity6' is necessary to be able to fetch information via IPv6.
> Fixing net-snmp IPv6 compatibility

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
I was confused for a long time about the error message "check your hostname is
correct". It turns out that this error was raised because the
Dynamic DNS code can only update existing records, not create new ones. I think
it would be better if it could create A records but for now this more
informative error message gives another valid reason that the update could be
failing.
> More informative cloudflare hostname error message

- net/frr/Makefile
How do we handle highering the sysctl?
`sysctl kern.ipc.maxsockbuf=16777216`
> net/frr: change frr3 to frr5

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This PR adds support for the "http-reuse" option (http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-http-reuse) for a HAproxy backend.
> net/haproxy: add "http-reuse" option

- net/vnstat/Makefile
- net/vnstat/pkg-descr
- net/vnstat/src/etc/inc/plugins.inc.d/vnstat.inc
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/Api/GeneralController.php
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/Api/ServiceController.php
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/GeneralController.php
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/forms/general.xml
- net/vnstat/src/opnsense/mvc/app/models/OPNsense/Vnstat/ACL/ACL.xml
- net/vnstat/src/opnsense/mvc/app/models/OPNsense/Vnstat/General.php
- net/vnstat/src/opnsense/mvc/app/models/OPNsense/Vnstat/General.xml
- net/vnstat/src/opnsense/mvc/app/models/OPNsense/Vnstat/Menu/Menu.xml
- net/vnstat/src/opnsense/mvc/app/views/OPNsense/Vnstat/general.volt
- net/vnstat/src/opnsense/scripts/OPNsense/Vnstat/setup.sh
- net/vnstat/src/opnsense/service/conf/actions.d/actions_vnstat.conf
- net/vnstat/src/opnsense/service/templates/OPNsense/Vnstat/+TARGETS
- net/vnstat/src/opnsense/service/templates/OPNsense/Vnstat/vnstat
- net/vnstat/src/opnsense/service/templates/OPNsense/Vnstat/vnstat.conf
I read a couple of times users (e.g. Dominian) need a method to count monthly traffic, beginning from e.g. 01.09. 00:00:01 to 30.09 23:59:59. This plugin would easy monitor usage by hour/day/week/month incl. future predictions which might be quite nice for LTE connections where traffic is billed by MB. 
EDIT: I kept the options at a minimum for beginning and wait for feedback if users need more.
> net/vnstat: new plugin

- net/vnstat/src/opnsense/scripts/OPNsense/Vnstat/setup.sh
On some systems /var/lib also doesn't exist, so permissions on /var/lib were 750 and then the user vnstat cannot reach subdir /var/lib/vnstat.
> net/vnstat: update setup.sh

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
- net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
Add DNS servers to interface via `resolvconf`
Now local DNS lookups work with AzireVPN.
No bump since 0.4 isn't released yet.
> net/wireguard: add DNS to server config

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns.inc
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
* add IPv6 support
* create DNS record if it doesn't exist
* better variable naming
* saner parsing of FQDN (previous code assumed all FQDNs had exactly
three parts)
* trimming of whitespace in the fqdn field is actually effective now
* warn if multiple records match when getting the record id
* removed “proxiable” attribute when updating, it is not an attribute
you can set as far as I know
* default “proxied” to off, assuming most people don't host websites
from their firewalls
> Add IPv6 support to Cloudflare DDNS and other fixes:

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
- net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
- wrong templating when using multiple endpoints
- moved disable routes to server since it's a global configuration, not client related.
> net/wireguard: hotfix for latest master

- www/nginx/src/etc/inc/plugins.inc.d/nginx.inc
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/BansController.php
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/IndexController.php
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/cache_path.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream_server.xml
- www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/AccessLogLine.php
- www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/AccessLogParser.php
- www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/ErrorLogParser.php
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Menu/Menu.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/ban.volt
- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/logs.volt
- www/nginx/src/opnsense/scripts/nginx/csp_report.php
- www/nginx/src/opnsense/scripts/nginx/ngx_auth.php
- www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
- www/nginx/src/opnsense/scripts/nginx/read_log.php
- www/nginx/src/opnsense/scripts/nginx/setup.php
- www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/webgui.conf
found stuff is sent to a special log and can be parsed periodically via a Cron job to update the alias automatically.
* Also marked some settings as advanced to decrease the size of some dialogs.
* In addition (request per mail), I added web socket support.
* Nice feature I've found in the nginx docs: HTTP/2 preloading.
* Allow caching
> www/nginx: new features

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
Add optional support to url prefix in proxy_pass module according module documentation. 
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
> Add nginx path_prefix in proxy_pass

- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
Currently the code [::]:80 ipv6only=off does not supported when running multiple servers in nginx.conf
More details in
https://unix.stackexchange.com/questions/321879/remove-ipv6only-option-from-puppet-nginx-module
https://serverfault.com/questions/638367/do-you-need-separate-ipv4-and-ipv6-listen-directives-in-nginx
http://nginx.org/en/docs/http/ngx_http_core_module.html#listen
https://forum.opnsense.org/index.php?topic=8877.msg44610#msg44610
This fix works as expected.
> Make nginx support multiple servers entries

- misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/nv.d3.css
@fichtner 
when I split the main.css, the colors in cicada for the reporting have been lost. This is unfortunately too late for this release but would still be great if you could at least merge it for the next release. sorry it was my mistake. best regards rené
> nv.d3.css - legend fix color

- net/vnstat/Makefile
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/forms/general.xml
- net/vnstat/src/opnsense/mvc/app/models/OPNsense/Vnstat/General.xml
- net/vnstat/src/opnsense/service/templates/OPNsense/Vnstat/vnstat
- net/vnstat/src/opnsense/service/templates/OPNsense/Vnstat/vnstat.conf
Add ability to monitor multiple interfaces, e.g. to sum 2 WANs together.
> net/vnstat: add multiple interfaces, ready for stable

- misc/theme-cicada/Makefile
- misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
- misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
- misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/nv.d3.css
- misc/theme-tukan/Makefile
- misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
- misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/jquery.bootgrid.css
- misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css
- misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/nv.d3.css
no expansion delay / animation  -> https://github.com/opnsense/core/issues/2554
nv.d3.css fixes
other small fixes
> tukan/cicada (no expansion delay / animation / nv.d3.css) fixes

- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/upstream.conf
I've some trouble while trying with multiple upstream servers:
```
nginx: [emerg] "upstream" directive is not allowed here in /usr/local/etc/nginx/nginx.conf:56
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed
```
I've made a small change to make it work.
> Problem with multiple Upstream servers

- sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/forms/settings.xml
- sysutils/nut/src/opnsense/mvc/app/models/OPNsense/Nut/Nut.xml
- sysutils/nut/src/opnsense/service/templates/OPNsense/Nut/ups.conf
Add blazer_usb driver, closes #905 
Current stable of nut is 1.0, with 1.1 I added apcsmart which sadly  wasn't verified yet, 1.2 splitted diagnostics for timeout reasons. Now I didn't touch the makefile, should we make 1.3 or how to handle this now?
> sysutils/nut: add blazer_usb driver

- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/ruleset.conf
root cause: even if MainRule is successfully parsed, it is currently
not supported. So it must be moved to a basic rule.
> www/nginx: fix rule 19 issue

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/general.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml
As discussed with @fichtner in IRC, added carpfailover.
Franco will add the carp syshook and a config loader
> net/frr: add carp failover option

- net/haproxy/Makefile
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
none
- fix warning: a 'http-request' rule placed after a 'use_backend' rule will still be processed before (#999)
- fix wrong parameter name when using `tcp-request content lua` (#999)
- internal: trim whitespace, remove empty lines in haproxy.conf (#999)
> net/haproxy: Release 2.11

- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
Check if charset is defined in http section, currently when choosed charset to "none", the code add **charset** option without value, and nginx service fail.
According http://nginx.org/en/docs/http/ngx_http_charset_module.html
> Check if charset is defined

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Hi, I was looking to enable **HTTP/2** support in haproxy but could not find it. I added a checkbox under the advanced SSL options and added `alpn h2,http/1.1` to the SSL bind options in the template. Wanted to add it as a selectable SSL bind option in the GUI first, but it became too complex because the options string is split on commas. Therefore I decided to add it as a checkbox instead. 
Tested on my installation of Opnsense 18.7.8 (haproxy plugin 2.10, haproxy 1.8.14):
> net/haproxy: Add support for HTTP/2

- www/nginx/pkg-descr
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/streamserver.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf
* Add proxy protocol support
* Add real ip support
* Add support to add improved WAF whitelist rules
* Fix a location bug
> www/nginx: add proxy protocol support and improve whitelist handling of WAF

- www/nginx/pkg-descr
- www/nginx/src/opnsense/scripts/nginx/setup.php
happend probably around 1.3 by dropping privileges by running nginx under www:staff
> www/nginx: fix basic auth acl permission error

- www/nginx/src/opnsense/scripts/nginx/ngx_functions.js
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/nginx.conf
allow the plugin to detect a MitM before us.  See: #1044. This pull request should make the feature available to nginx when done.
> WIP: www/nginx: add njs script to detect MitM attacks on TLS connections

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
When refactoring the Cloudflare DDNS code, I removed a bunch of assumptions
but inadvertently added one. The refactored code did not allow for "apex"
domain records, records for which there is no hostname, just the bare
domain. (Traditionally, these have been referred to as '@' records but
with the Cloudflare API, you just hand it the name of the zone.)
Ideally there would be a checkbox or something in the UI for this, or
even better a way to specify the record and zone separately but in lieu of
that, we first try to break the provided string down into hostname and
domain portions and look up the zoneId from that. If that fails, we try
to look up the zondId using the whole string. And then finally fail if
neither return a zone from the API.
Hopefully fixes #926 and possibly the issue …
> Fix for using apex domains with cloudflare DDNS

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/LogsController.php
- www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/AccessLogParser.php
- www/nginx/src/opnsense/mvc/app/library/OPNsense/Nginx/StreamAccessLogParser.php
don't read log file at once (convert reader to line by line read) and don't extract JSON structure in controller
> www/nginx: backend performance improvements

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
- net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
The PersistentKeepalive option is important for tunnels though a NAT.
Would be nice to have it configurable though the web interface.
> add wireguard persistent keepalive option

- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
As requested here:
https://github.com/opnsense/plugins/pull/1002#issuecomment-447898515
> net/frr: make 'set' in route-maps optional

- dns/dyndns/Makefile
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
HE.net TunnelBroker endpoint update URL changed at some point, the old URL still works, but it's probably better to use their current recommendation. The new one looks like:
https://<user>:<pass>@ipv4.tunnelbroker.net/nic/update?hostname=<tunnelid>
Also enable HTTPS certificate verification for HE.net DNS service, they are now using Let's Encrypt.
> dns/dyndns: update HE.net TunnelBroker URL

- www/nginx/Makefile
- www/nginx/src/opnsense/scripts/nginx/ngx_functions.js
cleanup: this is not needed since the utf-8 / raw compare is fixed in nginx now.
> www/nginx: remove workaround for njs encoding bug; release 1.6

- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
The checkbox for "Collect CPU Time" in telegraf doesn't work because there is a typo in input.xml
> Fix "Collect cpu time" in telegraf plugin

- mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/dkim_signing.conf
This fixes an issue here if you have redis in use in other places in rspamd did it is set to now use it by default in dkim_signing.conf. By adding the if else this makes it so that we can store the dkim keys in redis.
> fixing use_redis in dkim_signing.conf

- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Menu/Menu.xml
I'll start now moving nginx in production and will do some more work on it. 
At first could we reorder the menu as within most menues the logs are at the bottom and configuration on the top?
> www/nginx: reorder menu

- security/clamav/Makefile
- security/clamav/pkg-descr
- security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/forms/general.xml
- security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/General.xml
- security/clamav/src/opnsense/service/templates/OPNsense/ClamAV/freshclam.conf
> security/clamav: add third party signatures

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/upstream.xml
> www/nginx: misleading help attribute for upstream.tls_enable

- www/nginx/README.md
- www/nginx/pkg-descr
- www/nginx/src/etc/nginx/opnsense_http_vhost_plugins/README
- www/nginx/src/etc/nginx/opnsense_stream_vhost_plugins/README
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/settings.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/streams.conf
see release note
partial of: https://forum.opnsense.org/index.php?topic=8877.msg52677#msg52677
> www/nginx: plugins, bug fixes

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M2_7_0.php
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- rules can finally be sorted by using drag'n'drop (#582)
- added "enabled" field to servers (#1208)
- TCP inspection delays are supported in rules (#1188)
none
- server option "mode" is always visible, no longer requires "advanced mode" (#1208)
- most dropdown fields finally have alphanumeric sorting (#687, https://github.com/opnsense/core/issues/3251)
- rules: align indentation of comments in haproxy.conf
> net/haproxy: release 2.15

- misc/theme-cicada/src/opnsense/www/themes/cicada/assets/stylesheets/main.scss
- misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/main.css
- misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
- misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css
see -> https://github.com/opnsense/core/pull/3286#issuecomment-469782949
@fichtner 
@AdSchellevis
> core/vpn/ipsec: allow easier override of colors in themes fix

- net/freeradius/src/opnsense/mvc/app/views/OPNsense/Freeradius/dhcp.volt
As discussed with @fichtner .. can go to stable with 19.1.4
> net/freeradius: add warning to dhcp

- net/freeradius/Makefile
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/eap.xml
- net/freeradius/src/opnsense/scripts/Freeradius/generate_certs.php
Certificate files were not properly generated. There was a mixup between service cert and ca cert. Also added elaboration on what the purpose of the `Root CA` is. I run this already in production.
> net/freeradius: fix certificate generation

- www/nginx/pkg-descr
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/security_rule.conf
See: https://forum.opnsense.org/index.php?topic=12245.0
> www/nginx HSTS bug

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
Fixes updates to hosts with multiple levels of subdomains as mentioned in #1299.
Changes zone ID lookup for CloudFlare DDNS so that instead of guessing at hostname & domain parts of FQDN using array_push and testing with an API call, we instead request a list of zones and compare to $fqdn for an exact match, or one that matches the ending of $fqdn. This is reliable for multi-level subdomains of unrestricted depth.
Also eliminates an API call to check for an exact $fqdn match since this will also work in that scenario.
> Fixes #1299 by changing CloudFlare zone ID lookup behavior

- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
@fabianfrz As stated in https://github.com/opnsense/plugins/pull/1292#issuecomment-487414386 I think the current approach is flawed:
https://github.com/opnsense/plugins/blob/930ebe8111cc33bbb9825fd8b213b4c4aa68c704/www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf#L180-L184
nginx should proxy requests to ACME's own web service instead of accessing ACME's files directly. Furthermore the configurable port number of ACME's web service should be used:
https://github.com/opnsense/plugins/blob/930ebe8111cc33bbb9825fd8b213b4c4aa68c704/security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/lighttpd-acme-challenge.conf#L65
This way we're one step closer to a better integration between our Let's Encrypt and nginx plugins.
> www/nginx: fix ACME support

- net/haproxy/Makefile
The FreeBSD port net/haproxy was recently switched to the 1.9 release series of HAProxy. As stated in https://github.com/opnsense/plugins/issues/1089 I'd rather stay on 1.8.x until 2.0 was released and stabilized.
HAProxy 1.8 moved to a new port:
https://www.freshports.org/net/haproxy18
refs https://github.com/opnsense/tools/pull/141
> net/haproxy: keep HAProxy 1.8.x

- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
This PR fixes #1374, locally verified with my own rules. 
Since the form already allowed to specify the "URL" zone, this PR is a bugfix only.
> www/nginx: #1374 - Fixes matching values in URLs using naxsi rules.

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns.inc
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
I added basic DigitalOcean dynamic DNS support to the dyndns plugin. It requires knowing the record ID of the domain, which unfortunately means you won't see the actual name of the record being updated. It works well enough for my purposes, though, and you can always put the record name in the description field for reference.
> DigitalOcean dynamic DNS

- net/google-cloud-sdk/Makefile
- net/google-cloud-sdk/pkg-descr
This is a dummy plugin in order to install the Google Cloud SDK (and to check wether it's installed programmatically).
This is mostly required for our Let's Encrypt plugin to support Google Cloud DNS API (#1318).
I've decided to create a separate plugin instead of adding it as a dependency in os-acme-client, because the SDK is relatively huge and not useful for most users.
> new plugin: google-cloud-sdk, refs #1318

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/validations.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- add support for Domain-Offensive LetsEncrypt API dns_doapi (#1294)
- add support for Namecheap API (dns_namecheap)
- add support for Google Cloud DNS API dns_gcloud (#549)
- certificate status not correctly updated ( #1307)
- add log message when certificate status is updated (refs #1307)
> security/acme-client: release 1.24

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/CertificatesController.php
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf
- run `acme.sh --remove` when a cert is removed from the GUI (#1380)
- add a new button to remove the private key (#990)
none
none
> security/acme-client: release 1.24 (additions)

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAcl.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogHealthcheck.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- allow backends without servers (#1304)
- add support for deciphered SNI check in ACLs (#1365)
- allow to force SSL for health checks (#1282)
none
- improve wording for SNI conditions to differentiate between deciphered vs. not deciphered
> net/haproxy: release 2.17

- mail/postfix/Makefile
- mail/postfix/pkg-descr
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/Api/SendercanonicalController.php
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/SendercanonicalController.php
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/dialogEditPostfixSendercanonical.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Menu/Menu.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Sendercanonical.php
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Sendercanonical.xml
- mail/postfix/src/opnsense/mvc/app/views/OPNsense/Postfix/sendercanonical.volt
- mail/postfix/src/opnsense/scripts/OPNsense/Postfix/setup.sh
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/+TARGETS
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/sendercanonical
This PR adds support for configuring postfix sender_canonical_maps with regexp expressions. This is needed when relaying mail over an external SMTP server that only allows sending with specific sender addresses. (e.g. only the address that was also used for authenticating with the external relay). This PR is based on the Address/virtual configuration in the postfix plugin and works mostly the same.
> mail/postfix: Add support for configuring sender_canonical_maps

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
**Important:**
This will only work with the next release of acme.sh (2.8.2).
Besause the current implementation of the netcup dns api in acme.sh dosen´t work on BSD systems.
For more infos see https://github.com/Neilpang/acme.sh/issues/2279 and https://github.com/Neilpang/acme.sh/pull/2284
> security/acme-client: Add Support for netcup DNS API

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_highwinds.php
- add support for netcup DNS API (#1350)
- updating an existing cert in Highwinds API failed with a 404 error (wrong HTTP method)
- fix "Use of undefined constant" PHP errors
- treat certificate serial number as string not as integer
- move "remove certificate" button to the end of the button list
> security/acme-client: release 1.25

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Menu/Menu.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This adds support for a single HTTP cache in HAProxy.
This currently supports the configuration options that HAProxy 1.8 allows for the cache ("total-max-size" and "max-age") but not the "max-object-size" option supported by HAProxy 2.0.
Only a single cache can be defined and this initial version does not allow caching to be based on an ACL.
Configuration is a two step process by firstly enabling and configuring the cache and then enabling caching in a backend pool.
Enabling caching in a backend pool without first enabling the cache under Settings will have no effect on the config.
> net/haproxy: Initial support for HAProxy cache

- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
This change updates the default for "http-reuse" to match the recommendation to use "safe" from the HAProxy documentation since HAProxy 1.6, despite the default actually being "never" since the option was introduced.
It also matches the new default in the current HAProxy 2.0 release so things are ready for when it comes to OPNsense.
> net/haproxy: Change http-reuse default

- net/haproxy/Makefile
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- add support for HAProxy cache (#1442)
none
- change http-reuse default (align with HAProxy's default value, #1439)
> net/haproxy: release 2.18

- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindDomain.xml
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindRecord.xml
- dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/domain.db
Hi @mimugmail,
I'll be using your plugin to manage mostly _slave_ zones. I've noticed that some small tweaks improved my experience. Let me know what you think.
The most "controversal" change might be that I ask you to rename "domain" to "zone", because it more precisely describes what can be managed here – both forward and reverse zones. But "domain" usually refers only to forward zones. :)
However, here is the full list of changes:
* Rename "domain" to "zone", because both forward and reverse zones can be used
* Hide options that are only valid for either master or slave zones
* Move field "name" to the top (it's the logical order IMHO, but also required to hide options)
* Improve some help messages (fix typos, add examples and more detailed explanations)
* Automatically replace "@" …
> dns/bind: small improvements for zone management

- sysutils/smart/src/opnsense/scripts/OPNsense/Smart/detailed_list.sh
- sysutils/smart/src/www/widgets/widgets/smart_status.widget.php
Hi,
In my environment , SMART status in dashboard was not correctly displayed.
- OPNsense 19.7.1 (with no patch, and fixed with only patch of this pull request)
- Protectli Vault FW1
- Transcend mSATA 64GB SSD TS64GMSA370
In that I had two problems:
- `smartctl -H` accepts device file path like /dev/ada0, while `ls /dev | grep ad` shows just a basename like ada0.
- `smartctl -H` emits space after colon, while current program does not ignore in comparison.
and the one trivial addition:
- In case of error (`default:` in `switch`), a small red box shows up but has no message in it.
```
% sudo smartctl -H /dev/ada0
smartctl 7.0 2018-12-30 r4883 [FreeBSD 11.2-RELEASE-p11-HBSD amd64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF READ …
```
> SMART dashboard widget to display correct status

- net/freeradius/Makefile
- net/freeradius/pkg-descr
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users
Closes #1444 
I made a multi_select field with Integer 1-19, so it's a mix of both discussed solutions.
> net/freeradius: add Service-Type

- dns/bind/Makefile
- dns/bind/pkg-descr
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Dnsbl.xml
- dns/bind/src/opnsense/scripts/OPNsense/Bind/dnsbl.sh
- dns/dnscrypt-proxy/Makefile
- dns/dnscrypt-proxy/pkg-descr
- dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/Dnsbl.xml
- dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh
Per https://zeustracker.abuse.ch/ # ZeuS Tracker has been discontinued on Jul 8th, 2019, remove zeus tracker from dnsbl.
> bind/dnscrypt-proxy: DNSBL ZeuS Tracker has been discontinued

- net/frr/src/etc/rc.carp_service_status.d/carp_frr_ospf
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/scripts/quagga/event_loop.sh
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/syslog-ng-frr-events.conf
Currently when a carp node promotes back to MASTER while booting, it's quite likely that no neighbors are found yet and thus the machine wouldn't know where to route the traffic.
Inspired by OpenBSD's handling of carp demotion in ospfd (https://man.openbsd.org/ospfd.conf.5), this should lead to a similar result. Event handling is not complete yet, but the concept seems to be working.
- The basic idea is actually quite simple, create an ospf status monitor script to utilize our new carp hooks (https://docs.opnsense.org/development/backend/carp.html), which monitors if ospfd has neighbors.
- Use Syslog-NG's functionality to filter messages and use those as events, so we can trigger "configctl interface update carp service_status" when our state changes.
Ideally on the (new) backup mode the …
> FRR/ospf: demote/promote carp when no neighbors are found

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
**Problem:**
Currently, it is not possible to have OSPF talk over IPSec VTI interface (and most likely other interfaces but my use case does not cover this).
**Proposed Solution:**
Enable "area" to be defined on a per interface basis.  The expected change is `ip ospf area {{ areaDefinedByUser }}` under each interface in the following file `/usr/local/etc/frr/ospfd.conf`
**Notes:**
Interestingly enough, "area" seem to exist in the Diagnostics view as found in `net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsospf.volt`.  I do not believe I might have accidentally overlooked the GUI as `interface.area` wasn't set in the model.
I also put "area" on top of "cost" in `ospfd.conf` which made the diff look like I deleted a line.  I wanted to keep the order consistent with …
> net/frr: [ospf] Enable Area on a per Interface basis instead of just on router for VTI IPSec

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ActionsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Process.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SSHKeys.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpClient.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpUploader.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Utils.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/setup.sh
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php
- security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf
This PR implements a new automation action for the Let's Encrypt (AcmeClient) client that allows to deploy certs to remote hosts using SFTP after they have been created or renewed.
The purpose of the extension is to securely transfer certificates generated on the firewall to protected hosts that may not be public reachable on ports required to generate certs directly.
**Notes**:
* The feature is very similar to the highwinds upload but it works on any SFTP enabled host.
* Only public key authorization is allowed as it doesn't require exchanging any secrets.
* Host keys and identities are actively managed in a discrete folder, not mixed with standard locations.
* The upload script can be called directly (via console/ssh) to test and trigger it outside of the normal workflow with …
> AcmeClient support cert upload via sftp

- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/main.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
This adds support for the "[max-object-size](http://cbonte.github.io/haproxy-dconv/2.0/configuration.html#10.2.1-max-object-size)" cache configuration option that was added in HAProxy 1.9/2.0.
As this option is not present in Haproxy < 1.9 this must not be merged until #1089 is closed.
> net/haproxy: Update cache to support HAProxy 2.0 option

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/certificates.volt
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/validations.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dns_opnsense.sh
- security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf
- new automation: support cert upload via sftp (#1455)
- add support for OPNsense's BIND plugin (#1491)
- add support for DNS alias mode (#1492, #1301)
none
- add headers for certificate options for the sake of clarity
> security/acme-client: release 1.26

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- switch to HAProxy 2.0 release series (#1089)
- add support for the "max-object-size" cache configuration option (#1458)
- fix IPv6 validation in frontends (#540)
- add IPv6 example to listen address help text
> net/haproxy: release 2.19

- net/frr/src/opnsense/scripts/quagga/quagga.rb
… by frr adding a new line of output to the vtysh command. I reworked the code for processing the 'header' to decrease the likelihood of this happening with future additions in the header. The new code looks for header lines it is interested in, and skips all others until it gets a blank line, at which time it assumes the tabular data is to follow
> net/frr: Issue #1509. Fixing issue with net/frr BGP diagnostics summary tab

- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
I wanted to have support for Rage4 and added it to the XML configuration file.
It works perfectly fine.
Instead of just adding the single provider I want to use, I am adding all providers from dns-lexicon v3.3.3, based on output from `lexicon -h`.
> security/acme-client: Adding more providers from dns-lexicon

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
@fraenki 
Separate PR as suggested for _--debug 2_ and _--debug 3_ support. 
acme.sh is capable of deeper levels of debug messages. This is especially important when the DNS-01 acme challenge doesn't work as expected. The messages include debug messages about the exported env vars, http method calls, etc. that would not be printed at the debug (_--debug_) level. 
This probably is not the best way to do this. Would be happy to take on suggestions to have debug level selection in Settings when _debug_ is selected from _Log Level_. Unfortunately, the volt scripting/ config is currently beyond me.
acme.sh debug levels are implemented as the private functions *_debug*, *_debug2*, and *_debug3*. There are currently no deeper debug levels. A quick verification with [the source …
> security/acme-client: Add support for --debug 2/ 3

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M1_6_0.php
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- add support for Loopia DNS API (#1529)
- automations can now restart Captive Portal or IPsec service after cert renewal (#1534)
- add support for 60+ DNS APIs through [Lexicon](https://github.com/AnalogJ/lexicon) (#1524)
- don't break accounts when switching between stg/prod Let's Encrypt environments (#1528)
- add py-dns-lexicon as plugin dependency to support it in DNS-01 out-of-the-box
- support acme.sh debug log level 2 and 3 (#1546)
> security/acme-client: release 1.27

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
Log level is probably one of the most useful options for anyone using a plugin such as LE. I don't think any other function or plugin that offers a log level option, hides it from the user behind a "show/hide advanced" button.
This PR simply moves the control in the GUI to be always visible, without needing to be exposed by "show advanced".
> security/acme-client: Make "log level" GUI control always visible

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns.inc
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
- dns/dyndns/src/www/services_dyndns_edit.php
This PR adds support for dynamic DNS updates with Linode. The logic is pretty close to the existing Cloudflare code since their REST APIs are very similar.
I've tested creating and updating both A and AAAA for all possible records:
* `<domain>` (root of zone)
* `<hostname>.<domain>`
* `*.<domain>` (wildcard)
I've also tested some failure paths:
* Inputting invalid personal access token -> logs the server-side reason error message
* Inputting invalid domain name -> logs the response containing all domains/records that exist
> Add Linode Dynamic DNS support

- mail/postfix/Makefile
- mail/postfix/pkg-descr
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/antispam.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Antispam.xml
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
Closes #1591 
Currently WIP as I get an model upgrad error.
Anyone have an idea what's wrong?
```
Installed packages to be REMOVED:
os-postfix-devel-1.13
Number of packages to be removed: 1
[1/1] Deinstalling os-postfix-devel-1.13...
[1/1] Deleting files for os-postfix-devel-1.13: 100%
Reloading plugin configuration
Installing os-postfix-devel-1.13...
Extracting os-postfix-devel-1.13: 100%
Stopping configd...done
Starting configd.
*** OPNsense\Postfix\Antispam Migration failed, check log for details
Keep version OPNsense\Postfix\Domain (1.0.1)
Keep version OPNsense\Postfix\General (1.2.4)
Keep version OPNsense\Postfix\Recipient (1.0.0)
Keep version OPNsense\Postfix\Recipientbcc (1.0.0)
Keep version OPNsense\Postfix\Sender (1.0.0)
Keep version OPNsense\Postfix\Senderbcc (1.0.0)
Keep …
```
> mail/postfix: add milter protocol selection

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
solves  #1477 #1614
I've tested this with mutiple domains on a testing env and my home environment, both 19.7.7. Seems to be functional.
Please do an honest review though, I feel this is dodgy at best. Esp. the hack in security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php would need some attention.
> security/acme-client: implement cloudflare token

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
See related upstream commit: ([Neilpang's acme.sh PR # 2562](https://github.com/Neilpang/acme.sh/pull/2562)), adding a DNS-01 method using the Plesk XML API to `acme.sh`. Now merged into acme.sh "dev" branch.
This PR contains the code to allow use of that DNS-01 method via the OPNSense GUI.
**The DNS-01 method has been accepted, but this PR should continue to be left "on hold" until upstream DNS-01 patch appears in a release**
> security/acme-client: Enable new DNS-01 method "pleskxml" in GUI

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
The existing description of "CA Certificate" is confusing, in that it implies the user should select the Certificate Authority responsible for generating their SSL pem (e.g. LetsEncrypt), whereas the parameter is solely used to specify the CA used for verifying Client Certificates. While this might be acceptable in self-signed scenarios where users have the appropriate keys to generate a client CA, it's unfortunately not the case for production SSL certs.
> Clarify purpose of ID httpserver.ca

- security/acme-client/Makefile
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
- security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/lighttpd-acme-challenge.conf
- add support for CloudFlare token (#1625)
- add support for MailinaBox DNS API (#1531)
- add support for Plesk XML API (#1567)
- add support for Variomedia DNS API
- fix IPv6 support for "automatic port forward" validation method (#1590)
- validate IPv4 and IPv6 addresses before using them for "automatic port forward"
- enable IPv6 support on local ACME webservice (when `system.ipv6allow` is enabled)
> security/acme-client: release 1.29

- net/frr/src/opnsense/scripts/quagga/diag-bgp.sh
By omitting the parameter 'ip' vtysh shows IPv4 as well as IPv6 sessions.
> net/frr: show bgp status for IPv4 and IPv6 in diagnostics

- net/vnstat/Makefile
- net/vnstat/pkg-descr
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/Api/ServiceController.php
- net/vnstat/src/opnsense/mvc/app/views/OPNsense/Vnstat/general.volt
- net/vnstat/src/opnsense/service/conf/actions.d/actions_vnstat.conf
Removed weekly, added a note for wiping DB in plugin changelog
> net/vnstat: make plugin compatible to new v2 version

- dns/bind/src/etc/inc/plugins.inc.d/bind.inc
This patch allows to sync the BIND configuration to a secondary node in a OPNsense cluster.
I've tested it with slave zones only (but it should work with master zones too).
> dns/bind: enable xmlrpc sync

- net-mgmt/net-snmp/Makefile
- net-mgmt/net-snmp/pkg-descr
- net-mgmt/net-snmp/src/opnsense/mvc/app/controllers/OPNsense/Netsnmp/forms/general.xml
- net-mgmt/net-snmp/src/opnsense/mvc/app/models/OPNsense/Netsnmp/General.xml
- net-mgmt/net-snmp/src/opnsense/service/conf/actions.d/actions_netsnmp.conf
- net-mgmt/net-snmp/src/opnsense/service/templates/OPNsense/Netsnmp/snmpd.conf
Closes #1602 
Setting version in SysDesc is complicated as it needs a hook to update the config when updating opnsense itself. Better to just call the command and output in a separate OID
> net-mgmt/net-snmp: allow to call opnsense-version via snmp

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/scripts/systemhealth/logformats/telegraf.py
Add log parser for upcoming feature in core.
This changes can already be merged and will take effect as soon as the core will be updated.
**Before**
**After**
**Additional context**
#1702 and opnsense/core#3941
**Special thanks to @AdSchellevis for making this possible**
> net-mgmt/telegraf: Add log parser to display logs correctly 

- dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.py
Fixes issues with hosts files that contains comments and/or non-valid characters in domain names as issued by https://github.com/marunjar in https://github.com/opnsense/plugins/issues/1699
See: https://regex101.com/r/JAAMgV/6
> unbound-plus: another regex fix

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
Commit ab0ccc3be92ff4b716296d0d683cc0e1c8975030 seems to have mistakenly removed the `break` statement for the `switch` case for Linode. This commit adds it back, which fixes dynamic DNS updates for Linode.
> phpDynDNS.inc: Fix missing break statement in switch case for Linode

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
The URL for DynamicDNS updates using GratisDNS was changed at some point.
I have updated to the new URL and testet the update is working again.
Please note, that the code for calculating the domain name for the GratisDNS query is a bit optimistic, and only updates for third level hostnames (e.g. hostname.domain.tld) is supported.
I might pick that up in another PR, if I find the time.
> DynamicDNS GratisDNS URL updated

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
Verify peer and IP resolve have value aside from authentication.  For cases where authentication is not used it can still be desirable to confirm identity and prevent MITM.
> DynDNS Custom Updater: Un-restrict Verify Peer & IPv4 Resolve

- security/maltrail/Makefile
- security/maltrail/pkg-descr
- security/maltrail/src/etc/rc.d/opnsense-maltrailsensor
- security/maltrail/src/etc/rc.d/opnsense-maltrailserver
> security/maltrail: switch python version

- net/wol/src/opnsense/mvc/app/models/OPNsense/Wol/Wol.xml
Took me a while to figure out why the mac address of my computer
wasn't accepted. The added validation message will make it more
clear what's expected.
I have verified that wol will generate identical 'magic' packets
regardless if it is given a mac address with lower, upper or mixed case.
> net/wol: add validation message + support for uppercase hex

- security/acme-client/pkg-descr
Updated Github Web Link to Reflect Github Repository rebrand/rename from: https://github.com/Neilpang/acme.sh to https://github.com/acmesh-official/acme.sh
> Update Github  Link to Reflect Repo rename

- sysutils/nut/src/opnsense/mvc/app/controllers/OPNsense/Nut/forms/settings.xml
The monitoring user created by the NUT plugin is named "monuser". While this can be found in the NUT documentation, it's not evident from the plugin's help text or UI. 
With this small change, the user gets a hint for the correct username. To be consistent, the change also spells out the username for the "admin" user. There might be other approaches but this seemed the most sensible one to have the information available when needed.
> NUT plugin: Specify usernames for admin and monitor users in help text

- dns/unbound-plus/src/opnsense/scripts/OPNsense/Unboundplus/dnsbl.py
Fix for https://github.com/opnsense/plugins/issues/1759
* Restrict download timeout to 5 seconds and 2 retries. Parse only if HTTP response status is 200 OK.
* "Whitelist" (exclude) domains which aren't starting with alphanumeric char causing Unbound not to start.
> Fix issue #1759 - dnsbl.py

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php
This is a small complementary change to [PR-1753](https://github.com/opnsense/plugins/pull/1753). It adds the ability to customise upload name & location of "fullchain.pem", similar to "cert", "key" and "ca" files.
> security/acme-client: Added "fullchain" name-template to model & dialog

- net/haproxy/Makefile
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
**WARNING: The changes to the SSL verification settings may break existing configurations. Please test this change (or review the resulting haproxy.conf) before using it in production!**
- enable SSL verification for a server when "Force SSL" is enabled in the associated health check (#1761)
- use the systems local Root CA Certificates for SSL verification when no CA was selected (#1761)
- fix label of `src_sess_cnt` (#1780)
- fix invalid use of `option httplog` (resolves a warning in config test)
- fix invalid use of `option forwardfor` (resolves a warning in config test)
none
> net/haproxy: release 2.22

- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Additional changes for https://github.com/opnsense/plugins/issues/1779
- added option "--insecure"
- increased maximum dns sleep time
> security/acme-client: add support for dnsapi "Euserv.eu"

- net/wol/src/www/widgets/widgets/wake_on_lan.widget.php
Find mac addresses case-insensitive. When mac addresses are added, they are saved like the users enters them. If the user used upper-case letters, this results in showing the host offline in the dashboard, although it´s online. Other fix would be to make all mac inputs lowercase while saving.
> wake_on_lan widget: find macs case-insensitive

- dns/unbound-plus/src/opnsense/mvc/app/models/OPNsense/Unboundplus/Miscellaneous.xml
CSVListField needs comma for validator, also 46 chars is only one v6 address without shortening.
> dns/unbound-plus: fix DoT validations

- net/shadowsocks/src/opnsense/mvc/app/controllers/OPNsense/Shadowsocks/forms/local.xml
It may be obvious to some, but I think there's some value in making it more explicit that the password required here is for the *remote* `shadowsocks` server and not for a connection to the local proxy. Furthermore, I would suggest moving the password in the form closer to the remove server info, to group them a bit more logically.
I am aware that the `shadowsocks` local config JSON has the same order of the fields as the form currently does, but regrouping makes it clearer in my view what the password is for. And then you could argue somebody who doesn't know what the password is for is probably not "fit" to use `shadowsocks` in the first place anyway.
> Make doc for password more explicit, group options logically 

- dns/unbound-plus/src/opnsense/service/templates/OPNsense/Unboundplus/dot.conf
While 'forward-ssl-upstream' is indeed an alias/alternative syntax for the '*tls*' option, therefore it's more a cosmetic thing - specially because it's called DNS over TLS. Just to be consistent with terms used.
I've paid a look into the configuration file due to some UI validation issues, since then it's annoying me unfortunately - therefore the PR... :)
> unboundplus: Use 'forward-tls-upstream' config key

- security/tinc/src/opnsense/mvc/app/models/OPNsense/Tinc/Tinc.xml
- security/tinc/src/opnsense/scripts/OPNsense/Tinc/lib/objects.py
- security/tinc/src/opnsense/scripts/OPNsense/Tinc/tincd.py
**Background**
What I would like to achieve is a dual-stack ethernet bridge using Tinc (layer 2 VPN). Since it is completely possible using Tinc on Linux, it should be achievable in OPNsense.
**Current situation summary**
**About this PR**
If I change Tinc mode from router (L3VPN) to switch (L2VPN), it wont start properly because irrelevant `subnet` variables are included in host configuration files. Before this commit I cannot leave them empty in OPNsense WebGUI. Commenting out these variables and restarting Tinc daemon from console fixes the problem.
Following [the official manual](https://www.tinc-vpn.org/documentation/tinc.pdf), `subnet` configuration variable seems to be used by Tinc for routing purposes in router mode. Although this field can also be a single MAC address which might …
> security/tinc: Fix switch mode

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
acme.sh contains support for the Acmeproxy provider (https://github.com/acmesh-official/acme.sh/pull/2250), but OPNsense didn't yet support the dialogs which are added with this PR.
> security/acme-client: Add Acmeproxy DNS provider dialog

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
This change is to update nsupdate (RFC 2136) DNS Service for the Let's Encrypt module to support a Zone declaration.  As described in PR#1963 for acme.sh:
> Some DNS servers for which dns_nsupdate.sh is applicable (such as dyn.com's 'Standard DNS' TSIG update mechanism), require that the zone be set during the nsupdate transaction.  Therefore we add a new environment variable NSUPDATE_ZONE which is used to set the zone for the DNS TSIG transaction.
Currently OPNSense is a year and a half behind what acme.sh supports for the nsupdate DNSAPI. See the [acme.sh pull request](https://github.com/acmesh-official/acme.sh/pull/1963) for more detailed information.
> security/acme-client: Add NSUPDATE_ZONE support to nsupdate DNS-01 Service

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
Added core-networks API config options, to fix #1872 
NEEDS TESTING
Pleas advice, how I can test this on my opnsense. I sadly do not have a test environment, hence would need to do that on my live environment. As this is my first PR here, would appreciate some advice on how to do that securely.
> [security/acme-client] Add core-networks API option

- net/wireguard/Makefile
- net/wireguard/pkg-descr
- net/wireguard/src/opnsense/service/conf/actions.d/actions_wireguard.conf
- net/wireguard/src/www/widgets/include/wireguard.inc
- net/wireguard/src/www/widgets/widgets/wireguard.widget.php
Adds a widget for WireGuard.
Relates #1862.
> net/wireguard: Add dashboard widget

- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
The Telegraf flush_interval option is not working correctly. The option was not being added to the telegraf.conf file. Add the missing flush_interval option to the template to fix this problem.
> Telegraf: fix flush_interval option

- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
This PR fixes #1821 .
- Add new checkbox that enables TLS:
Only if that checkbox is set, verification is evaluated. 
As soon as  insecure_skip_verify = {true | false} is in the Telegraf config file, Telegraf will connect to Graphite using TLS.
> net-mgmt/telegraf: Fix TLS connect (#1821)

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns.inc
- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
- dns/dyndns/src/www/services_dyndns_edit.php
Based on the following documentation https://developer.godaddy.com/
This adds basic support for GoDaddy DynDNS REST API.
I could test the following :
- A record
- AAAA record
- Invalid and Valid tokens produce the correct output in logs
- Incorrect domain name produce the correct output in logs
More error messages and features could be handled as the API is richer than what I handled here, but this is a start
> Add GoDaddy DynDNS API support

- net-mgmt/collectd/src/opnsense/mvc/app/controllers/OPNsense/Collectd/forms/general.xml
- net-mgmt/collectd/src/opnsense/mvc/app/models/OPNsense/Collectd/General.xml
- net-mgmt/collectd/src/opnsense/service/templates/OPNsense/Collectd/collectd.conf
https://github.com/opnsense/plugins/issues/1758
Implemented the aggregate values for CPU and the "separate instances" feature.
Added "disk" (disk i/o) and "swap" plugins.
I need to research why the "cputemp" plugin is not available in the package version used by OPNsense.
> Add support for aggregation and Graphite Separate Instances to Collectd plugin, add 2 plugins to collectd

- mail/postfix/src/etc/inc/plugins.inc.d/postfix.inc
Missed this one, mentioned by @AdSchellevis 
Changing remote => mail to postfix *may* break syslog filter for graylog or ELK, but I think for a major this is ok-ish
> mail/postfix: quick fix syslog

- security/acme-client/Makefile
- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
This PR adds support for `dns_1984Hosting` API.
> acme-client: add support for 1984Hosting API

- net/frr/Makefile
- net/frr/pkg-descr
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Without eBGP filters no prefixes are exchanged without a policy.
To not break too many setups disable globally
https://github.com/FRRouting/frr/issues/6843
https://forum.opnsense.org/index.php?topic=18379.0
> net/frr: Disable eBGP policies

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/certhelper.php
This PR adds support for the Joker API DNS validation via `dns_joker.sh`. Note that `dns_joker.sh` doesn't exist yet in the current `acme.sh` package version, 2.8.6. However, due to #1946 that script should soon be part of the `acme.sh` package.
I've verified that my modification works with a manually-installed `dns_joker.sh`.
I have read the contributing guidelines.
> acme-client: add support for Joker API DNS validation

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Add ntpq input
**Unbound:**
I would also like to add unbound input. See: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/unbound
Unfortunately the telegraf user don't has all required permissions for that.
```
:~ # sudo -u telegraf unbound-control -c /var/unbound/unbound.conf stats_noreset
/var/unbound/unbound.conf:121: error: cannot open include file '/var/unbound/etc/*.conf': Permission denied
read /var/unbound/unbound.conf failed: 1 errors in configuration file
[1596929270] unbound-control[24137:0] fatal error: could not read config file
```
Is it possible to change the permissions of the folder `/var/unbound/etc` so telegraf can load the config file?
> net-mgmt/telegraf: Add ntpq input

- dns/dnscrypt-proxy/src/opnsense/scripts/OPNsense/Dnscryptproxy/dnsbl.sh
blocklistproject sites are formatted in two columns, the first column is
0.0.0.0 and the second column is the domain to block.  Added an awk to
just get the list of blocklistproject sites, otherwise the result is just 0.0.0.0
> Dnscryptproxy dnsbl.sh helper script fix for blocklistproject sites

- net/wireguard/Makefile
- net/wireguard/pkg-descr
- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
RFC 952 allows the hyphen or minus sign (-) to be a valid hostname character. The WireGuard Client configuration should allow the same. This change has had limited testing with no negative impact.
http://en.wikipedia.org/wiki/Hostname
The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.
> Allow hyphen / minus sign (-) as a valid hostname character

- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAccount.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCertificate.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeUtils.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/Base.php
As discussed in https://github.com/opnsense/plugins/pull/2028 I've made the following changes:
* Use `exec_safe()` in more places to prevent shell command injection.
* Drop dependency on legacy `util.inc` by including a copy of the required function in `LeUtils.php`
Granted, the latter one is not great, because it duplicates code. I think this is still better than depending on the legacy codebase in many places.
When the core team decides to move `exec_safe()` to the new codebase then I'll gladly remove the copy from the LE plugin.
> security/acme-client: post merge fixes for version 2.0

- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-ldap
Add NT-Password entry for FreeIPA compatibility.
FreeIPA requires control:NT-Password   := 'ipaNTHash'
> Update mods-enabled-ldap for compatibility with FreeIPA

- net/freeradius/Makefile
- net/freeradius/pkg-descr
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/eap.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/+TARGETS
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/sites-enabled-check-eap-tls
Add support for TLS and implement common name checking on certificates. Allow additional characters in the usernames, since those are required for this use-case
> Freeradius TLS

- sysutils/hw-probe/src/opnsense/service/conf/actions.d/actions_hwprobe.conf
Future versions will prevent execution without parameters.
> sysutils/hw-probe: add full parameters to configd call

- net/chrony/Makefile
- net/chrony/pkg-descr
- net/chrony/src/opnsense/mvc/app/controllers/OPNsense/Chrony/forms/general.xml
- net/chrony/src/opnsense/mvc/app/models/OPNsense/Chrony/General.xml
- net/chrony/src/opnsense/scripts/OPNsense/Chrony/setup.sh
- net/chrony/src/opnsense/service/templates/OPNsense/Chrony/chrony.conf
Add NTS for peers to chrony which was introduced in 4.0
https://blog.apnic.net/2019/11/08/network-time-security-new-ntp-authentication-mechanism/
> net/chrony: add NTS peer mode

- security/tinc/src/opnsense/mvc/app/controllers/OPNsense/Tinc/forms/dialogHost.xml
- security/tinc/src/opnsense/mvc/app/controllers/OPNsense/Tinc/forms/dialogNetwork.xml
- security/tinc/src/opnsense/mvc/app/models/OPNsense/Tinc/Tinc.xml
- security/tinc/src/opnsense/scripts/OPNsense/Tinc/lib/objects.py
All three situations are legit, both for local and remote hosts.
> [security/tinc] Enable usage of no, one or several addresses per hosts

- security/acme-client/Makefile
- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNsupdate.php
This release fixes the dns_nsupdate challenge type.
> security/acme-client: release 2.1

- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap
As discussed in #2085
Creates a option to set freeradius to use EAP-TTLS-GTC.
This can, for example, be used to connect to LDAP databases with hashed passwords.
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>
> [Freeradius] Create option to set EAP-TTLS-GTC for FreeRadius

- security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf
Sensor now starts even with local server disabled.
> FIX - Sensor not starting without server enabled

- security/tinc/src/opnsense/scripts/OPNsense/Tinc/lib/objects.py
In switch mode the subnet field is empty, thus the 'subnet' key does not exist in the '_payload' dictionary. This PR fixes switch mode after #2110.
> security/tinc: Fix switch mode (again)

- security/tinc/src/opnsense/mvc/app/models/OPNsense/Tinc/Tinc.xml
The IpAllowed flag should be 'Y', since any different value is recognized as 'N' ([reference](https://github.com/opnsense/core/blob/de291e62660996b04d589381cad3396db5e9eb80/src/opnsense/mvc/app/models/OPNsense/Base/FieldTypes/HostnameField.php#L70)). This PR fixes external address fields in Tinc configuration not accepting IPv6 addresses after #2110. Closes #2184.
> security/tinc: Fix extaddress field validation

- sysutils/smart/src/opnsense/service/conf/actions.d/actions_smart.conf
The "description" fields were removed to not flood the UI with duplicate
items but some of them are actually useful for cron.
Descriptions for actions related to tests were re-added with unique
content to enable periodic SMART tests via cron.
> os-smart: Re-add descriptions for cron actions

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Many months ago I discovered that Telegraf's ping input plugin doesn't work for IPv6 on OPNsense (and FreeBSD in general).
I fixed the general FreeBSD problems in [this pull request](https://github.com/influxdata/telegraf/pull/7861) for Telegraf, which is included since release 1.15.3.
OPNsense also needs some changes to make use of the fixed Telegraf.
Added another checkbox to enable a second instance of the ping input for IPv6, and a list box where one can specify the IPv6 hosts, to the GUI.
This second instance has `binary = "ping6"` set in `telegraf.conf`.
Both the IPv4 and the IPv6 instances also explicitly set `method = "exec"`, since there's a chance that the ping input plugin will move to `method = "native"` in the future, which wouldn't work without changes (if at all?) on …
> net-mgmt/telegraf: Add ping6 input

- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Client.xml
Adding a peer with a wrong public key format to a tunnel configuration makes the wall tunnel hang silently when trying to save configuration (and then restart the service). This should prevent wrong configuration but some checks may be done server side to, at least, log some error and display some warning.
> Check wg-public key format

- net/wireguard/src/www/widgets/widgets/wireguard.widget.php
This change shows each latest handshake time in the WireGuard widget in the timezone of the system, rather than UTC as currently. The change is intended to implement this forum request: https://forum.opnsense.org/index.php?topic=20530.msg95463#msg95463.
As a disclaimer, I am by no means a PHP programmer, but this commit is based on my research. It works when I tested it.
> Show WG widget timestamps in system timezone

- www/nginx/src/opnsense/scripts/nginx/setup.php
Hi. just quick fix for troubles with trust_upstream_*.pem files after update to 1.20 with upstream tls verify enabled and trusted CAs selected
> www/nginx: quick fix for trusted CAs pem

- mail/postfix/Makefile
- mail/postfix/pkg-descr
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/antispam.xml
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/Antispam.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
- mail/rspamd/Makefile
- mail/rspamd/pkg-descr
- mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/+TARGETS
- mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/worker-normal.inc
- mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/worker-proxy.inc
Issue #1591 concerning duplicate E-Mails was not fixed, because it was anticipated that Postfix 'milter_protocol' version would specify the IP version. Instead this specifies the [version of Sendmail's Milter Protocol](http://www.postfix.org/postconf.5.html#milter_protocol), which in Postfix+Rspamd's case should always be version 6.
To really fix the issue I have set Postfix', Rspamd Proxy's and Rspamd Worker's Connection to Unix Sockets. Because in OPNsense Postfix and Rspamd are set up to run on the same host, there is really no need to use TCP-Connections, which makes this the most ideal solution. 
```
Postfix ---/var/run/rspamd/milter.sock---> Rspamd Proxy Worker ---/var/run/rspamd/normal.sock---> Rspamd Normal Worker 
```
At the moment, if Rspamd becomes unavailable to Postfix, …
> mail/postfix: Duplicate Message Fix, Milter Default Action Choice and Recipient Address Verification

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
When updating an apex domain (like mydomain.com) it fails as the domain sent to gratisdns becomes just com. Both hostname and domain should in this case be mydomain.com. The current logic is based on updating a subname like www.mydomain.com in which case the domain part becomes correctly mydomain.com.
> Added fix for updating apex domains (mydomain.com) with gratisdns

- www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
This PR addresses a CPU consumption issues I have with "`ngx_autoblock.php`". The script dominates the top process list, it consumes more CPU than all other processes and it runs for almost 30 seconds (every minute).
* Latest Opnsense on Intel quad core.
* ~**955** banned IP addresses (collected over time in ~1 year)
* Average load 1.3 (prior) and 0.8 (after applying the changes)
**Original "`ngx_autoblock.php`" (24 seconds +- 3)**: 
```.sh
time /usr/local/opnsense/scripts/nginx/ngx_autoblock.php
7.557u 16.446s 0:24.03 99.8%	4390+1547k 0+0io 0pf+0w
```
**Updated "`ngx_autoblock.php`"**:
| Condition                      | Time results  |
| ---------------------  |:-------------:|
| Regular schedule with no changes | 0.690u 0.839s 0:01.55 |
| Every 10 minutes, no changes | 4.047u 5.147s …
> Nginx: Refactored "ngx_autoblock" to reduce cpu consumption

- net/haproxy/Makefile
- net/haproxy/pkg-descr
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/ExportController.php
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/Api/SettingsController.php
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/ExportController.php
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/IndexController.php
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAcl.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMailer.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMapfile.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogServer.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalSettings.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Menu/Menu.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/Migrations/M3_0_0.php
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/export.volt
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/maintenance.volt
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/statistics.volt
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/exportCerts.php
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/setup.sh
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/socketCommand.py
- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/updateOcsp.sh
- net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/+TARGETS
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/rc.conf.d
Main achievements in this release:
See plugin changelog for a complete list of changes and new features.
> net/haproxy: release 3.0

- security/stunnel/src/opnsense/mvc/app/controllers/OPNsense/Stunnel/forms/dialogService.xml
- security/stunnel/src/opnsense/mvc/app/models/OPNsense/Stunnel/Stunnel.xml
- security/stunnel/src/opnsense/service/templates/OPNsense/Stunnel/stunnel.conf
I need to connect to an LDAP server using stunnel client mode.
In the services form, there is no option to enable client mode.
This adds a checkbox to enable client mode in the service creation/edit form.
When the checkbox is enabled, the option
`client = yes`
is added to relative service config.
> security/stunnel: Add client mode option to services

- sysutils/smart/src/opnsense/mvc/app/controllers/OPNsense/Smart/Api/ServiceController.php
- sysutils/smart/src/opnsense/service/conf/actions.d/actions_smart.conf
os-smart: Add new action and API parameter for JSON info from smartctl.
- The existing `smart info.*` actions have been merged into one `smart info`
action that takes the type as a parameter.
- There is now a `smart info_json` action that runs the same `smartctl` command
with an additional `--json=c` parameter for JSON output.
- The `/api/smart/service/info` API now takes an optional `"json": true`
request body parameter that changes the response `"output"` value from
a string to a JSON object. The JSON object is the output of
the `smart info_json` action.
Fixes #2283
> os-smart: Add new action and API parameter for JSON info from smartctl.

- emulators/qemu-guest-agent/Makefile
- emulators/qemu-guest-agent/pkg-descr
- emulators/qemu-guest-agent/src/etc/inc/plugins.inc.d/qemuguestagent.inc
- emulators/qemu-guest-agent/src/opnsense/mvc/app/controllers/OPNsense/QemuGuestAgent/Api/ServiceController.php
- emulators/qemu-guest-agent/src/opnsense/mvc/app/controllers/OPNsense/QemuGuestAgent/Api/SettingsController.php
- emulators/qemu-guest-agent/src/opnsense/mvc/app/controllers/OPNsense/QemuGuestAgent/IndexController.php
- emulators/qemu-guest-agent/src/opnsense/mvc/app/controllers/OPNsense/QemuGuestAgent/forms/general.xml
- emulators/qemu-guest-agent/src/opnsense/mvc/app/models/OPNsense/QemuGuestAgent/ACL/ACL.xml
- emulators/qemu-guest-agent/src/opnsense/mvc/app/models/OPNsense/QemuGuestAgent/Menu/Menu.xml
- emulators/qemu-guest-agent/src/opnsense/mvc/app/models/OPNsense/QemuGuestAgent/QemuGuestAgent.php
- emulators/qemu-guest-agent/src/opnsense/mvc/app/models/OPNsense/QemuGuestAgent/QemuGuestAgent.xml
- emulators/qemu-guest-agent/src/opnsense/mvc/app/views/OPNsense/QemuGuestAgent/index.volt
- emulators/qemu-guest-agent/src/opnsense/scripts/OPNsense/QemuGuestAgent/setup.sh
- emulators/qemu-guest-agent/src/opnsense/service/conf/actions.d/actions_qemuguestagent.conf
- emulators/qemu-guest-agent/src/opnsense/service/templates/OPNsense/QemuGuestAgent/+TARGETS
- emulators/qemu-guest-agent/src/opnsense/service/templates/OPNsense/QemuGuestAgent/rc.conf.d
> add new plugin: emulators/qemu-guest-agent

- README.md
- sysutils/munin-node/Makefile
No revision bump since this is a minor non-functional typo.
> sysutils/munin-node: fix description typo.

- security/maltrail/src/opnsense/service/conf/actions.d/actions_maltrailsensor.conf
Maltrail sensor is a memory hog (or it might leak memory), if I don't restart it every few days it crashes with OOM or worst case it takes suricata and/or ntopng with it as well. The commit makes the Maltrail sensor restart option visible under webGUI's cron settings to make restarting convenient.
> Allow maltrail sensor periodic restart from webGUI

- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
Some applications as Keycloak when running behind Nginx proxy need these flags configured 
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Host $host;
This cause no impact in other applications already configured, at least for my applications
> www/nginx: Add X-Forwarded-Port and  X-Forwarded-Host headers

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/naxsi_rule.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Base/Constraints/NaxsiIdentifierConstraint.php
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/naxsirule.conf
Naxsi whitelist configuration has some drawbacks as elaborated in #2151. Here some improvements:
- Allow specifying multiple IDs for whitelist rules
- The user can specify _1,2,3_ to whitelist rule IDs 1, 2 and 3 with one single whitelist entry.
- The user can specify _-1,-2,-3_ to whitelist all rules except rules 1, 2 and 3.
- Improvement in config generation
- `wl:` rules do not take any `msg:` nor `rx:` or `str:` parts (as these parts are not specified in [Naxsi whitelist documentation](https://github.com/nbs-system/naxsi/wiki/whitelists-bnf)).
- `id:` rules always generate `rx:` or `str:`. Previous implementation allowed generation of `id:` rules without actual value. I do not see any valid use-case for these.
- Add help texts for Rule Type and Match Type attributes in the UI
> www/nginx: Naxsi whitelist improvements

- www/nginx/src/opnsense/scripts/nginx/setup.php
If a CA Certificate for an stream server was selected the CA was saved with the last hostname set from the forearch loop of the HTTP Servers in the block above!
> www/nginx: Fix wrong stream server ca filename

- www/nginx/src/opnsense/scripts/nginx/setup.php
Hi!
minor fixes for setup.php script
- get rid of the "PHP Warning: Use of undefined constant 'next'" message in reporter
- make streams block work for single stream server in config (correctly identify the case of a single server)
> www/nginx: setup.php minor fixes

- net/freeradius/src/opnsense/scripts/systemhealth/logformats/freeradius.py
The freeradius logformat has days without a leading zero. (1,2,3,...)
This breaks the regex added by... myself.
**Original PR:** https://github.com/opnsense/plugins/pull/1705
**Before:**
**After:**
> net/freeradius: Fix leading space in freeradius logformat

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
- dns/dyndns/src/www/services_dyndns_edit.php
Current implementation of FreeDNS update in DynDNS plugin is broken.
DynDNS changed its interface and switched to "v2".
The URL in current implementation getting response `PAYLOAD: ERROR: Invalid update URL (2)`
This PR fixes endpoint, documentation and expected responses to make it work.
Logs are backwards. Also includes piece of log "before". IP/DNS are sanitized.
```
/usr/local/etc/rc.dyndns: Dynamic DNS (abcd.mooo.com): (Success) No Change In IP Address
/usr/local/etc/rc.dyndns: Dynamic DNS: updating cache file /var/cache/dyndns_wan_abcd.mooo.com_2.cache: A.B.C.D
/usr/local/etc/rc.dyndns: Dynamic DNS (abcd.mooo.com): A.B.C.D extracted
/usr/local/etc/rc.dyndns: Dynamic DNS (abcd.mooo.com): Current Service: freedns
/usr/local/etc/rc.dyndns: Dynamic DNS (abcd.mooo.com): _checkStatus() …
```
> Fix FreeDNS update in DynDNS plugin

- net/frr/Makefile
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/general.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/General.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/zebra.conf
I need agentx support in order to gather BGP details via SNMP.  All of the software is built, and only the UI and config files need a change. 
This works for me, and it only changes templates and adds a field for Net-SNMP and Frr.
> net/frr: Add support for agentx

- emulators/qemu-guest-agent/Makefile
I did another test of the -devel version on 21.1.5 and it works as expected – at least for me :)
So let's finally release this thing.
> emulators/qemu-guest-agent: release initial version

- www/nginx/src/opnsense/scripts/nginx/csp_report.php
Chrome and Firefox report CSP as application/csp-report and not application/json. This lead to HTTP 400 BAD REQUEST.
No csp logs were created. With this fix, the form is csp report is processed and written to logs.
> Fixed expected mime-type

- net/wireguard/Makefile
- net/wireguard/pkg-descr
- net/wireguard/src/opnsense/mvc/app/models/OPNsense/Wireguard/Server.xml
- net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
Tunnel addresses are only needed if wireguard peers need to talk directly to one another over the VPN. In a site-to-site configuration it is perfectly valid to not assign a wireguard interface address and just issue appropriate ranges for AllowedIPs at each end. When configured this way, wireguard is smart enough to handle the routing internally and everything works fine.
The proposed change makes the tunneladdress parameter optional in the web interface, and provides the appropriate if statement in the configuration file generator.
Tested and working with my own site-to-site VPN.
> net/wireguard: Make tunneladdress an optional parameter

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
The if statements were out of order in the telegraf.conf file and this feature was using the output the model instead of the input model
>  net-mgmt/telegraf: fixed #2369 if statements in wrong spot and wrong model form

- mail/postfix/Makefile
- mail/postfix/pkg-descr
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
The default TLS client/ server configurations of `mail/postfix` are not really up to the best practices anymore.
Therefore I have added three compatibility modes:
* Old
* Intermediate
* Modern
for both `smtpd` (server) and `smtp` (client). I configured those different compatibility levels according to [Mozilla's TLS configuration recommendations](https://ssl-config.mozilla.org/#server=postfix) for Postfix.
With those, the user is easily able to choose between different compatibility levels depending on particular requirements/ philosophy regarding backwards compatibility. 
The results for different compatibility levels for `smtpd` look quite promising: 
<details>
<summary>Old compatibility</summary>
<p>
```
$ sslyze --starttls=smtp opnsense.local:25
CHECKING HOST(S) AVAILABILITY …
```
> mail/postfix: Add TLS compatibility modes

- net/freeradius/Makefile
- net/freeradius/pkg-descr
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap
With FreeRADIUS 3.0.22 the TLS minimum version has been changed to TLS 1.2. However older Android devices do not support that version for EAP authentication. 
Also update the file (especially the comments) to match the upstream version.
> net/freeradius: Update comments and reduce min TLS version. Fixes #2434

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsNjalla.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Njalla is integrated in acme.sh. This PR adds support in the interface.
> security/acme-client: Add support for Njalla DNS API

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpUploader.php
Fixes a problem in the sftp upload automation that a re-deployment of certificates with permissions set to readonly (= default) fail on SSH/SFTP servers that return file owners of existing files as numeric values.
The failure is caused by the fact that the detection whether the connecting user owns an existing cert file on the remote location currently does not work when the SSH server returns the owner as numeric value. Without ownership detection, the upload automation will not attempt to remove the readonly flag from existing files and will fail to overwrite certs (in this case only the initial upload works).
As a workaround the automation can be configured to leave cert file uploads writable, which is not a good option.
> security/acme-client: Fix sftp re-deployment of readonly certs

- net/freeradius/Makefile
- net/freeradius/pkg-descr
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Client.xml
It seems the current model parses the client IP as a HostnameField, meaning it fails validation if the user attempts to use a CIDR. 
A NetworkField seems to correct that.
> net/FreeRADIUS: Fix issue with being unable to specify a CIDR

- net-mgmt/zabbix-agent/src/opnsense/mvc/app/controllers/OPNsense/ZabbixAgent/forms/settings.xml
- net-mgmt/zabbix-agent/src/opnsense/mvc/app/models/OPNsense/ZabbixAgent/ZabbixAgent.xml
- net-mgmt/zabbix-agent/src/opnsense/service/templates/OPNsense/ZabbixAgent/zabbix_agentd.conf
Add option to switch Zabbix Agent logging between syslog and (current) logging to file, per #2332
I'm not sure if I've covered all the places this type of simple option change would appear. Please let me know if I should look anywhere else.
> net-mgmt/zabbix-agent: add syslog option

- mail/postfix/Makefile
- mail/postfix/pkg-descr
- mail/postfix/src/opnsense/mvc/app/controllers/OPNsense/Postfix/forms/general.xml
- mail/postfix/src/opnsense/mvc/app/models/OPNsense/Postfix/General.xml
- mail/postfix/src/opnsense/service/templates/OPNsense/Postfix/main.cf
At least my users prefer to receive a notification if a mail stays in the queue for an extended amount of time. Make that parameter configurable instead of forcing the default (disabled).
> mail/postfix: make `delay_warning_time` configurable

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/ServiceController.php
- www/nginx/src/opnsense/service/conf/actions.d/actions_nginx.conf
It seems that the reload option is better than the stop option, because stop action stop WebRTC communication. I have configured the reload option in another pull request.
> Replace stop action by the reload option in reconfigureForceRestart

- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/lib/haproxy/cmds.py
See: https://github.com/python/cpython/pull/8014
> use OrderDict because csv.DictReader returns a dict after version 3.7

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
Also add one comment to explain that the CN also becomes the first `subjectAltName` to clarify that a certificate will never be generated without `subjectAltName` (which would make it invalid by 2021 standards)
Fixes: #2526
> Update LE reference to ACME (#2526)

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/general.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf
> net-mgmt/telegraf: Allow Run as Root

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
- dns/dyndns/src/www/services_dyndns_edit.php
Adds https://desec.io wildcard support - see #2482
This is my first PR; I will happely incorporate any feedback.
Also note that I didn't packaged and tested the changes (as I still need to figure that out) - so I only validated the desec-API call via the https://insomnia.rest app.
Closes #2482.
> dns/dyndns: add desec.io wildcard support

- net/vnstat/Makefile
- net/vnstat/pkg-descr
- net/vnstat/src/opnsense/mvc/app/controllers/OPNsense/Vnstat/Api/ServiceController.php
- net/vnstat/src/opnsense/mvc/app/views/OPNsense/Vnstat/general.volt
- net/vnstat/src/opnsense/service/conf/actions.d/actions_vnstat.conf
currently the vnstat service offers hourly/daily/monthly - vnstat tracks yearly too so why not.
marking as draft for now as i don't have a machine spare to test this on, might be a few days.
> net/vnstat: added yearly table to vnstat service

- net/haproxy/src/etc/inc/plugins.inc.d/haproxy.inc
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/+TARGETS
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/log_socket.conf
Hi
for discussion on https://github.com/opnsense/plugins/issues/2587#issuecomment-954598043
drop 'local'
add log socket
if i'm not mistaken this can be applied as a patch without waiting for the https://github.com/opnsense/core/commit/a763313d138258b0044c3285de0e8ac55d308160
Thanks!
> net/haproxy: add syslog-ng socket

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
- dns/dyndns/src/www/services_dyndns_edit.php
Added a Error Log for failed updates - aligning with the rest of the Dynamic DNS Providers
Added the ability to replace the %Host% in the Configured update URL
> dns/dyndns: customDns log error details & inject %Host%

- net/freeradius/pkg-descr
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/eap.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/mods-enabled-eap
Insecure but most compatible default with a security warning.
> net/freeradius: Allow setting of minimum TLS version

- net/frr/Makefile
- net/frr/pkg-descr
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPPrefixLists.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Fixes: #2602, #2604, #2606, #2623
For anyone interested in testing, here's the issues I believe are fixed, how to test them in the UI, and what they should look like in `/usr/local/etc/frr/bgpd.conf`:
| Web UI | `bgpd.conf`|
|---------|-------------|
| IPv6 prefix list protocol/action fields are no longer multi-selectable (#2602) | |
| Configure an IPv6 prefix list with the target `any` (#2602) | Appears in the config file as an `ipv6 prefix-list` **not** `ip prefix-list` |
| Configure an IPv6 neighbor with a link-local interface (using the **advanced mode** dropdown) (#2604) | Neighbor appears with `neighbor <address> interface <interface>` |
| Setting `Update-Source` on an IPv6 neighbor does nothing | Neighbor does **not** appear with `neighbor <address> update-source <interface>`|
| …
> net/frr: Multiple fixes/features

- net-mgmt/zabbix-proxy/Makefile
- net-mgmt/zabbix-proxy/pkg-descr
- net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf.in
Changes in this PR:
* Fix upgrade path by using a new db file for each version (#1943)
* Add plugin variant for Zabbix Proxy 5.4 (depends on https://github.com/opnsense/tools/pull/252)
@mimugmail, please review :)
> net-mgmt/zabbix-proxy: release 1.6

- dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc
added digitalocean-v6 to switch, it was missing and returning error 6 'Dynamic DNS: (ERROR!) The Dynamic DNS Service provided is not yet supported.'
> Fix for digitalocean-v6

- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindDomain.xml
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Domain.xml
- dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
This allows you to add a TSIG key to your secondary zones so the primary can authenticate your request.
> dns/bind: allow signed zone transfers

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeUnifi.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
@fraenki I don't know if this is acceptable to you (regarding the unsupported remark here https://github.com/opnsense/plugins/issues/2627#issuecomment-967663228)
I tested this deployment hook using https://github.com/mimugmail/opn-repo/tree/main/net-mgmt/unifi-maxit
> Added (local)Unifi to ACME actions

- net/freeradius/Makefile
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
Got a couple of reports that starting FR failes. 
When applying on EAP correct default is set and daemon starts.
> net/freeradius: Fix bad default

- net/freeradius/src/opnsense/service/conf/actions.d/actions_freeradius.conf
Add description for restart action so it can be used in automations (e.g. after acme cert update, restart freeradius which uses it)
>  net/freeradius: add description for restart action

- net/frr/src/opnsense/service/conf/actions.d/actions_quagga.conf
didn't seem to cause any trouble, but my editor noticed it
> net/frr: replace U+00A0 with an actual space

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsCpanel.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
This adds support for the cPanel API to the plugin already included into acme.sh https://github.com/acmesh-official/acme.sh/wiki/dnsapi#136-use-cpanel-dns-systems
> security/acme-client: add support for cPanel HTTP API

- www/nginx/Makefile
- www/nginx/README.md
- www/nginx/pkg-descr
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/Api/SettingsController.php
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/security_headers.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/tabbed_dialog.volt
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/security_rule.conf
The security header edit dialog contains many fields and a tabbed interface for the dialog itself allows better configuration of the headers. Parameter names can be shorted when having a tabbed interface.
Also the grid view lacks columns to have an overview of the rules (is HSTS enabled? is CSP enabled? etc.)
This PR reworks the security header grid, the add/edit form and also adds two new header directives:
* The CSP _frame-ancestors_ and _frame-src_ is added.
* The HSTS _preload_ directive is added.
New dialog:
New grid:
> www/nginx: Rework security header forms and adding CSP frame-ancestors and HSTS preload directives

- net/wol/src/opnsense/service/conf/actions.d/actions_wol.conf
Without a description the wol action cannot be used to create a cron job via the OPNsense web gui. Therefore I added one. To add a cron job triggering a wol packet, one has to add the broadcast IP address and MAC address of the target network and host as parameters for the cron job.
This addresses https://github.com/opnsense/core/issues/873
> Add description and message to wol action

- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Migrations/M1_24_0.php
Hi!
Imho  there are problems updating nginx plugin to 1.24.0 version.
(nginx refuses to load, multiple errors in logs).
ref. https://forum.opnsense.org/index.php?topic=26266.0 https://forum.opnsense.org/index.php?topic=25830.0
in my experience: after an update, all servers are assigned a default listening address. if I understand correctly, since there are no `listen_http_port`, `listen_https_port` and `listen_port` fields in the new model there is no port-to-address conversion at
https://github.com/opnsense/plugins/blob/01fb8a8abbb220c1bbcee437fa099f08e8a68889/www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Migrations/M1_24_0.php#L38
PR  reads the config, take the current fields values from there and use it in port-to-address conversion
> www/nginx: 1.24.0 migration fix

- net/haproxy/Makefile
- net/haproxy/pkg-descr
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogAction.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogBackend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogFrontend.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogMapfile.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/dialogResolver.xml
- net/haproxy/src/opnsense/mvc/app/controllers/OPNsense/HAProxy/forms/generalTuning.xml
- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
- net/haproxy/src/opnsense/mvc/app/views/OPNsense/HAProxy/index.volt
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
See plugin changelog for details.
**NOTE: This release is intended for OPNsense 22.1, it should NOT be merged to previous releases due to the possibility of breaking changes.**
> net/haproxy: Release 3.10

- net/frr/Makefile
- net/frr/pkg-descr
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/RIP.xml
Migration errors on every update ... 
```
Starting configd.
>>> Invoking update script 'refresh'
*** OPNsense\Quagga\OSPF6 Migration failed, check log for details
*** OPNsense\Quagga\RIP Migration failed, check log for details
```
Router ID on OSPF6 is not a requirement and RIP would need a network to run, but I'd guess noone uses it anymore and ppl using it have a network in there, otherwise it wont work :)
> net/frr: Dont set empty defaults on required fields

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
I created this small tweak, so the new ddclient plugin works with STRATO. It should work, although I have not tested it yet. (not upgraded to 22.1 yet). 
EDIT:
I´m not really sure if `use=web` without a `web=address` is sufficient.
If not maybe consider https://ipinfo.io/ip for lookup as STRATO has no external IP checkup site.
> Add STRATO DynDNS functionality to the new ddclient-dyndns plugin.

- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
Added Cloudflare
had to add an additional config option for the zone. I hope that's the right way. Is it possible to make that field required only for cloudflare?
fixes #2772
> dns/ddclient Add Cloudflare

- dns/dnscrypt-proxy/pkg-descr
- dns/dnscrypt-proxy/src/opnsense/service/templates/OPNsense/Dnscryptproxy/dnscrypt-proxy.toml
Fixed function of "Disabled Servers List" when more than one server specified in the list.
> dns/dnscrypt-proxy: fixed "disabled_server_names"

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
HE is using the dyndns2 protocol for both dynamic DNS and IPv6 TunnelBroker services. Add both services to the service.
Added provider was tested to verify that both services are updating successfully.
> dns/ddclient - Add Hurricane Electric provider

- mail/rspamd/Makefile
- mail/rspamd/pkg-descr
- mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/multimap.conf
If it says "reject", the multimap whitelist is ignored and whitelisted domains are still getting blocked.
If you give it a Score of 1000 blocking still works.
Whitelisted senders are getting -1000 so that they can pass,
Destroyed the old one:
https://github.com/opnsense/plugins/pull/2819
> make multimap Whitelist work

- security/stunnel/src/opnsense/service/templates/OPNsense/Stunnel/stunnel.conf
The current code generates conf line:
```
connect = [::1]:53
```
will end up producing the following:
```
Error resolving "[::1]": Neither nodename nor servname known (EAI_NONAME)
```
stunnel(8) states that an address parameter of an option may be either:
> ...
> A colon-separated pair of IP address (either IPv4, IPv6, or domain name)
and port number.
> ...
which means there should not be special treatment on IPv6 addresses.
> security/stunnel: Fix connect format for IPv6 addresses

- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/sites-enabled-inner-tunnel
Not sure if it's correct but I could make the plugin work for me with this change.
Error in backend log was
> Inline action failed with OPNsense/Freeradius OPNsense/Freeradius/sites-enabled-inner-tunnel 'collections.OrderedDict object' has no attribute 'ldap' at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/template.py", line 267, in _generate content = j2_page.render(cnf_data) File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render self.environment.handle_exception() File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception raise rewrite_traceback_stack(source=source) File "/usr/local/opnsense/service/modules/../templates/OPNsense/Freeradius/sites-enabled-inner-tunnel", line 159, in …
> net/freeradius: Fix template for sites-enabled-inner-tunnel

- dns/ddclient/pkg-descr
- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/settings.xml
- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
This is a pull request to integrate the fix for https://github.com/opnsense/plugins/issues/2895.
There is a new advanced general option to allow updates via IPv6.
I think that the new setting is backward-compatible so that no migration needs to be done. After all, the version for the settings is still 1.2.0 despite the version is 1.3 already.
> New DynDNS option to allow IPv6 updates (issue 2895)

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsAcmedns.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/Migrations/M3_3_0.php
This PR fixes the use of a self hosted ACME-DNS service after the following change https://github.com/acmesh-official/acme.sh/commit/2ce145f359deaaaff9bea06312984c70a04ef87c.
The env var `ACMEDNS_UPDATE_URL` is no longer accepted. `acme.sh` requires `ACMEDNS_BASE_URL` now, since it can also auto-register with the service.
> security/acme-client: ACMEDNS_UPDATE_URL to ACMEDNS_BASE_URL

- net/frr/pkg-descr
- net/frr/src/etc/rc.carp_service_status.d/carp_frr_ospf6
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPF6Interface.xml
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/ospf6.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnosticsbgp.volt
- net/frr/src/opnsense/scripts/frr/lib/events/ospf6d.py
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/+TARGETS
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/frr
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d_carp.conf
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/syslog-ng-frr-events.conf
Implements https://github.com/opnsense/plugins/issues/2923 
Add event handler for ospf6 carp demotion including required interface fields (carp_depend_on and cost_demoted) and implement "CARP demote" for IPv6 as well to bring HA features on par with OSPF.   
While here polish some small usability issues, knowing:
o Interface networktype and interfacename should be single dropdown boxes
o diagnostics / bgp - fix search in grid, should only use a formatter for presentation purposes.
> FRR: OSPF ipv6 influence interface cost via carp

- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindDomain.xml
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Domain.xml
- dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
This resolves #2873 by getting a key name from the user. The key is also specified in the `masters` section, so a separate `server` block is not needed (incidentally this also allows different keys on the same server.)
Not sure how one would handle keys with the same name on different servers. Seems like an edge case not worth worrying about ATM.
> Avoid errors with repeated primary servers and keys

- net-mgmt/zabbix-proxy/Makefile
- net-mgmt/zabbix-proxy/pkg-descr
- net-mgmt/zabbix-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
- net-mgmt/zabbix-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml
- net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf.in
This to add Enable Remote Commands to Zabbix Proxy on GUI.
Instead of agent that EnableRemoteCommands is deprecated, on Proxy configuration EnableRemoteCommands is alway valid.
> Add Enable Remote Commands to Zabbix Proxy

- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
according to the FRR documentation and the ui validations, match is optional (https://docs.frrouting.org/en/latest/routemap.html#term-Matching-Conditions). Likely fixes https://github.com/opnsense/plugins/issues/2955
> net/frr: (BGP) Configure ipv6 next-hop on route-map

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
API key field  type of Transip corrected from "text" to "textbox". It was nog working with "text" due to linebreaks. I tested and this and now it works. Furthernore added a note that 300s sleep time is recommended.
> security/acme-client: Correct TransIP API

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/ActionsController.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdRemoteSsh.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Process.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SSHKeys.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpClient.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/SftpUploader.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/Utils.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- security/acme-client/src/opnsense/mvc/app/views/OPNsense/AcmeClient/actions.volt
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/run_remote_ssh.php
- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php
- security/acme-client/src/opnsense/service/conf/actions.d/actions_acmeclient.conf
Draft PR that implements ACME action to trigger remote commands via SSH.
Implements #2757 using the infrastructure already in place for SFTP. Since it is a separate concern to run a command vs upload files it was implemented as separate action to not mix things (e.g. SSH connection vs SFTP connection).
To make this contribution useful, user-defined order of actions (like requested in #2833) should be in place so that one can upload first and trigger commands afterwards.
Current status: Needs more testing, but works in my environment.
> security/acme-client: SSH remote command automation (#2757)

- net/wireguard/Makefile
- net/wireguard/pkg-descr
- net/wireguard/src/opnsense/scripts/OPNsense/Wireguard/resolve-dns.sh
- net/wireguard/src/opnsense/service/conf/actions.d/actions_wireguard.conf
Wireguard does DNS resolution of endpoints only on startup. Even when a keepalive is in place, a stale connection does not lead to a renewal of DNS entries in case the other side's IP has changed.
This adds a script that can be called from cron every now and then and then triggers a DNS renewal for all stale connections.
> os-wireguard: add script to enable cron renewal of DNS for stale connections

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServerController.php
Trim is used in many other plugins before config values are stored. Discussion here:
https://forum.opnsense.org/index.php?topic=28345.msg137607#msg137607
> Trim whitespace around public and private keys in config.

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
The missing <style> field at TransIP was causing the fields below it to show up in ALL dialogs.
> security/acme-client: Add missing <style> field

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
While working on an Azure setup where the neighbor isn't within visible range, we stumbled upon the "disable-connected-check" option to allow loopback addresses.
Reading a bit further there seem to be different ways of dealing with similar kind of situations.
Either by setting an ebgp-multihop ttl value or to enable the disable-connected-check option. Since the multihop didn't come with a help text, it seemed like a good idea to add at least the upstream frr one. Knowning that the current multihop fieldtype currently is wrong ("enabling" will set a ttl of 255, where it should have been a number)
Used the following resources:
- https://nexp.com.ua/technologies/rns/bgp-loopbacks/
- https://docs.frrouting.org/en/latest/bgp.html
- https://github.com/FRRouting/frr/issues/2713
Ideally one …
> net/frr add disable-connected-check option

- www/nginx/Makefile
- www/nginx/pkg-descr
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/security_headers.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/security_rule.conf
Add support for
* Web Workers
* Websockets
in Content Security Policy.
Closes #1396
> www/nginx: add support for workers and websockets in CSP directive

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BgpController.php
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Add (advanced) bgp `weight` attribute and move `disable-connected-check` to the correct place (both should be set in the generic peer options). 
It looked like "community lists" missed a toggle action, added that as well.
> net/frr - BGP weight option and bug fix for disable-connected-check option

- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
The Internet Speed Monitor plugin collects data about the internet speed on the system.
> net-mgmt/telegraf: Add internet speed input plugin

- sysutils/apcupsd/src/opnsense/mvc/app/controllers/OPNsense/Apcupsd/forms/general.xml
- sysutils/apcupsd/src/opnsense/mvc/app/models/OPNsense/Apcupsd/Apcupsd.xml
From the manual apcupsd will react to the first valid test of timeout expired, battery level remaining, minutes remaining setting.
Setting the minimum value to `-1` for battery level and minutes will allow to disable those checks.
> sysutils/apcupsd: change minimum value for battery level and minutes settings

- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.php
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/Api/SettingsController.php
This changes the parameters for four functions in HAProxy.php.
The ACME Client appears to call these functions with positional rather than named params so also switch the order of the parameters in these function calls
Fixes: #3042
> Re-order function parameters due to PHP8 deprecation notice

- security/maltrail/Makefile
- security/maltrail/pkg-descr
- security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrailsensor
- security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrailserver
As discussed in https://github.com/opnsense/plugins/issues/3002
> security/maltrail: remove MFS for /var/log/

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Hi there,
all-inkl.com updated its KASAPI and is removing SHA1 as Authtype at around December 2022. Unfortunately, they will just have plain as option. Even if one would like to use the alternate "session", the login will need "plain". In regards of the task (ACME client), the documentation and staff state (not directly advise, but you can avoid the session) to just use plain instead of session.
> update ACME Client KAS by all-inkl.com

- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
Fixes #3074
For me unclear reasons PrefixLists and CommunityLists did not allow to specify multiple lists. Saving them failed with a very unclear error `Related item not found` in the UI, as pointed out in above issue.
The bgpd.conf does include support specifying multiple lists, but the UI blocked the same:
https://github.com/opnsense/plugins/blob/4546aeb47d62010ea4f8d3e4204b26285be864fe/net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L180-L218
After this change, multiple lists can be selected and saved:
And:
After reloading the service, the config at `/usr/local/etc/frr/bgpd.conf` reflects the change:
```text
ip prefix-list AllowAll seq 99 permit any
!
ip prefix-list DenyWAN seq 20 deny SOME_IP/24
!
!
!
!
route-map DefaultRouteMap permit 20
match ip address prefix-list …
```
> net/frr: Allow specifying multiple PrefixLists and CommunityLists

- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
By default any BGP neighbor has IPv4-unicast address family enabled. This leads to a number of IPv6 neighbors listed under the IPv4-unicast summary in Routing -> Diagnostics -> BGP ->Summary with NoNeg status (unless it is OpnSense on the other side as well). With _no bgp default ipv4-unicast_ option we will have only IPv4 neighbors under the IPv4-unicast address family summary and only IPv6 neighbors under the IPv6-unicast address family summary.
Please, refer to the [docs](http://docs.frrouting.org/en/stable-7.5/bgp.html#clicmd-[no]bgpdefaultipv4-unicast) for details.
> net/frr: set no bgp default ipv4-unicast in bgpd.conf

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/checkip
icanhazip.com tends to be very fast, and only returns the actual IP address, so less processing time is needed.
> dns/ddclient - Add icanhazip.com as a checkip provider

- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/checkip
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
For ddclient plugin, add a configurable checkip timeout which defaults to 10 seconds. This is to cover high latency corner cases which some users have been reporting.
See #3133 and #3051 for details.
cc @AdSchellevis
> ddclient configurable checkip timeout

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsSelfhost.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Hello,
now we got the selfhost dns in the acme.sh master.
We had to remove rid and rid2 and have replaced it with a mapping field.
Usage: https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#151-use-selfhost-dns-api
> security/acme-client: Update selfhost (breaking change)

- net/haproxy/src/opnsense/scripts/OPNsense/HAProxy/setup.sh
- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Hi!
ref. https://forum.opnsense.org/index.php?topic=28007.0
looks like it require special unix sockets binding and targeting since haproxy is chrooted
pr moves sockets to `/var/haproxy/sockets` 
Thanks!
> net/haproxy: chrooted sockets binding

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/bgp.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
This adds a checkbox to enable frr's BGP Network Import-Check, as I had requirement in my own setup for this.
**Reason**
Until including frr 7.3, all defined networks were announced. Starting frr 7.4 (released [July 2020](https://github.com/FRRouting/frr/releases/tag/frr-7.4)) only routes present in the routing tables are announced. See frr documentation at: https://docs.frrouting.org/en/latest/bgp.html#networks
To not change default behavior in future frr releases again, I have added if-else to explicitly enable or disable the functionality based on the setting in OPNsense GUI.
There might be requirements - or expectations from users like myself - that all defined networks are announced. Therefore I also added a clarification with existing 'Network' help text.
**Impact**
For existing and …
> net/frr: Added BGP Network Import-Check

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ClientController.php
- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/ServerController.php
- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardClient.xml
- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
- net/wireguard/src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
Those are generally minor changes:
1. Add interface name (wgX) as a column
2. Corrected/improved/explained a few help entries better and renamed them. Also using "Peers" instead of "Endpoints", as WireGuard also refers to "Peers" in their configuration and documentation.
3. Update configuration and handshakes once page loaded, instead waiting for the 5 secs refresh interval to start.
> net/wireguard: Late Spring Cleaning

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php
- net/wireguard/src/www/widgets/widgets/wireguard.widget.php
The old WireGuard widget was there, but honestly wasn't providing much information:
So I decided to rework it. It now looks like this:
Following to note:
1. When WireGuard is disabled, nothing will appear.
2. Disabled Locals or Peers are not shown. If they are disabled, they will disappear on the next refresh cycle.
3. The data is refreshed via AJAX every 10 seconds.
4. When there is one Interface with 2 Peers, there're 2 entries in the table (see 2x wg4 and end4 and end5 entries)
5. The code sometimes looks a bit complicated - but the handshakes are retrieved from the CLI with only 1) the interface name, 2) the public key of the peer. So to get more details from the WireGuard configuration, I had to do some matching. The matching is based on 1) searching the same interface, 2) and then …
> net/wireguard: Reworked widget

- security/tor/src/opnsense/service/templates/OPNsense/Tor/torrc
On suitable hardware platforms, FreeBSD/OPNsense supports hardware acceleration for crypto. Verified with https://stackoverflow.com/a/28614159/5424487
TOR however is not set up to make use of this. This change should enable it. Especially useful on those weak CPUs commonly used in router boxes. From https://www.freebsd.org/cgi/man.cgi?tor(1):
```
HardwareAccel 0|1
If non-zero,	try to use built-in (static) crypto hardware
acceleration	when available.	Can not	be changed while tor is
running. (Default: 0)
```
Because TOR (or rather OpenSSL) will fall back to software crypto when hardware crypto is not available, I see no need to make this flag configurable in the web UI, making this a very trivial PR :)
> Enable hardware acceleration in TOR

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Add the [apcupsd input](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/apcupsd/README.md) to telegraf.
Tested on multiple OPNsense running 22.7.6.
> net-mgmt/telegraf: Add apcupsd input

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php
This PR fixes the following error, triggered when opening the dashboard (with the Wireguard widget and a configuration with dead peers in servers): 
```
[04-Nov-2022 13:53:07 Europe/Berlin] TypeError: array_merge(): Argument #1 must be of type array, null given in /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php:93
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Wireguard/Api/GeneralController.php(93): array_merge(NULL, Array)
#1 [internal function]: OPNsense\Wireguard\Api\GeneralController->getStatusAction()
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Wireguard\Api\GeneralController), 'getStatusAction', Array)
#3 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch() …
```
> net/wireguard: Fixed array_merge error for removed peers

- net/upnp/src/etc/inc/plugins.inc.d/miniupnpd.inc
Later releases of miniupnpd require additional firewall anchors to function properly. This commit adds those.
> net/upnp: add missing firewall anchors

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Adding the ability to configure a timeout for InfluxV2. Without this issues can arise when the Telegraf is trying to flush metrics.
> net-mgmt/telegraf: Add Influxv2 timeout

- dns/ddclient/pkg-descr
- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
Add 1984, ClouDNS, Dinahosting, DNSExit, DonDominio, Freemyip, godaddy, Hetzner, Key-Systems, NearlyFreeSpeech.NET, Njal.la(thanks to satrapes), sitelutions, woima and Yandex for ddclient 3.10.0.
I hope that is okay that I have taken the changes from https://github.com/opnsense/plugins/pull/3129.
> dns/ddclient Add support for ddclient 3.10.0 dns provider

- security/clamav/Makefile
- security/clamav/pkg-descr
- security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/forms/general.xml
- security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/ACL/ACL.xml
- security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/General.xml
- security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/Menu/Menu.xml
- security/clamav/src/opnsense/service/templates/OPNsense/ClamAV/clamd.conf
- security/clamav/src/opnsense/service/templates/OPNsense/ClamAV/freshclam.conf
- security/clamav/src/opnsense/service/templates/OPNsense/Syslog/local/clamd.conf
Hi
ref. https://forum.opnsense.org/index.php?topic=31198.0
maybe it makes sense to switch to using syslog? )
from
to
verbose logging option added, just in case
thanks!
> security/clamav: migrate to syslog-ng

- dns/ddclient/pkg-descr
- dns/ddclient/src/opnsense/scripts/ddclient/checkip
When using external services to determine the public IPv6 address of an interface, the bounds are too limited for short (but valid) IPv6 addresses. Reducing the necessary amount of colon characters in the resolved IPv6 address for the `checkip` script to accept them fixes this issue.
For example an IPv6 address of this format `aaaa:bbbb:cccc::dddd` would be incorrectly deemed invalid because it has only 4 `:` colon characters but the `checkip` script requires *more* than 4.
I've reduced the amount of necessary colon characters to two, which is the least necessary amount for a valid IPv6 address according to [RFC-4291 Section 2.2](https://www.rfc-editor.org/rfc/rfc4291.html#section-2.2), even though it's unlikely many of those short IPv6 addresses are actually publicly routed/delegated. …
> dns/ddclient: Fix IPv6 address parsing from external service

- security/stunnel/src/opnsense/scripts/stunnel/generate_certs.php
```
PHP Fatal error:  Uncaught Error: Call to undefined function log_msg() in /usr/local/etc/inc/plugins.inc:251 Stack trace:
#0 /usr/local/opnsense/scripts/stunnel/generate_certs.php(89): plugins_configure('crl')
#1 {main}
thrown in /usr/local/etc/inc/plugins.inc on line 251
```
> security/stunnel: Add missing inclusion

- dns/bind/pkg-descr
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindMasterDomain.xml
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindSlaveDomain.xml
- dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
This cleans up the `master`/`slave` dialog boxes to only contain the items that are actually processed for each zone type. It also remove the Type column from the zone list since this is redundant information.
> dns/bind: cleanup master/slave zone UI

- dns/bind/pkg-descr
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/GeneralController.php
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/rndcKey.xml
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/General.xml
- dns/bind/src/opnsense/mvc/app/views/OPNsense/Bind/general.volt
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/rndc.conf
This adds RNDC Key UI support which closes #2196. This restarts the `named` service when the RNDC key changes instead of doing a reconfigure.
> dns/bind: add RNDC key UI support

- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Allow certificate renewal intervals up to 5000 days. 
refs https://github.com/opnsense/plugins/issues/3219
> security/acme: increase max value for certificate renewal interval

- dns/bind/pkg-descr
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Acl.xml
This ensure that the ACL names are unique, since you can't add two ACLs with the same name in the `named.conf` file this ensures that you are given an error message in the UI when you try to add/update an ACL.
This PR supersedes #3235.
> dns/bind: ensure the ACL names are unique

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsOnline.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Add new API for ACME dns challenge type:
* online.net
refs https://github.com/opnsense/plugins/issues/3213
> security/acme: Add online.net API for dns challenge type

- dns/bind/pkg-descr
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindPrimaryDomain.xml
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindSecondaryDomain.xml
- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/general.xml
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Domain.xml
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/General.xml
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
This would allow multiple ACLs to be defined for `Allow Transfer` and `Allow Query`. This needs to be merged after #3234 since it updates the `domain` model version higher than that PR.
This is the initial work to allow for key based `allow transfer` statements and also to allow nested ACLs.
> dns/bind: allow multiple acls

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBGPNeighbor.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BGP.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Closes #3084
This adds the attribute-unchanged option as discussed in above issue.
The config generated when enabling looks like:
```
root@OPNsense:~ # cat /usr/local/etc/frr/bgpd.conf
[...]
router bgp 64511
no bgp ebgp-requires-policy
neighbor 10.2.2.2 remote-as 64512
neighbor 10.2.2.2 update-source em0
neighbor 10.2.2.2 attribute-unchanged med
address-family ipv4 unicast
```
> net/frr: Added attribute-unchanged option

- net/frr/src/opnsense/service/conf/actions.d/actions_quagga.conf
I was trying to configure Cron to restart FRR periodically. Oddly enough, I could choose between a bunch of services to restart but not FRR.
After some troubleshooting, I figured only actions with a description were showing up in the list when setting up a Cron job.
This fixes the issue by adding a description to FRR's restart action.
> net/frr: make restart action available in Cron settings

- net/upnp/src/etc/inc/plugins.inc.d/miniupnpd.inc
I've never committed to this project, so apologies I'm not sure if its my job to point to the stable branch or maintainers pluck changes.
I upgraded to 23.1 this morning and a crash was detected.
```
[28-Jan-2023 07:09:40 America/New_York] Error: Undefined constant "LOG_WARING" in /usr/local/etc/inc/plugins.inc.d/miniupnpd.inc:162
Stack trace:
#0 /usr/local/etc/inc/plugins.inc(292): miniupnpd_configure_do(true)
#1 /usr/local/etc/rc.bootup(106): plugins_configure('bootup', true)
#2 {main}
```
It looks like it regressed here: https://github.com/opnsense/plugins/commit/ec1399c9a24285f8bba3dc689fbbd0c1e7ea212b
> net/upnp: Correct crash due to LOG_WARNING typo.

- security/openconnect/Makefile
- security/openconnect/pkg-descr
- security/openconnect/src/opnsense/service/templates/OPNsense/Openconnect/openconnect.conf
Required for some VPN hosts, in my case was needed for my university VPN. Tested by changing the equivalent file on my installation, correctly only adds this useragent for the case of anyconnect VPNs.
> security/openconnect: useragent="AnyConnect" for better compatibility

- emulators/qemu-guest-agent/Makefile
- emulators/qemu-guest-agent/pkg-descr
fixes #3283
depends on https://github.com/opnsense/tools/pull/344
This release ensures that users are actually migrated to the new version.
> emulators/qemu-guest-agent: release 1.2

- net/haproxy/src/opnsense/service/templates/OPNsense/HAProxy/haproxy.conf
Use the option field _ssl_ instead of boolean _force_ssl_ for case 2. in health checks
> net/haproxy: fix HAProxy SSL preferences in healthchecks

- security/acme-client/src/opnsense/service/templates/OPNsense/AcmeClient/lighttpd-acme-challenge.conf
Hi!
on ACME Client plugin reload it produces warnings in Web GUI log (since it lighttpd proc name also):
pr tries to fix this by:
use '`deflate.`' options to enable compression
remove `server.dir-listing = "disable"` since mod_dirlisting is disabled by default
thanks!
> security/acme: minor lighty config fixes

- misc/theme-cicada/Makefile
- misc/theme-cicada/src/opnsense/www/themes/cicada/build/css/dns-overview.css
- misc/theme-vicuna/Makefile
- misc/theme-vicuna/src/opnsense/www/themes/vicuna/build/css/dns-overview.css
by the way......for the dns-unbound reporting html basic structure the color "white" was written hardcoded. the color is defined differently in each theme and is already defined in the main.css. I would ask you to remove this hardcoded part so that the colors of the themes can be used again. the part I mentioned is here. see the screenshot
> dns-overview.css color theme fixes for Cicada/Vicuna

- sysutils/api-backup/Makefile
- sysutils/api-backup/pkg-descr
- sysutils/api-backup/src/opnsense/mvc/app/controllers/OPNsense/Backup/Api/BackupController.php
This PR adds a new API endpoint `/api/backup/backup/download/json` that can be used to download a backup of the `config.xml` in JSON:
```
{"status":"success","filename":"config.xml","filetype":"application\/xml","content":"REDACTED"}
```
This is necessary for some cases where a "real" API is needed. The existing API endpoint `/api/backup/backup/download` is nice for shell scripts or when using curl to perform backups. However, it does not behave like any other OPNsense API, making it cumbersome to implement in existing systems/applications.
So this additional API endpoint provides a OPNsense-like API with the same goal: provide an easy way to perform automatic backups of the system configuration. And it does not increase code complexity in any meaningful way, so everyone wins. :)
> sysutils/api-backup: add json download functionality

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/settings.xml
Single word changed, see commit.
> security/acme-client: fixed typo in HAProxy info

- net/frr/src/opnsense/scripts/frr/register_sas
OPNsense supports BGP on both IPv4 and IPv6, but the current frr/setkey script implementation only adds SAD entries for IPv4. Changing -4 to -n keeps filtering on numeric addresses, but adds SAD entries for both IPv4 and IPv6 instead of only IPv4.
Tested working on a Vultr VM with BGP enabled and MD5 password on the Vultr side.
> net/frr register_sas script/setkey add SAD entries for both IPv6 and IPv4

- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/cloudflare.py
I had some free time and implemented cloudflare support for ddclient with OPNsense backend.
It supports a single hostname/record.
It needs some better error handling and there is also no support for multiple Hostnames and Wildcard at the moment.
Credentials have remained the same, as with ddclient backend (Username=Mailaddress of the cloudflare account, Password=Global API Key)
Tested on 23.1.3_4
> Cloudflare implementation for OPNsense backend ddclient

- security/crowdsec/Makefile
- security/crowdsec/pkg-descr
- security/crowdsec/src/etc/crowdsec/acquis.d/opnsense.yaml
- security/crowdsec/src/opnsense/mvc/app/models/OPNsense/CrowdSec/General.xml
The filter logs are used by a new scenario in the opnsense collections to detect port scans.
> security/crowdsec: bump version 1.0.3; acquire packet filter logs.

- security/maltrail/src/opnsense/mvc/app/controllers/OPNsense/Maltrail/forms/sensor.xml
Correct 'Help Text' for Remote Port, the removed text mentions that field can be left blank which is incorrect. A value needs to be specified for the service to run correctly.
> Correct 'Help Text' for Remote Port - Maltrail - Sensor Settings

- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
Obviously a typo the `query-source` section in the generated named.conf is always empty because of the wrong loop variable referenced in the code. This leads to BIND failing to start up.
If you agree, shall I update the plugin version and `pkg-descr` accordingly or just bump the plugin revision? I'm not quite familiar with the meaning of the latter.
Kind regards,
Patrick
> dns/bind: fix bug in ACL processing for `allow-query` section

- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
Without this, I get the following in flush_status() in poller.py when it tries to dump the state to the file:
```
"IPv4Address('xx.xx.xx.xx') is not JSON serializable"
```
```
fhandle.seek(0)
fhandle.truncate()
data = {}
for acc_id in self._accounts:
data[acc_id] = self._accounts[acc_id].state
fhandle.write(ujson.dumps(data))
```
I am using custom dyndns2 if that is interesting at all, ~I am not sure how others have made this work so far without this change...~ Edit: Ah I bet they are using the curl methods instead of the interface for the IP
> [ddclient] OPNsense backend, make sure address is string

- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
Fixes #3450
Adjusts ddclient.conf to use `ifv4`/`ifv6` fields for interface monitoring, as the `if` field is deprecated, and causes ddclient to fall back to "default interface" detection logic.
> dns/ddclient: update ddclient.conf interface template for ifv4 and ifv6

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Fixes: #3265 
If you have a populated InfluxDB v2 configuration, and you want to disable it, then the timeout should be removed from the configuration file. The Jinja2 template had an incorrectly nested loop so if the InfluxDB v2 timeout was set, the `timeout` key/value would still be put into the configuration file and may cause Telegraf to fail to start for several reasons (depending on your exact configuration:
`2023-02-17T13:38:15Z E! [telegraf] Error running agent: error loading config file /usr/local/etc/telegraf.conf: error parsing data: line 34: key 'timeout' is in conflict with line 18d`
`2023-02-17T13:46:19Z E! [telegraf] Error running agent: error loading config file /usr/local/etc/telegraf.conf: plugin outputs.prometheus_client: line 19: configuration specified the fields …
> net-mgmt/telegraf: don't set timeout for disabled InfluxDB v2

- net/wireguard/src/www/widgets/widgets/wireguard.widget.php
Fixes public key overlapping latest handshake, moving the ellipsis to css to allow full display and fix current overlap.
This appears for me with Dashboard at 3 columns, which makes widget width 230px, but it surely appears at other configs too.
Current overlap looks like this, which make nither pk nor date legible.
> net/wireguard: widget, fix/improve colum public key overlapping latest handshake

- www/nginx/src/opnsense/mvc/app/views/OPNsense/Nginx/index.volt
Fix width of commands column to display "delete" symbol in nginx config again, which was lost after https://github.com/opnsense/plugins/commit/55820e4f77c784fca0b89fa24593f9f1286d04ef 
Fixes https://github.com/opnsense/plugins/issues/3448
> www/nginx: update index.volt - fix commands column size

- dns/dnscrypt-proxy/pkg-descr
- dns/dnscrypt-proxy/src/opnsense/mvc/app/models/OPNsense/Dnscryptproxy/General.xml
Currently GUI fails to display disabled servers, when more than one server is configured.
Also added `ValidationMessage`.
> dns/dnscrypt-proxy: fix GUI with more than one disabled server

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsGoogledomains.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
- Rename `DnsGoogleDomains.php`->`DnsGoogledomains.php`
Adds support for Google Domains DNS-01 ACME challenge API added to latest upstream acme.sh. This is separate from the Google Cloud API.
https://domains.google/learn/gts-acme/
See acmesh-official/acme.sh#4542
Manually tested with `opnsense-patch -c plugins 4714943b1888`
> security/acme-client: Add domains.google support

- net/firewall/Makefile
- net/firewall/src/opnsense/mvc/app/models/OPNsense/Firewall/Filter.xml
Hi,
If you have a bash script calling couple of firewalls and don't want to care about interfaces (similar to floating rules), the API required an interface.
When setting this to `N` and applying the rules the rules.debug looks sane:
```
pass in quick on igb1 inet from {1.1.1.1} to {2.2.2.2} label "f24eb5c97fba314949e404267481211b" # testAPI
pass in quick inet from {1.1.1.1} to {2.2.2.2} label "00d1413e3dba729147b991cf3876a721" # testAPI2
```
> net/firewall: Make interface optional (like floating)

- net/wireguard/src/opnsense/service/templates/OPNsense/Wireguard/wireguard-server.conf
This adds '# friendly_name = {{ peerlist2_data.name }}" for each peer.
With this it is possible to run the [MindFlavor/prometheus_wireguard_exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter) on OPNsense and get the prom label `friendly_name` - if enabled in the exporter.
IMO there is no downside in writing this to the wg config because _everyone_ could get this information anyway from the local filesystem.
i will eventually figure out how to make a plugin / package for the exporter itself and submit that as well.
(dunno how / what is necessary but im familiar with RPM building and hope the difference is minimal)
in the meantime this change would make it easy for everyone willing to install the exporter on their own.
despite the fact that there is basically no real …
> Add "friendly_name" to wg config for prom wg exporter

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeProxmoxve.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
> security/acme: expose new values for Proxmox VE deployhook, closes #3516

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsIpv64.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Adds support for IPv64.net DNS-01 ACME challenge API added to latest upstream acme.sh.
https://ipv64.net/
see acmesh-official/acme.sh#4420
> security/acme-client: Add IPv64.net support

- net/relayd/Makefile
- net/relayd/src/opnsense/mvc/app/controllers/OPNsense/Relayd/Api/StatusController.php
- net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Migrations/M1_0_5.php
- net/relayd/src/opnsense/mvc/app/models/OPNsense/Relayd/Relayd.xml
- net/relayd/src/opnsense/service/templates/OPNsense/Relayd/relayd.conf
An updated relayd version is on it's way, which should bring FreeBSD's version in sync with upstream OpenBSD (https://github.com/freebsd/freebsd-ports/commit/c9ba90c07ddc5b9f4232f831cf301fdc939303f3). Since some small things have changed, we need a migration and a some small config changes.
A test build is available  at https://pkg.opnsense.org/FreeBSD:13:amd64/snapshots/misc/relayd-7.3.2023.05.09.p2.pkg
> net/relayd - sync with OpenBSD 

- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/dyndns2.py
desec uses also dyndns2 protocol and can therefore directly added to the list of supported services. config is
- Services: Dynamic DNS: Settings: Edit Account Enabled [X]
Service [desec (v6)]
Protocol  [DynDNS2]
Username [Your Domain]
Password [Your DeSec Token]
Hostname(s) [Your Domain]
Check ip method [Interface [IPv6]]
Force SSL [X]
Interface to monitor [Your WAN Interface]
- Services: Dynamic DNS: Settings: Edit Account Enabled [X]
Service [desec (v4)]
Protocol  [DynDNS2]
Username [Your Domain]
Password [Your DeSec Token]
Hostname(s) [Your Domain]
Check ip method [Interface [IPv4]]
Force SSL [X]
Interface to monitor [Your WAN Interface]
> Add desec service provider to ddclient OPnsense backend

- benchmarks/iperf/Makefile
Adds the missing rubygem-rexml dependency to os-iperf
This makes the service startable and allows the Interfaces -> Diagnostics -> iperf GUI to work again
Fixes #3522
> benchmarks/iperf: add rubygem-rexml dependency

- security/crowdsec/Makefile
- security/crowdsec/pkg-descr
- security/crowdsec/src/opnsense/scripts/OPNsense/CrowdSec/reconfigure.py
I am confident this option does not need to be exposed in the UI and can be enabled unconditionally. It was introduced in Crowdsec 1.5.4 to make the bouncer retry contacting the LAPI endpoint if the first try fails. I don't see how this could ever hurt.
Kind regards,
Patrick
> security/crowdsec - add option `retry_initial_connect` to bouncer configuration for more robust startup

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Output.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Hi,
it seems I need a pair of fresh eyes finding my error in this PR. Want to add mqtt as output and to me everything looks good, but when clicking on the submenu "Output" in Telegraf, I immediately get redirected to crash reporter with:
```
[08-Oct-2023 07:27:43 Europe/Berlin] Exception: form xml /usr/local/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/output.xml not valid in /usr/local/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php:161
Stack trace:
#0 /usr/local/opnsense/mvc/app/controllers/OPNsense/Telegraf/OutputController.php(35): OPNsense\Base\ControllerBase->getForm('output')
#1 [internal function]: OPNsense\Telegraf\OutputController->indexAction()
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(OPNsense\Telegraf\OutputCon …
```
> net-mgmt/telegraf: Add mqtt output

- net/wireguard/src/opnsense/mvc/app/controllers/OPNsense/Wireguard/forms/dialogEditWireguardServer.xml
- net/wireguard/src/opnsense/scripts/Wireguard/wg-service-control.php
Issue: https://forum.opnsense.org/index.php?topic=36503.0
Error message:
`Error	wireguard	/usr/local/opnsense/scripts/Wireguard/wg-service-control.php: The command '/sbin/ifconfig 'wg1' 'inet' '' alias' returned exit code '1', the output was 'ifconfig: : bad value'`
I have edited the wg-service-control.php to implement an array_filter() function that filters empty strings for tunnel address by checking the byte length with strlen. This way, it will be empty if no tunnel address is given, instead of "".
Also adjusted the help text to hint leaving the tunnel address empty for point to point connections.
> wg - fix error when empty tunnel address in instance

- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/general.xml
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
Fixes #3650. This works for me for the mentioned issue and use case. Not exactly familiar with the templates.
> [os-bind] #3650 - break-dnssec toggle needed for Enable filter-aaaa on IPv4/IPv6 clients

- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/c-icap.conf
With OPNSense 23.7.8 and c-icap 0.5.11, the service refuses to start using the generated config.
This commit changes the acl-syntax as suggested by [this forum post](https://forum.opnsense.org/index.php?topic=36895.msg180513#msg180513).
> [C-ICAP] Change ACL Sytax

- net-mgmt/net-snmp/src/opnsense/scripts/OPNsense/Netsnmp/setup.sh
```
chown: /var/mib_indexes: No such file or directory
Starting snmpd.
```
Someone reported ages ago [at the forums](https://forum.opnsense.org/index.php?topic=21432.0)
> [net-snmp]- Fix mib_indexes directory path

- dns/bind/src/opnsense/service/templates/OPNsense/Bind/domain.db
Hi!
can close https://github.com/opnsense/plugins/issues/3703 i hope
- template may throw an error if there is no `records` at all in config
- primary zone MUST have NS record
pr tries to solve this by adding a check before sorting ~~and adding fallback NS from SOA record (technically not very correct, but its realy frequently used (MNAME as one of NS-servers) imho)~~
Thanks!
> dns/bind: fix possible template error

- sysutils/smart/src/www/widgets/widgets/smart_status.widget.php
Add word-breaking to the "Ident" column of the SMART Dashboard widget, to prevent long device names from causing the table to extend outside of the widget's div.
See the following example:
With this PR, this will get corrected to look as follows:
This style of word breaking is in line with the table in the "interface_list" widget. I had originally considered truncating the long "Ident" values with ellipsis; however, since there was already precedent in other widgets to use word-break, I wanted to stay consistent.
> sysutils/smart: add word break to ident in widget

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsBunny.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Added support for Bunny DNS for the DNS-01 ACME challenge, which is supported by acme.sh.
Tested with `opnsense-patch -c plugins 8636a1f`, and confirmed it worked successfully
> security/acme-client: Add support for Bunny DNS API

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsEasydns.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
acme.sh [has support for easyDNS](https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#dns_easydns) as a dns01 provider. This adds support for OPNSense to expose this in the UI for easyDNS customers
Tested on OPNsense 23.7.9:
system.log:
```
<13>1 2023-12-12T17:39:33+00:00 opnsense opnsense 36298 - [meta sequenceId="88"] AcmeClient: certificate must be issued/renewed: <Removed>
<13>1 2023-12-12T17:39:33+00:00 opnsense opnsense 36298 - [meta sequenceId="89"] AcmeClient: issue certificate: <Removed>
<13>1 2023-12-12T17:39:33+00:00 opnsense opnsense 36298 - [meta sequenceId="90"] AcmeClient: using CA: letsencrypt
<13>1 2023-12-12T17:39:33+00:00 opnsense opnsense 36298 - [meta sequenceId="91"] AcmeClient: account is registered: <Removed>
<13>1 2023-12-12T17:39:33+00:00 opnsense opnsense …
```
> security/acme-client: Expose acme.sh EasyDNS support

- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsGandiLivedns.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
> security/acme-client: support token authentication in Gandi LiveDNS

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
With the pull #3252 the limit was increased on the software side, but the display text in the configuration dialogue was not adjusted. This misguided me, you could have simply set a higher value.
> Update max value forms display text for acme client

- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
Added Digitalocean ddns support
> Add Digitalocean ddns support

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
Enable access to the **Mythic Beasts** service which is built into **ddclient**.  This will not work correctly in ddclient v3.11.2 or lower.  However, I have had a PR accepted (& merged) to fix ddclient and this will provide support for IPV4 and IPV6 updates in a single invocation.
This change to DynDNS.xml appears to be the only change necessary to produce a correct `/usr/local/etc/ddclient.conf` file (containing the line `protocol=mythicdyn` )
> Update DynDNS.xml to provide access to Mythic Beasts dynamic dns service via their API V2

- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
Some legacy devices needs plain authentication, quite simple
> net/frr: Add plain password authentication to OSPF

- net/upnp/Makefile
- net/upnp/pkg-descr
- net/upnp/src/etc/inc/plugins.inc.d/miniupnpd.inc
- net/upnp/src/www/services_upnp.php
and also mention `UPnP IGD` as `UPnP` is probably not specific enough.
Port Control Protocol (PCP) is the successor to NAT-PMP and has similar protocol concepts and packet formats, but adds IPv6 support.
*PCP standard:*
https://datatracker.ietf.org/doc/html/rfc6887
https://en.wikipedia.org/wiki/Port_Control_Protocol
*NAT-PMP std. (see 9.1 Simplicity - 9.3 for some diff. to UPnP IGD):*
https://datatracker.ietf.org/doc/html/rfc6886
> net/upnp: Update plugin wording to include PCP as supported

- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/domeneshop.py
Fixes typo of the URL Get parameter name `hostname`.
See API documentation: https://api.domeneshop.no/docs
> dns/ddclient: fix domeneshop hostname parameter name

- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/HttpOpnsense.php
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/TlsalpnAcme.php
Hi!
just a typos quick fix:
-json_decode backend response before use (to make adding an IP by the selected interface work)
-more strict type for "IP Auto-Discovery" check (to make it possible to turn the autodiscovery off)
Thanks!
> security/acme-client: http/tlsalpn libs typos

- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/domeneshop.py
Since Python 3.8, 'is' and 'is not' produce warnings when its behavior is undefined by the language spec.
See: https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior
---
(First time contributor to this project, let me know if there's anything I need to do).
More specifically, inside of the OPNsense backend logs, I get this "Error"-level message from configd.py (spaced for clarity):
<details>
```
[b1725c24-8952-4125-944c-66b8132873f5] Script action stderr returned "b'/usr/local/opnsense/scripts/ddclient/lib/account/domeneshop.py:70: SyntaxWarning: "is" with a literal. Did you mean "=="?
if response.status_code is 204:
/usr/local/opnsense/scripts/ddclient/lib/account/domeneshop.py:78: SyntaxWarning: "is" with a liter'"
```
</details>
The fix is simply to use `==` instead. …
> ddclient: Domeneshop - use '==' instead of 'is'

- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Might fix #3763.
Basically, when using FRR, it doesn't set the value of ebgp-multihop by default, which defaults it to 1.
IMHO: Better to have a higher value than a lower value, so I set it to 255.
> net/frr: Set multihop value to 255

- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
I have a bunch of secondary configured in the BIND Plugin. If I make a change through the web interface, the named.conf file at /usr/local/etc/namedb/named.conf will be regenerated from the /usr/local/opnsense/service/templates/OPNsense/Bind/named.conf template.
/usr/local/bin/named does not allow updates on the secondary zone as they should be done to the primary zone. Hence named throws an error:
`/usr/local/etc/namedb/named.conf:93: option 'update-policy' is not allowed in 'secondary' zone 'xx.xx.xx.in-addr.arpa'
`
In the secondary zone configuration block, 'update-policy' seems not to be allowed - this is a snippet from the generated name.conf file:
```
zone "xx.xx.xx.in-addr.arpa" {
type secondary;
primaries { yy.yy.yy.yy key "key.dyn.zz.zz.zz"; };
file …
```
>  dns/bind: Do not add the update-policy if the zone type is secondary

- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/users
To improve security provide an "advanced" option to avoid storing
users' radius passwords in plaintext.
The default behaviour is unchanged.
Tested using an openwrt access point as a client with the opnsense
freeradius plugin set to use PEAP.
Compare: https://github.com/pfsense/FreeBSD-ports/pull/822
> net/freeradius: Support NT hash of user password

- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/General.xml
Hi!
adjust log severity levels: remove not supported, rename deprecated, add 'dynamic'.
closes https://github.com/opnsense/plugins/issues/3876
Thanks!
> dns/bind: adjust log severity levels

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dnsprovider.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dynamicdns.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/logsettings.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/setup.sh
- www/caddy/src/opnsense/service/conf/actions.d/actions_caddy.conf
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
WIP Pull request for next version of os-caddy.
**DONE for v1.5.3:**
- Change from Phalcon Messages to OPNsense Messages - Requires: https://github.com/opnsense/core/commit/c2ea9aa3039eb4d24ba53a7aa2190642150f20eb
- Change default storage location to ```/var/db/caddy/data/caddy/``` (in line with rc.d file), by removing custom storage mount in the Caddyfile
- Refactor setup.sh for new storage location
- Add [tls_insecure_skip_verify](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#tls_insecure_skip_verify) to handlers because a lot of people need it for backwards compatibility with old services, examples would be certificates that only have a CN, weird self signed certs that have expired, old ciphers etc... Not all services allow their cert to be changed (sadly...)
- Change …
> www/caddy: v1.5.3

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsDnshome.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Hi OPNsense-Team,
would you please add my changes to support DnsHome @ AcmeClient (os-acme-client plugin):
DnsHome which is maintained by @Bodenhaltung is supported but not exposed to the webUI:
https://github.com/opnsense/ports/blob/master/security/acme.sh/pkg-plist#L73
which will be this file => https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_dnshome.sh
Or on Firewall => `/usr/local/share/examples/acme.sh/dnsapi/dns_dnshome.sh`
This changes are working without any constraints by myself.
But is there anything else that needs to be in consideration?
My Syslog:
```log
2024-04-03T09:25:06	opnsense	AcmeClient: imported ACME X.509 certificate: ***mypersonalid***.dnshome.de
2024-04-03T09:25:06	opnsense	AcmeClient: importing ACME CA: R3
2024-04-03T09:25:06	opnsense	AcmeClient: …
```
> security/acme-client: Add support for dnshome DNS API

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Add: Simple Load Balancing support of Upstreams with the random policy, by allowing multiple Upstream Domains in Handlers. A passive health check can be set too.
- I would still like to sneak this in for v1.5.4, it was easy to implement and it was requested.
- In terms of load balancing, this is probably the most I will offer. There is a multitude of options, but the passive health check duration combined with being able to set multiple upstreams was the most user friendly and straight forward choice.
Reference: 
- https://forum.opnsense.org/index.php?topic=39951.0
- https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing
> www/caddy: Add simple load balancing

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
A small fix that addresses too strict input validation.
PR: https://forum.opnsense.org/index.php?topic=40019.0
Reference: https://caddy.community/t/create-wildcard-cert-with-other-sans-too/16322
The input validation prevented the creation of ```example.com``` at the same time as ```*.example.com```
I thought that was necessary when I created the validation model, but it prevents this valid configuration that will be needed in some circumstances.
> www/caddy: Fix input validation - allow wildcard domains and base domains at the same time

- www/caddy/Makefile
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Migrations/M1_1_7.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Migrations/M1_1_8.php
This migration script empties out "on" and "none" options that were replaced with empty values by the referenced commit in os-caddy-1.5.4. It fixes the regression that Caddy will refuse to start because invalid values for AutoHttps and DnsProvider will remain stored in the config without a manual config change from the user.
Compare to commit that caused regression: https://github.com/opnsense/plugins/commit/a628ebfc0682c0f27ec59b6a605dbeff8bd52765
Issue was tracked multiple times:
https://forum.opnsense.org/index.php?topic=40075.0 
https://github.com/opnsense/plugins/pull/3930
https://github.com/opnsense/plugins/issues/3917#issuecomment-2064230068
> www/caddy: Create Migration script that fixes issue with Caddy not being able to start. (Regression in 1.5.4)

- www/caddy/Makefile
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
Since a stray ":" when leaving the port empty could cause confusion, I have opted to replace it with a "space".
**Old display:**
example.com:
example.com:443
**Fixed display:**
example.com
example.com 443
(Compare to: https://github.com/opnsense/plugins/issues/3917#issuecomment-2064230068 )
> www/caddy: Change display of domain and port combination in Model Relation Field

- net-mgmt/zabbix-proxy/Makefile
- net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf.in
Closes #3921.
Regression was introduced in 26e6379874d56190e409c07c37cb12a58679c1ff.
> net-mgmt/zabbix-proxy: fix syntax error

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/logsettings.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Sometimes it is necessary to enable the debug logs for troubleshooting purposes.
> www/caddy: Select global log level

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
Having a big configuration is hard, the items all reference each other, but each bootgrid has multiple domains, subdomains, handlers... it's hard to get an overview of a single item.
This new filter selectpicker solves it.
It shows up conditionally in the Domain/Subdomain Tab, and Handler Tab. It is shared between them. Selecting one or multiple domains manipulates the output of the Search Function to only show items that have the selected domains "reverse" UUIDs referenced.
When nothing is selected, all items are returned.
> www/caddy: Selectpicker that can filter the Domain, Subdomain and Handlers by selected Domain

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/3929
This one can cause a lot of pain. It took almost two months to track this down. I had this issue too and didn't understand for quite a while why it was happening.
I had a chat with Francis Lavoie (one of the Caddy contributers and devs) and he pointed me to the way Caddy handles open connections and streams. (but it was not straight forward that it was exactly this option at first)
Caddy, by default, tries to keep all connections and streams open, and waits for clients to close them gracefully. This means, it can wait **indefinitely** when a reload, or stop action happens. Which makes Caddy seem frozen, and the apply in the GUI hang forever.
https://caddyserver.com/docs/caddyfile/options#grace-period
> www/caddy: Fix reload/stop of caddy being infinite when websocket streams of clients are open

- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeCommon.php
Match acme.sh settings where debug 2 should have corresponding syslog = 8, and debug 3 should have corresponding syslog = 9. Refer to levels as defined in [acme.sh line 133](https://github.com/acmesh-official/acme.sh/blob/master/acme.sh#L133)
Fixes: https://github.com/opnsense/plugins/issues/3933
> security/acme-client: Update Syslog Debug Levels to match acme.sh

- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
It is valid to use the `tls_server_name` option, and most other options, inside a `transport_http` or `transport_ntlm` block without having an invalid configuration. For some configurations, it seems to be required to only have `tls_server_name` inside `transport_http`.
At the same time, a constraint was added to `tls` and `ntlm` because they depend on each other, also in the template.
Fixes: https://forum.opnsense.org/index.php?topic=39951.msg197303#msg197303
> www/caddy: template fix tls_server_name option

- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
general.volt
Because the "Apply" button triggers "saveFormToEndpoint" to save the form before continuing, the "callback_fail" has to trigger when the validation fails to reject the deferred object. Otherwise, the apply button can get stuck indefinitely.
Also, the "disable_dialog" has been set to false, in order to show the validation dialog. Since there are multiple tabs, the validation result could be hidden to the user otherwise.
Give the "Save" button the same treatment as the "Apply" button, using SimpleActionButton for better User Feedback, and also displaying the error dialog when the validation failed.
> www/caddy: general.volt - Improve Save and Apply buttons

- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
All of the declared variables in general.volt and reverse_proxy.volt are contained to their blocks and never called outside of them.
Reducing the scope of the variables with "let" instead of "var" will probably make the code more safe.
> www/caddy: Reduce scope of variables in javascript - replace var with let

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
In the upcoming Caddy Version 2.8.x, there were changes with ZeroSSL that now demand the ACME E-Mail to be filled out with a valid E-Mail address to create the ACME account.
So the field has been changed to required.
Please note that this change needs the updated general.volt from this pull request to properly display validation errors, since that has been a bug: https://github.com/opnsense/plugins/pull/3957
Reference: https://github.com/opnsense/plugins/issues/3951
> www/caddy: Change ACME E-Mail to required field

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
I forgot to allow the acme redirection option for subdomains. I recently needed it and I saw it was not there. So, now it is added.
Also it's not an advanced option anymore since it's tested thoroughly, and also needed for proper HA.
> www/caddy: HTTP-01 challenge redirection subdomain fix

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/DiagnosticsController.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/DiagnosticsController.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/ACL/ACL.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Menu/Menu.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/diagnostics.volt
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_diagnostics.py
- www/caddy/src/opnsense/service/conf/actions.d/actions_caddy.conf
Adds a new Diagnostics view in which a download button can download the latest caddy configuration with timestamp.
The autosave.json file is used, since it's json, which makes it easy to validate that it is indeed valid json. Also, it includes all custom imports which users might have dropped into the filesystem, unlike the raw Caddyfile would.
The new API endpoint /api/caddy/diagnostics/showconfig can also be invoked, to show the json configuration in the Browser in real time. There is no view for that, to keep it simple. The API is only used for the Download button, and with a button that shows the json configuration in the browser.
> www/caddy: Diagnostics View

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/DiagnosticsController.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ServiceController.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
Implement gettext _() function for localization in php controllers and model.
The last few parts where text is emitted to the user have been wrapped into short versions of the gettext() function. _()
> www/caddy: Implement gettext() function for localization in php controllers and model

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogBasicAuth.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHeader.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dnsprovider.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dynamicdns.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/logsettings.xml
Most help text was incrementally written. Mistakes have been fixed, and everything has been explained more clearly. Some of the more convoluted options were given bigger help texts.
This PR aims to improve the help text (a lot). Every option is clearly labeled and none of the vital options are hidden in advanced mode anymore.
This cleanup was long overdue and took a few hours. :D
> www/caddy: Restructure and format helptext

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_control.py
Fix that the setup.sh script is not executed with reloadssl.
It is now triggered in the overlay script ``caddy_control.py`` that maps the ``reload`` action to the ``reloadssl`` extra command of the upstream caddy rc.d script. For other actions like start/stop/restart, the setup script is still executed by /etc/rc.conf.d/caddy.
Fixes: 
* Certificates not being updated in the filesystem on config changes when a reload is triggered
* Caddyfile not being properly formatted on config changes when a reload is triggered
Who does this bug impact:
* Anybody who uses custom certificates in os-caddy-1.5.5 and triggers ``configctl caddy reload`` without pressing the ``Apply`` button.
* Anybody who uses the new ``Diagnostics`` page and sees a weirdly formatted ``Caddyfile``.
Current impact of the bug: …
> www/caddy: Fix that the setup.sh script is not executed with reloadssl

- www/caddy/pkg-descr
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Implements this:
```
dynamic_dns {
provider cloudflare
domains {
example.com *
example.com opn
example.com @
}
}
```
Wildcard domains will use "*", base domains will use "@". Subdomains continue to function as before.
Since wildcard domains don't include the base domain, separating it in the template will not cause any regressions.
Fixes: https://forum.opnsense.org/index.php?topic=38714.msg198983#msg198983
> www/caddy: Caddy dyndns wildcard domain fix

- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.php
remove depecration warning popouts so the settings can be configured again
> Haproxy.php replace $(var) to ($var) - fix depecration error that halts configuration

- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
Validation: When Auto HTTPS is enabled, ACME email is required since caddy v2.8.0+
Otherwise ZeroSSL will stop to work due to API policy changes on their side
When Auto HTTPS is turned off, the constraint doesn't apply
> www/caddy: When Auto HTTPS is enabled, ACME email is required, for caddy v2.8.0+

- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
https://github.com/caddyserver/caddy/pull/6092
`basicauth` would still work, but spawns errors in the logs. So we change it to `basic_auth` now for compliance with caddy >=v2.8.0 upstream.
> www/caddy: basicauth becomes basic_auth, for caddy v2.8.0+

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4024
- The subdomain port field has been removed, since it is unsupported. Subdomains track their ports from their parent wildcard domain.
- Filling this field out currently will result in site block that does not work properly, since it will not route requests to the upstream.
> www/caddy: Remove port from subdomain since it is unsupported.

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dnsprovider.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Requires: https://github.com/opnsense/tools/pull/415
* Add dns providers: dnsmadeeasy, bunny, civo, scaleway, acmeproxy, inwx, namedotcom, easydns, infomaniak, directadmin, hosttech, vultr, 
* Remove dns providers: godaddy (Changes in their API policy makes the API only usable if you own 50 or more domains with them, making it pretty much unusable, doubt the plugin is going to be maintained now. If this changes it will be re-added, or upon request.)
> www/caddy: Add more dns providers for os-caddy-1.5.7

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/DiagnosticsController.php
Fixes this:
``
[17-Jun-2024 16:08:31 Etc/UTC] TypeError: Cannot assign OPNsense\Mvc\Response to property OPNsense\Mvc\Dispatcher::$returnedValue of type array|string|null in /usr/local/opnsense/mvc/app/library/OPNsense/Mvc/Dispatcher.php:165
``
> www/caddy: Fix type error in configAction of DiagnosticsController.

- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
Selecting multiple ACLs under the General tab currently results in invalid config:
```
allow-transfer {
;
};
allow-query {
;
};
```
This corrects the behaviour:
```
allow-recursion {
LAN;
VPN;
};
allow-query {
LAN;
VPN;
};
```
> dns/bind: Fix handling of multiple ACLs in allow-query/allow-transfer

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://forum.opnsense.org/index.php?topic=41203
- IPv6 will be detected and put into square brackets. 
- Additionally removed that IP addresses are valid in the frontend domain, since that would break some template sections like dyndns and certificate generation, so it is unsupported in the scope of the GUI.
Before the fix:
```
handle @66b595d6-ed36-458b-83a4-b48fecb89416 {
handle {
reverse_proxy 192.168.1.1:81 2003::1:81 example.com:81 fd00:00::1:81 {
}
}
}
```
After the fix:
```
handle @66b595d6-ed36-458b-83a4-b48fecb89416 {
handle {
reverse_proxy 192.168.1.1:81 [2003::1]:81 example.com:81 [fd00:00::1]:81 {
}
}
}
```
> www/caddy: Fix IPv6 address + Port combination in Caddyfile template

- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/gandi.py
Adding Gandi LiveDNS native backend support to the DDclient plugin.
Problem: while the ddclient plugin supports Gandi when using the ddclient backend, support is absent from the native backend.
I used the cloudflare.py and dyndns2.py files as a template for gandi.py.
What needs to be configured in the plugin web interface for it to work:
Password (API key / personal access token), zone, hostname (host only, not the FQDN), check IP method.
Possible issues:
Not all fields in the opnsense web interface are used. Specifically username, resource ID, and force SSL.
Gandi appears in the bottom of the service list, instead of being sorted alphabetically. I'm unsure how to fix this.
I only check for a 2xx response to determine success or failure. This could be improved by something as simple as …
> Added Gandi support to ddclient native backend.

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/GeneralController.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/authprovider.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeAuthProvider
Fixes: https://github.com/opnsense/plugins/issues/4056
This adds a generic and standard approach to forward_auth: https://caddyserver.com/docs/caddyfile/directives/forward_auth.
This implementation generates the default configuration for Authelia based on the documentation: https://caddyserver.com/docs/caddyfile/directives/forward_auth#authelia
Authelia is open source and a partner of Caddy, so this configuration is standardized. https://www.authelia.com/
Users can customize ```domain```, ```port```,```tls```, and the ```uri```. Only one Auth Provider can be serialized to the config.
```copy_headers``` are added automatically as per documentation standard without customization options.
To use it, the Forward Auth Provider has to be configured in "General Settings - Auth Provider". …
> www/caddy: Add forward_auth functionality, auth provider Authelia added.

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4065
Adds following options:
- `http_port`: https://caddyserver.com/docs/caddyfile/options#http-port
- `https_port`: https://caddyserver.com/docs/caddyfile/options#https-port
`http_port` and `https_port` can be chosen freely. The validation catches errors when there are conflicts with the WebGUI ports.
This should satisfy advanced usecases without causing regressions.
> www/caddy: Allow bind to non standard ports

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Replace `tls_trusted_ca_certs` with `tls_trust_pool file`.
`tls_trusted_ca_certs` has been deprecated.
https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#tls_trust_pool
No functional change.
> www/caddy: Replace tls_trusted_ca_certs with tls_trust_pool file

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- Theoretically, NTLM only hard codes the transport http to `versions 1.1` as `transport http_ntlm` before the option `versions` in `transport http` existed. So, NTLM could be replaced by setting http `versions 1.1`., since NTLM always requires the full header being sent. HTTP `versions 2` only sends the header one time, and that makes Outlook fail to authenticate.
- At the same time, this also adds support for HTTP/3 `versions 3` to the upstream, which is included in the latest Caddy version 2.8.4 we have rolled out.
> www/caddy: Add HTTP version selection. Mark NTLM as deprecated.

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js
- www/caddy/src/opnsense/www/js/widgets/CaddyDomain.js
Some applications need a longer keepalive or the keepalive turned off. (Also known as connection timeout)
(e.g. Exchange Active Sync, other Microsoft services.)
`keepalive` https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#keepalive
This only changes `transport http`. In `transport http_ntlm` the keepalive is turned off automatically, so this setting won't be rendered there.
NTLM is moved back to standard options since it can't be replaced.
> www/caddy: Add HTTP keepalive to handler, revert NTLM deprecation.

- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
The previous help text left me confused about what enabling these settings would do. I think this new text makes it more clear that these settings only add an `if () { redirect }`.
> www/nginx: Update help text to clarify https redirect actions

- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/general.xml
The Recursion field on the Configuration page does not allow multiple selections. This was added in 1.26 for Transfers and Queries but is broken for Recursion. The model already has `<Multiple>Y</Multiple>` and this PR fixes the controller.
> dns/bind: Fix multiple select on Recursion field

- www/caddy/src/opnsense/www/js/widgets/CaddyCertificate.js
There were two ajaxGet, and I forgot to rename one into ajaxCall.
> www/caddy: Fix CaddyCertificate.js not loading

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsEasydns.php
Changes an undeclared constant to a quoted string. Also fixes some (very minor) capitalization.
Fixes #4067
> security/acme-client: fix EasyDNS variable assignment

- www/nginx/Makefile
- www/nginx/pkg-descr
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/httpserver.xml
- www/nginx/src/opnsense/mvc/app/controllers/OPNsense/Nginx/forms/location.xml
- www/nginx/src/opnsense/mvc/app/models/OPNsense/Nginx/Nginx.xml
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/http.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/location.conf
- www/nginx/src/opnsense/service/templates/OPNsense/Nginx/webgui.conf
Hi!
more quick fixes than anything new, but still )
* Add the option to not log TLS handshakes
* Remove obsolete http2_push_preload directive
* Migrate from the deprecated 'listen … http2' directive to the 'http2' directive
ref.:
https://github.com/opnsense/plugins/issues/3854
https://forum.opnsense.org/index.php?topic=41415.0
https://nginx.org/en/CHANGES (1.25.1 version changes)
@fabianfrz please take a look when you have time
Thanks!
> www/nginx: 1.34

- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
Up for discussion, was the best workaround I could find with the least impact to the existing structure of the general view.
Also, when it breaks in the future (For example if the "SaveFormToEndpoint" won't return validation errors anymore (please, don't change this function)), it won't break any functionality.
Fixes: https://github.com/opnsense/plugins/issues/4086
> www/caddy: Create custom displayValidationErrors function in general.volt

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
For a first time user, the UI of the Caddy plugin can look a bit intimidating on the domain landing page in Reverse Proxy.
This PR tries to improve it without adding too much trickery, keeping it simple so it won't break in the future.
------
- Two buttons are added, that will programmatically change tabs and trigger add dialogues.
- Step 1: Add Domain -> The tab is changed to the domain tab, and the add domain button is clicked automatically
- Step 2: Add Upstream -> Same, but the add handler button is clicked
- These buttons guide first time users intuitively.
------
- Subdomains are in their own Tab now, uncluttering the UI on the main domain page. This puts the normal domains into clear focus, which should be the primary entry point for anybody.
- As soon as a wildcard domain is …
> www/caddy: Add buttons to guide users, conditionally hide subdomain tab, simplify forms

- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
Fixes #3975 
FreeRADIUS allows a `:` character in the username and password. This update is especially useful for MAC-based authentication where you might want to copy-paste a MAC address for the username and password.
```
Fetched 1207358 via https://github.com/chelming/plugins
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From 120735808a1bdcdfec7a85897a252d0e9b8dcfa4 Mon Sep 17 00:00:00 2001
|From: Chris Helming <chris.helming@gmail.com>
|Date: Mon, 13 May 2024 10:21:33 -0400
|Subject: [PATCH] allow : in FreeRADIUS user and password
|
|---
| .../OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml    | 4 ++--
| .../src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml  | 4 ++--
| 2 files changed, 4 insertions(+), 4 …
```
> net/freeradius: Allow `:` in user and password

- security/etpro-telemetry/src/opnsense/www/js/widgets/ETProTelemetry.js
The API returns "sensor_status":"ACTIVE", which is upper case. The widget logic compares it to "active", which makes the widget fail to show any data. Converting "ACTIVE" to lower case solves that issue.
Reference: https://forum.opnsense.org/index.php?topic=41772.0
I use it too so I know it works now.
> security/etpro-telemetry: Fix widget not showing any data

- net/ftp-proxy/Makefile
- net/ftp-proxy/src/opnsense/mvc/app/controllers/OPNsense/FtpProxy/Api/ServiceController.php
Fixes: https://github.com/opnsense/plugins/issues/4129
Added checks to ensure $this->request is set before accessing it.
Error: Typed property OPNsense\Mvc\Controller::$request must not be accessed before initialization in /usr/local/opnsense/mvc/app/controllers/OPNsense/FtpProxy/Api/ServiceController.php:52
> net/ftp-proxy: Fix php errors in ServiceController

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
This PR adds:
`layer4.matchers.remote_ip - matches connections based on remote IP (or CIDR range).`
Configuration example (generated Caddyfile):
- With Access List: Allow IPs 192.168.1.1 and 10.0.04 to access SSH on 10.0.0.10:22
- Without Access List: Allow any IPs to access http host opnsense.example.com on 10.0.0.10:8443
```
{
servers {
listener_wrappers {
layer4 {
@797661c7-8925-4bc5-88c1-2dda4682194c ssh
route @797661c7-8925-4bc5-88c1-2dda4682194c {
subroute {
@allowed_ips remote_ip 192.168.1.1 10.0.0.4
route @allowed_ips {
proxy 10.0.0.10:22 {
}
}
}
}
@85a414c7-2142-4332-9917-1995aeb887aa http host opnsense.example.com
route @85a414c7-2142-4332-9917-1995aeb887aa {
proxy 10.0.0.10:8443 {
}
}
route
}
tls
}
}
}
```
Tested it and it works fine.
The final piece in the puzzle that was …
> www/caddy: Add remote_ip matcher for access list functionality in Layer4 proxy

- dns/ddclient/src/opnsense/www/js/widgets/Dyndns.js
This fixes the little Todo I still had in it.
Now the headers will only show when the widget is in the expanded state.
As soon as it is in a collapsed state (smaller than 320px) the headers will disappear.
> dns/ddclient: Hide and show dyndnsTable headers dynamically

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
Added cloudflare as a checkip provider for ddclient / DynDNS.
Cloudflare provides an information page at [https://1.1.1.1/cdn-cgi/trace](https://1.1.1.1/cdn-cgi/trace), which returns the requesting clients IP address.
The benefit is that the connection is using a direct IP (so no DNS lookup) and it is a geo multi-cast server deployment.
This leads to a near instant response time compared to other services for IP lookups.
The return format required ignoring the `h=1.1.1.1` IP value, which reflects the HTTP host header used in the request.
> ddclient plugin: Added cloudflare to checkip providers

- sysutils/smart/src/opnsense/scripts/OPNsense/Smart/detailed_list.sh
- sysutils/smart/src/opnsense/service/conf/actions.d/actions_smart.conf
FreeBSD 14 changed from the nvd driver to the nda driver for x86. This change modifies the smart service to utilize the new driver name on the UI and the backend script that pulls the smartctl data (thanks @jbilac!). Issue https://github.com/opnsense/plugins/issues/4155
https://www.freebsd.org/releases/14.0R/relnotes/
https://cgit.freebsd.org/src/commit/?id=bdc81eeda05d
> smart plugin: nvd to nda

- net/freeradius/Makefile
- net/freeradius/pkg-descr
- net/freeradius/src/etc/inc/plugins.inc.d/freeradius.inc
Hi all,
this small PR adds remote syslog support for the freeradius plugin, so that the plugin is listed in the applications list for a remote destination. It was only necessary to implement the `freeradius_syslog()` function since the logging mechanism to syslog was already there. 
To test this, it is required to set the `Log to File or Syslog` option of the freeradius plugin to `syslog`.
If any changes are required to be compliant with any rules, just let me know.
> net/freeradius: Added remote syslog support (#3990)

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
With the sunset of Google Domains (and migration to Square Space), https://domains.google.com/checkip (used by OPNsense checkip) is no longer working.
Reference:
https://github.com/ddclient/ddclient/issues/622
> ddclient plugin: Removed deprecated domains.google.com/checkip

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
* Rewrote dyndns check-ip to use `re.finditer`, which is a bit cleaner
* Any IP results which are equal to the requested hostname IP are now ignored, this resolves the cloudflare `1.1.1.1` or `2606:4700:4700::1111` returned in results issue in a constructive re-usable way.
* Note, it looked like there was a small bug in the previous cloudflare added option as well, it was marked as `<web_dyndns>cloudflare</web_dyndns>`
* As mentioned before the new IP based cloudflare options are considerably faster (near-instant) compared to the pre-existing options.
Test results across all current available check-ip options:
|Provider|HTTP|HTTPS|IPv4|IPv6
|--|--|--|--|--|
|cloudflare|:x:|:white_check_mark:|:white_check_mark:|:white_check_mark:
|cloudflare-ipv4|:x:|:white_check_mark:|:white_check_mark::ex …
> Refactored dyndns check-ip

- Mk/plugins.mk
I ran into problems building a plugin where some of the source files have spaces in the name. Unfortunately I don't control these filenames as they are pulled in from a 3rd party open-source project. Regardless of filename sanity, it seemed that the issue was caused by inconsistent quoting of file paths in the plugins.mk file. This PR resolves that issue.
Add double-quotes to fix problems when packaging files with spaces in the filenames
> Update plugins.mk to fix missing double-quotes

- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
This one cooked for a while in the background.
Its a refactor to make the Caddyfile template better maintainable.
Most duplicate logic has been extracted to single points into macros. The cleanup makes the template shorter and the generation faster too.
From my testing, all the prior functionality still works exactly the same and I have found no regressions. Though as always, there could be one or two hidden surprises since I can't test /all/ possible setups.
> www/caddy: Refactor Caddyfile template to make it more dry

- net/wol/src/opnsense/www/js/widgets/WakeOnLan.js
if you add WOL clients in uppercase mac adresses then onlinestatus won't work. Just added a toLowerCase so the comparison always works.
> fix false negatives

- www/caddy/src/opnsense/www/js/widgets/Metadata/Caddy.xml
As discussed earlier.
The new ``lint-acl`` wants some changes to the widget ACL endpoints.
> www/caddy: Fix api endpoints in widgets via lint-acl

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4201
Caddy listens on 443/UDP since QUIC support is default on.
This PR will add the option to disable QUIC to use this protocol port combination somewhere else, e.g. for Wireguard on UDP/443.
> www/caddy: Add option to disable QUIC protocol

- dns/bind/src/opnsense/mvc/app/controllers/OPNsense/Bind/forms/dialogEditBindPrimaryDomain.xml
- dns/bind/src/opnsense/mvc/app/models/OPNsense/Bind/Domain.xml
- dns/bind/src/opnsense/service/templates/OPNsense/Bind/named.conf
This adds a zone option to allow the RNDC key to be used for transfers.
My use case for this is for [kubernetes-sig/external-dns](https://github.com/kubernetes-sigs/external-dns) to manage my cluster's DNS records with [dynamic updates](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md).
> dns/bind: Add option to allow the rndc-key for zone transfers

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHeader.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/diagnostics.volt
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/www/js/widgets/CaddyDomain.js
One of the final cleanups of the GUI.
Now I am pretty much satisfied with everything (finally). _Remind me of what I said when I try to move options around again._
Biggest change happened to the Handler dialogue, I disliked how there were so many options always visible.
- Headers and options are hidden more in advanced mode again
- http/https can be chosen explicitely (replacing the tls checkbox (yes its backwards compatible)) and some tls specific options will hide and show based on selection
- The subdomain field will only show if the subdomain tab also shows (aka a wildcard domain has been configured)
Other stuff is just some minor shuffling around but now everything feels great. This will please both newcomers and experts alike.
Handler without advanced and http and without subdomain …
> www/caddy: Handler and other dialogue form cleanup

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4223
Details:
- When no access list in a handler is chosen, it will render without as before
- If an access list is chosen, it will render inside the path handler, kinda like the forward auth directive. This prevents further processing if IPs have been matched.
There is an additional bug fix in here that fixes a typo that prevented inverted access lists being rendered correctly. If nobody tests this I will extract the bugfix and merge it in a separate PR.
EDIT:
The whole access list feature has been rewritten to be simpler and the same in the whole template
> www/caddy: Allow access lists in handlers

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_control.py
Patch behavior of caddy hanging during a reload or restart in some circumstances. This will avoid caddy waiting indefinitely when the NTLM module is active. After the Grace Period is over, there is a hard kill and restart. Since the template already regenerated the configuration, the new one will be used when Caddy starts. I think it fixes some reload issues with the Layer4 module as well, though unsure here.
It seems like Grace Period fix was not enough.
PR: https://forum.opnsense.org/index.php?topic=42664.msg212232#msg212232
PR2: https://github.com/opnsense/plugins/issues/3929 (Same as latest PR, Grace Period seemed to fix it there, but I guess its not for everyone)
PR2: https://github.com/opnsense/plugins/issues/3890  
PR3: https://github.com/opnsense/plugins/issues/3887  (This happens …
> www/caddy: Force caddy to restart if a reload takes too long

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4221
Allows for a configuration like this:
```
nextcloud.example.com {
handle /.well-known/carddav {
redir https://nextcloud.example.com/remote.php/dav/
}
handle /.well-known/caldav {
redir https://nextcloud.example.com/remote.php/dav/
}
handle {
reverse_proxy 192.168.1.10:11000 {
header_down +Strict-Transport-Security "max-age=31536000;"
}
}
}
```
Needs testing, draft for now.
> www/caddy: Add redir directive to HTTP Handler

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogAction.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/AcmeVault.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
The vault token is needed to enable the storage of keys in vault. This was not considered so far.
https://github.com/opnsense/plugins/issues/3525 discusses the issue and the reporter suggested a solution in his [blog](https://blog.infoitech.co.uk/opnsense-bugfix-acme-plugin-upload-to-vault/#1-opnsense-acme-plugin-form). This is the second step of getting the solution implemented after acme.sh merged the first fix: https://github.com/acmesh-official/acme.sh/pull/5159 and opnsense merged the [release](https://github.com/acmesh-official/acme.sh/releases/tag/3.0.8) to make it available there.
With that pull request is now possible to use vault for storing certificates for opnsense.
> security/acme-client: fix vault support, added vault token

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
The current layer 4 implementation was like a draft and feature preview.
This here adds the real deal while also cleaning it up quite a lot.
It is a quite complicated feature and will be properly documented. Though, there is quite some validation added to ensure no layer4 Route can be added that would totally break everything.
<details>
</details>
> www/caddy: Complete Layer4 routing feature

- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSUser.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/User.xml
Fixes #4115 
Allow `&` to in password
> net/freeradius: Allow `&` as a password character

- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospf6d.conf
Template for ospf6d.conf should call out ipv6, not ip, for both route-map and prefix-list.  Also, a rogue newline crept into ospf6.volt - corrupting the enabled checkboxes in the Prefix Lists tab.
> Correct minor issues in OSPF6

- net/freeradius/Makefile
- net/freeradius/pkg-descr
- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/dialogEditFreeRADIUSClient.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Client.xml
- net/freeradius/src/opnsense/service/templates/OPNsense/Freeradius/clients.conf
It is recommended for RADIUS clients to use a message authenticator for all requests to protect against the [BlastRADIUS](https://www.freeradius.org/vul_notifications/2024/07/09/blastradius.html) attack.
Further this should be enforced by the RADIUS server.
These changes add the required function to the client settings as an advanced option.
Initiated and tested in this forum thread:
https://forum.opnsense.org/index.php?topic=42094.msg207448
Kind regards,
Patrick
> net/freeradius add `require_message_authenticator` client option

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditBFDNeighbor.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BFD.php
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/BFD.xml
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bfdd.conf
closes https://github.com/opnsense/plugins/issues/4282
Although IPv6 also supports multihop, it does require a local-address to be set (https://docs.frrouting.org/en/latest/bfd.html#bfdd-commands), to avoid adding extra complexity now, start with IPv4 and see where that brings us.
> net/frr - Routing: BFD - add multihop support for IPv4.

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Layer4Controller.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/ACL/ACL.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Menu/Menu.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/layer4.volt
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
This cleans up the UI a bit to make it less convoluted.
- Layer4 is its own Menu and view now, the "Enable Layer4 Proxy" has been shifted to general settings to be immediately visible. The hidden tab was very convoluted
- Subdomains and Domains are a combined tab once more. The hidden/separate subdomains tab was very convoluted and a bad UX choice
- The subdomains selectpicker is always visible again in the Handler dialogue
- reverse_proxy.volt had a some convoluted functions removed that checked the API to determine which tabs/fields to show and to hide. Removing this made the UI like 200% faster again, it just loads instantly, improving UX a lot
- A "Clear All" button to the "Filter by Domain" selectpicker has been added. I disliked how I had to manually revert my selections in that …
> www/caddy: Put Layer4 Proxy into own menu, cleanup reverse_proxy.volt

- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
Fix WebGUI ports validation: 
- Do not validate with empty ACME email address to prevent migration issues on first install.
- Do not validate WebGUI redirect rule when WebGUI protocol is http. 
- Attach validation message additionally to Caddy HTTP and HTTPS port fields.
Fixes: https://github.com/opnsense/plugins/issues/4288
> www/caddy: Fix WebGUI ports validation (by removing it)

- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Fix for [#4317](https://github.com/opnsense/plugins/issues/4317)
With this, the "ipv4 vs ipv6" will be respected, and the count is respected too.
> Fix for "ipv4 vs ipv6" and  mixed configuration on telegraf ping section.

- benchmarks/iperf/src/opnsense/mvc/app/views/OPNsense/iperf/index.volt
Sample payload:
```
{
"start_time": "2024-04-20 14:12:10 +0000",
"interface": "vtnet0",
"port": 5830,
"result": {
"start": {
"connected": [],
"version": "iperf 3.16",
"system_info": "FreeBSD OPNsense.localdomain 13.2-RELEASE-p11 FreeBSD 13.2-RELEASE-p11 stable\/24.1-n255007-1d6e165fb40 SMP amd64"
},
"intervals": [],
"end": [],
"error": "error - unable to receive parameters from client: "
}
},
```
Considered introducing JSDoc to document the payload structure, but it ultimately is defined by `iperf3 -J` (where `-J` means output in json: https://iperf.fr/iperf-doc.php#3doc). Too difficult to clearly define the expected payload structure.
> benchmarks/iperf: fix JS TypeError when parsing iperf result with an error (#3925)

- security/etpro-telemetry/src/opnsense/scripts/etpro_telemetry/send_telemetry.py
PR: https://forum.opnsense.org/index.php?topic=42759.0
See man syslog(3) and https://github.com/opnsense/core/issues/7101
This log message is of no interest to anyone beyond debugging telemetry functionality.
>  security/etpro-telemetry: Lower logging priority

- security/tinc/src/opnsense/scripts/OPNsense/Tinc/tincd.py
I noticed the following warning at boot:
```
<118>/usr/local/opnsense/scripts/OPNsense/Tinc/tincd.py:34: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
```
This commit Remove "pipes" Python module dependency.
> Prepare Tinc plugin for Python 3.13

- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Why its not needed anymore: https://github.com/mholt/caddy-l4/pull/248#issuecomment-2400513639
It was also the main cause of this: https://github.com/mholt/caddy-l4/issues/250
Together with building with go1.23 (which has kyber support): https://github.com/opnsense/ports/pull/204
And updating the layer4 module to the main branch without the workaround patch: https://github.com/opnsense/tools/pull/440
The layer4 module is back on the main branch and can use the newer features and bugfixes again.
> www/caddy: Remove default route from layer4 since its obsolete

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Api/ReverseProxyController.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/Layer4Controller.php
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4Openvpn.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.php
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/layer4.volt
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
Adds these: 
OpenVPN https://github.com/mholt/caddy-l4/pull/251
Winbox https://github.com/mholt/caddy-l4/pull/255
QUIC https://github.com/mholt/caddy-l4/pull/262
Sample configuration for OpenVPN (generated by template) to compare with sample config of above PR:
```
{
layer4 {
import /usr/local/etc/caddy/caddy.d/*.layer4global
udp/:8843 {
@72e3a520-7c15-49de-a4dc-e45ab1cba40a openvpn {
modes auth
auth_digest sha256
group_key_direction normal
group_key_file /var/db/caddy/data/caddy/certificates/temp/b0bf7f56-7a84-4e24-9851-785bedc0b432.key
}
route @72e3a520-7c15-49de-a4dc-e45ab1cba40a {
proxy udp/192.168.1.1:1195 {
}
}
@5b0fd94e-781c-4d48-86f0-a14a5c5c7ad4 openvpn {
modes auth
auth_digest sha256
group_key_direction inverse
group_key_file …
```
> www/caddy: Add Layer4 openvpn, winbox and quic matcher

- security/wazuh-agent/src/opnsense/mvc/app/controllers/OPNsense/WazuhAgent/forms/settings.xml
- security/wazuh-agent/src/opnsense/mvc/app/models/OPNsense/WazuhAgent/WazuhAgent.xml
- security/wazuh-agent/src/opnsense/service/templates/OPNsense/WazuhAgent/ossec.conf
closes: #4293
this pr adds options to configure the ports to use for sending events and for initial enrollment of the agent. defaults are 1514/1515, respectively, as wazuh uses these by default.
this also renames the header from "Authentication" to "Enrollment" as the `authd.pass` file is also only used for enrollment. i'm not sure whether it's possible to change the settings keys, so these have been left as `agent.auth.*`.
cc: @AdSchellevis
> security/wazuh-agent: implement options to change server ports

- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4368
This got a bit more spicy than expected since I had to deduplicate, change and cleanup some logic in the template.
I handled `http://` and `https://` indirectly before by adding `tls`. Now its added as protocol in front of each domain:port (except http which is the default).
To prevent options that are incompatible to be rendered inside the `transport_http` block its logic was changed too.
To make `reverse_proxy` and `redir` the same, the logic for setting the domains has been centralized.
> www/caddy: Add h2c protocol to handler

- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
its the correct way to configure ping to use the "binary" file. (the "count" is a parameter passed to the ping binary).
> Fix in ping telegraf plugin, the "count" to be a "arguments".

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/layer4.volt
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
Fixes: https://github.com/opnsense/plugins/issues/4378
Adds most of this: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing
`reverse_proxy` (HTTP Handler) can do `lb_policy`, `lb_retries`,`lb_try_duration`,`lb_try_interval`
`proxy` (Layer4) can only do `lb_policy`
Load balancing options that need further configuration have not been added.
Additionally all passive health check options have been added as well since they go habd in hand with the load balancing.
This hopefully exposed most options required for load balancing.
Since none of the options require a master/detail they all live in the existing forms.
> www/caddy: Add Load Balancing options to Reverse Proxy and Layer4 Proxy

- net/haproxy/src/opnsense/service/conf/actions.d/actions_haproxy.conf
fix for opnsense/plugins#4035
Workaround for this ligering issue is simple and well described, but it seems that noone has created a PR yet. So here it is.
> net/haproxy: Fix "not all arguments converted during string formatting" in cert_sync

- www/caddy/Makefile
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_diagnostics.py
Wildcard certificates are `wildcard_.example.com` in the filesystem, but the widget requires `*.example.com`.
This little patch should fix it.
PR: https://forum.opnsense.org/index.php?topic=44440.0
> www/caddy: Fix wildcard certificate extraction for widget

- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf
Gandi and GoDaddy both support setting the TTL using the ddclient tool.
Not setting pose an issue at least for Gandi which set the value to 18000 seconds, which is too high.
Letting the user to set 300 for example helps reducing service interruption when the IP changes.
> Add ddclient TTL configuration in Gandi and GoDaddy

- net/mdns-repeater/Makefile
- net/mdns-repeater/pkg-descr
- net/mdns-repeater/src/etc/inc/plugins.inc.d/mdnsrepeater.inc
- net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/Api/ServiceController.php
- net/mdns-repeater/src/opnsense/mvc/app/controllers/OPNsense/MDNSRepeater/forms/general.xml
- net/mdns-repeater/src/opnsense/mvc/app/models/OPNsense/MDNSRepeater/MDNSRepeater.xml
- net/mdns-repeater/src/opnsense/mvc/app/views/OPNsense/MDNSRepeater/index.volt
- net/mdns-repeater/src/opnsense/service/conf/actions.d/actions_mdnsrepeater.conf
- net/mdns-repeater/src/opnsense/service/templates/OPNsense/MDNSRepeater/mdnsrepeater
A general cleanup of the plugin code because I was tracing a bug in the view with tokenized fields but it caused a chain reaction that resulted in this PR.
This includes: https://github.com/opnsense/plugins/pull/4362
> net/mdns-repeater: Modernize plugin code; Add blocklist support (contributed by Kodehyrden)

- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Long story short:
`reverse_proxy` implies it is "http://" when it is empty default
`redir` implies it is an URI when it is an empty default
So, gotta attach http:// to redir again to fix regression introduced here: https://github.com/opnsense/plugins/pull/4369
PR: https://forum.opnsense.org/index.php?topic=44542.0
> www/caddy: Fix redirect regression

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/rc.conf.d/caddy
Fixes: opnsense/plugins#4402
When Caddy is given a Unix socket for its admin interface, and no permissions are supplied, the permissions become `0200` by default ([link](https://github.com/caddyserver/caddy/blob/v2.8.4/internal/sockets.go#L34-L55)).
As part of applying changes, OPNsense ends up running a script which results in the owner of `/var/run/caddy/caddy.sock` becoming `root`, thus when Caddy is running under the `www` user it can no longer perform admin operations like stop/restart.
This proposed change would provide custom permissions to Caddy, which is already catered for in the upstream code, to make sure that no matter who the **owner** of `caddy.sock` is, the `www` **group** can write to this socket. This way, whether Caddy is running under the `root` user or the `www` user, …
> opnsense/plugins#4402: configure custom permissions on caddy.sock

- security/tailscale/Makefile
- security/tailscale/pkg-descr
- security/tailscale/src/opnsense/mvc/app/views/OPNsense/Tailscale/status.volt
- security/tailscale/src/opnsense/service/templates/OPNsense/Tailscale/rc.conf.d
Update security/tailscale template to enforce presence of "--auth-key" attribute in Tailscale up_args - fixes #4394
> enforce --auth-key param in template preventing prompt for auth on boot

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsMydnsjp.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
MyDNS.JP is integrated in acme.sh. This PR adds support in the interface.
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_mydnsjp
> security/acme-client: Add support for MyDNS.JP DNS API

- www/squid/src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
- www/squid/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
- www/squid/src/opnsense/service/templates/OPNsense/Proxy/squid.conf
This pull-request enables the squid "workers" configuration-directive (https://www.squid-cache.org/Doc/config/workers/) which gives the user the possibility to set squid workers according to their needs.
The default value of 1 represents one main process, which is the current default.
For more information regarding scaling see https://wiki.squid-cache.org/Features/SmpScale
> www/squid: Add SMP support

- security/clamav/src/opnsense/scripts/OPNsense/ClamAV/freshclam.sh
This one was forgotten to rename.
> security/clamav: Fix typo in freshclam.sh

- net/frr/Makefile
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/BfdController.php
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/GeneralController.php
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/ServiceController.php
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bfd.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/bgp.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/general.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf6.volt
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/rip.volt
Apply frontend / api changes to align more with current core patterns.
This has been on my list for quite some time, but finally found some time to cleanup the frontend code.
> net/frr - style cleanup and unify forms

- mail/rspamd/src/opnsense/service/templates/OPNsense/Rspamd/greylist.conf
Hi,
this Bug ist still exist in rspamd plugin
https://forum.opnsense.org/index.php?topic=30204.0
https://forum.opnsense.org/index.php?topic=21665.0
> fix wrong key in greylist.conf template for whitelisted ips

- net/freeradius/src/opnsense/mvc/app/controllers/OPNsense/Freeradius/forms/eap.xml
- net/freeradius/src/opnsense/mvc/app/models/OPNsense/Freeradius/Eap.xml
- net/freeradius/src/opnsense/scripts/Freeradius/generate_certs.php
**Description:**  
This PR enables the configuration of multiple CA certificates for EAP-TLS authentication in FreeRADIUS. This is useful for environments where client devices (e.g., laptops, desktops) use certificates from an internal private CA, while devices like VoIP phones and printers use certificates issued by their vendor's CA.
The configuration aligns with the FreeRADIUS documentation regarding the "ca_file" directive, which supports multiple CA certificates:  
[[FreeRADIUS Documentation - ca_file](https://networkradius.com/doc/current/raddb/tls/tls-config_tls-common.html)](https://networkradius.com/doc/current/raddb/tls/tls-config_tls-common.html)
To implement this, the controller and model for eap was modified. And the "generate_certs.php" script was updated to handle and …
> net/freeradius: EAP-TLS with multiple CAs

- www/squid/src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
- www/squid/src/opnsense/service/templates/OPNsense/Syslog/local/squid_access.conf
Sorry, i somehow messed up the regex in squid_access.conf..
Also it is necessary to drop a note about not using local cache in combination with multiple workers as our cache_dir is of the type ufs and is not smp-aware.  Rock is currently the only smp-aware cache_dir type.
> www/squid: Regex + hint

- www/caddy/src/opnsense/mvc/app/library/OPNsense/System/Status/CaddyOverrideStatus.php
Implements a banner like this when custom configuration imports are used:
https://github.com/opnsense/core/commit/fd39bafe7288689e39a4350188535428043981ad
Fixes: https://github.com/opnsense/plugins/issues/4244
> www/caddy: Add persistent banner notification if custom imports are used

- security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/upload_sftp.php
export correct array element for ca certs. fixes #4477
> security/acme-client: fix export of ca certs for SFTP upload automation

- security/acme-client/Makefile
- security/acme-client/pkg-descr
- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogCertificate.xml
@fichtner Let's Encrypt is going to make a huge change later this month. This will probably affect many users (and may cause a lot support requests). Is there a chance that you could add a note to the OPNsense 25.1 release notes? Something like this may be sufficient:
> BREAKING CHANGE: Let's Encrypt [ends support](https://letsencrypt.org/2024/12/05/ending-ocsp/) for the OCSP Must Staple
> extension on 30.01.2025. Issuance requests will fail if this option is
> still enabled past this date.
This note is also in the plugin changelog, but it's too easy to miss this important change.
> security/acme-client: release 4.8

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
It's an upstream issue but it could be mitigated with a hotfix.
Explanation here: https://github.com/opnsense/plugins/issues/4471#issuecomment-2599639355
Since this mitigation changes configuration via a forced migration, its a kinda dirty workaround. We do not /have/ to do this, but its a short term solution.
> www/caddy: Disable HTTP/3 to mitigate status 400 issue when reverse proxying the OPNsense WebGUI

- dns/ddclient/src/opnsense/mvc/app/controllers/OPNsense/DynDNS/forms/dialogAccount.xml
- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/__init__.py
- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
- dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.json
https://github.com/opnsense/plugins/pull/4491
> dns/ddclient: Add support for altering IPv6 addresses in ddclient plugin

- security/maltrail/src/opnsense/service/templates/OPNsense/Maltrail/maltrail.conf
This hard-coded path does not exist on OPNsense at all
> Fixing non-existing path in maltrail.conf

- security/tailscale/src/opnsense/mvc/app/controllers/OPNsense/Tailscale/forms/settings.xml
- security/tailscale/src/opnsense/mvc/app/models/OPNsense/Tailscale/Settings.xml
- security/tailscale/src/opnsense/service/templates/OPNsense/Tailscale/rc.conf.d
If the Tailscale (or Headscale) control plane is unavailable at OPNsense boot time then the boot will stall because `tailscale up` by default will wait indefinitely to connect.  This seems undesirable, even in my case where I use Tailscale rather than a self hosted instance, an outage may be unlikely but I would still rather OPNsense didn't get stuck booting up if I rebooted during some Tailscale outage, or even if my Internet connection were simply down and I was rebooting as part of diagnosing that.
I've made the timeout configurable, defaulting to 10 seconds, which feels like it should be long enough to connect in the majority of cases.  If timeout does occur, the daemon still runs, and will reconnect on its own once the control plane is available again.
ref forum thread: …
> security/tailscale: make login timeout (tailscale up --timeout parameter) configurable

- security/tailscale/src/opnsense/mvc/app/controllers/OPNsense/Tailscale/forms/settings.xml
- security/tailscale/src/opnsense/mvc/app/models/OPNsense/Tailscale/FieldTypes/ExitNodeField.php
- security/tailscale/src/opnsense/mvc/app/models/OPNsense/Tailscale/Settings.xml
- security/tailscale/src/opnsense/mvc/app/views/OPNsense/Tailscale/settings.volt
- security/tailscale/src/opnsense/mvc/app/views/OPNsense/Tailscale/status.volt
- security/tailscale/src/opnsense/service/templates/OPNsense/Tailscale/rc.conf.d
I've been playing around with Tailscale since the new plugin was added and I was looking at getting OPNsense to use a remote exit node.  This achieves the Tailscale part of doing that - the rest needs doing separately with NAT/Firewall rules.
Would this be useful for inclusion in the plugin at all?
> security/tailscale: Allow use of an exit node

- security/intrusion-detection-content-pt-open/LICENSE
- security/intrusion-detection-content-pt-open/Makefile
- security/intrusion-detection-content-pt-open/pkg-descr
- security/intrusion-detection-content-pt-open/src/opnsense/scripts/suricata/metadata/rules/pt-open.xml
Hi!
The rather interesting IDS rules from Positive Technologies are available again.
It would be great to add the ability to install them in OPNsense.
Thanks!
> security/intrusion-detection-content-pt-open: (Re-)Add PT IDS-rules plugin

- security/acme-client/src/opnsense/mvc/app/controllers/OPNsense/AcmeClient/forms/dialogValidation.xml
- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeValidation/DnsScaleway.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
Support for Scaleway DNS challenge, available in acme.sh since 2020: https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_scaleway.sh
Displays `API Key` to match Scaleway UI:
but using `SCALEWAY_API_TOKEN` as this is the name of the value in acme.sh
> security/acme-client: Add support for Scaleway DNS challenge

- sysutils/sftp-backup/Makefile
- sysutils/sftp-backup/pkg-descr
- sysutils/sftp-backup/src/opnsense/mvc/app/library/OPNsense/Backup/Sftp.php
- sysutils/sftp-backup/src/opnsense/mvc/app/models/OPNsense/Backup/SftpSettings.php
- sysutils/sftp-backup/src/opnsense/mvc/app/models/OPNsense/Backup/SftpSettings.xml
Add a simple backup option using secure copy (sftp).
Easy to use with any unix/linux target server offering ssh services. Just add a public key to `~/.ssh/authorized_keys`  (`~` = users home directory), upload a matching private key and set the remote location (for example `sftp://root@192.168.1.1//root/test_backup`)
[ssh-keygen](https://man.openbsd.org/ssh-keygen.1) can be used to generate a keypair.
> sysutils/sftp-backup : add sftp backup connector

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeDnsProvider
Fixes: https://github.com/opnsense/plugins/issues/4543
> www/caddy: Update DNS Provider list and improve maintainability

- www/squid/src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
- www/squid/src/opnsense/mvc/app/models/OPNsense/Proxy/Proxy.xml
- www/squid/src/opnsense/service/templates/OPNsense/Proxy/squid.conf
This pull-request changes the type of the squid cache_dir from ufs to rock.
We already included the workers in https://github.com/opnsense/plugins/pull/4393 for smp-mode and should also move to rock as the cach_dir type, as rock is currently the only SMP-aware cache_dir type.
Testing happened on OPNSense 24.7.12 with enabled local ufs cache.
Switched to rock and it initialises the rock db in /var/squid/cache.
The pre-rock ufs data stays there until a reset via Squid Web Proxy --> Administration -->  Support --> Reset is done.
More information: http://www.squid-cache.org/Doc/config/cache_dir/
> www/squid: change cache_dir from ufs to rock

- www/squid/src/opnsense/mvc/app/controllers/OPNsense/Proxy/forms/main.xml
Removes the hint introduced by https://github.com/opnsense/plugins/pull/4470 as we now have https://github.com/opnsense/plugins/pull/4487 which supports cache in combination with workers.
> Update squid workers helptext.

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
I didn't notice this for quite a while.
> www/caddy: Add missing selectpicker style to dropdowns which have other styles attached

- net/turnserver/Makefile
- net/turnserver/pkg-descr
- net/turnserver/src/etc/inc/plugins.inc.d/turnserver.inc
- net/turnserver/src/opnsense/mvc/app/controllers/OPNsense/Turnserver/Api/ServiceController.php
- net/turnserver/src/opnsense/mvc/app/controllers/OPNsense/Turnserver/Api/SettingsController.php
- net/turnserver/src/opnsense/mvc/app/controllers/OPNsense/Turnserver/IndexController.php
- net/turnserver/src/opnsense/mvc/app/controllers/OPNsense/Turnserver/forms/settings.xml
- net/turnserver/src/opnsense/mvc/app/models/OPNsense/Turnserver/ACL/ACL.xml
- net/turnserver/src/opnsense/mvc/app/models/OPNsense/Turnserver/Menu/Menu.xml
- net/turnserver/src/opnsense/mvc/app/models/OPNsense/Turnserver/Turnserver.php
- net/turnserver/src/opnsense/mvc/app/models/OPNsense/Turnserver/Turnserver.xml
- net/turnserver/src/opnsense/mvc/app/views/OPNsense/Turnserver/index.volt
- net/turnserver/src/opnsense/scripts/OPNsense/Turnserver/export_certs.php
- net/turnserver/src/opnsense/scripts/OPNsense/Turnserver/setup.sh
- net/turnserver/src/opnsense/service/conf/actions.d/actions_turnserver.conf
- net/turnserver/src/opnsense/service/templates/OPNsense/Turnserver/+TARGETS
- net/turnserver/src/opnsense/service/templates/OPNsense/Turnserver/rc.conf.d
- net/turnserver/src/opnsense/service/templates/OPNsense/Turnserver/turnserver.conf
Requires https://github.com/opnsense/tools/pull/450
Closes #4473
Tested on OPnsense standalone instances and on HA pair.
> New plugin: net/turnserver

- net/frr/Makefile
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF6.xml
@fichtner I made a small oopsy here while copy pasting.
Fixes: https://github.com/opnsense/plugins/issues/4580#issuecomment-2767842030
Compare to here: https://github.com/opnsense/plugins/blob/7bbd4557995c77f6668c8b5f97401a98a634f005/net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml#L56-L62
> net/frr: Fix wrong route redistribution option for ospf (bgp missing)

- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/ACL/ACL.xml
Fixes: https://github.com/opnsense/plugins/issues/4623
As multiple ACLs were mostly smoke and mirrors, there is just a single ACL now that matches the whole plugin.
The ACL from before is dysfunct due to non matching api paths.
> www/caddy: Change and fix ACL privileges

- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
- Show only wildcard domains in subdomain selection
- Show only wildcard domains in handler selection if a subdomain is selected
Improves UX a little more since it makes wildcard domain + subdomain selection very explicit, so proper selection is easier.
> www/caddy: Show only wildcard domains in subdomain selection

- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
https://github.com/opnsense/plugins/issues/4643
Reasons are explained in above ticket. To be merged when caddy-v2.10.0 hits the road.
> www/caddy: Revise dns providers for caddy-v2.10.0

- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
Add Akamai to checkip providers.
Supports IPv4/IPv6, IPv4 only, IPv6 only.
> dns/ddclient: Add Akamai to checkip providers.

- www/c-icap/src/etc/inc/plugins.inc.d/cicap.inc
- www/c-icap/src/opnsense/mvc/app/models/OPNsense/CICAP/Menu/Menu.xml
- www/c-icap/src/opnsense/scripts/OPNsense/CICAP/setup.sh
- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/+TARGETS
- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/c-icap.conf
- www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/newsyslog.conf
- www/c-icap/src/opnsense/service/templates/Syslog/local/cicap.conf
This commit changes the cicap log from logfile to syslog.
It also improves the previously static localserver acl with the correct serverip configured via the GUI.
Furthermore it flips the logic of the accesslog because it is enabled by default if sys_logger is enabled.
> www/c-icap: move to syslog

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
This PR adds a dropdown to Access List form to choose Request Matcher between `client_ip` and `remote_ip`.
Close #4666
> www/caddy: Add Request Matcher option to Access List

- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/general.xml
- www/caddy/src/opnsense/mvc/app/models/OPNsense/Caddy/Caddy.xml
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
Fixes: https://github.com/opnsense/plugins/issues/4672
Fixes: https://github.com/opnsense/plugins/issues/4655
Before this commit, subdomains used this pattern:
https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates
```
*.example.com {
tls {
dns <provider_name> [<params...>]
}
@foo host foo.example.com
handle @foo {
respond "Foo!"
}
}
```
But now that pattern is deprecated. A new pattern should be used.
This is to support new tls automation policies like ECH, and to automatically use existing wildcard certificates for each site block.
https://github.com/caddyserver/caddy/pull/6959
```
*.example.com {
tls {
dns <provider_name> [<params...>]
}
}
foo.example.com {
respond "Foo!"
}
```
To ease transition only the template has been adjusted, the frontend stays the same.
This …
> www/caddy: Change template generation of wildcard+subdomain pattern to support ECH and mTLS

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/Api/OspfsettingsController.php
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/OspfController.php
- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFNeighbor.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
This commit adds the possibility to configure OSPF neighbors for non-broadcast multi-access (NBMA) networks and point-to-multipoint non-broadcast networks.
The feature was also requested in the past: https://forum.opnsense.org/index.php?topic=22543.0
> net/frr: add neighbor config to ospf

- net/radsecproxy/src/opnsense/service/templates/OPNsense/RadSecProxy/radsecproxy.conf
While playing around with OPNsense and my new access points I was trying to get radius accounting working with OPNsense / RadSecProxy / Freeradius.
However, no matter what settings I tried, I couldn't get it to work.
Looks like the "AccountingServer" option is missing, so I copied the "Server" section and things started working.
> Added AccountingServer options

- www/squid/src/opnsense/service/templates/OPNsense/Proxy/squid.conf
These days I'm in a project to migrate from Sophos Proxy to OPNsense, nearly 1000 users, explicit proxy with ssl decryption and ClamAV/C-ICAP. There a couple of misconfigured site where certificate chain is incomplete and also not in OPNsense default stack. The only solution is to import by hand or ask website owner to fix it.
Now I had a new case where also importing missin certificates doesn't work and only option was this one.
To me it's fine as it says don't block connections when certificate validation fails, but we ignore this only for no-bump sites, so it shouldn't be a problem either.
Screenshot of the error:
> www/squid: Don't reject no-bump sites when certificate validation fails

- dns/ddclient/src/opnsense/mvc/app/models/OPNsense/DynDNS/DynDNS.xml
- dns/ddclient/src/opnsense/scripts/ddclient/lib/account/__init__.py
- dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:
**Describe the bug**
The current service to lookup external ip (   https://github.com/opnsense/plugins/blob/master/dns/ddclient/src/opnsense/scripts/ddclient/lib/address.py#L35) for dyndns times out (and has been doing so for ages):
```
curl https://checkip.dyndns.com/
curl: (28) Failed to connect to checkip.dyndns.com port 443 after 300103 ms: Timeout was reached
```
Subsequently no IP is displayed in GUI and no IP is send to the DNS provider.
The PR resolves the dyndns ip lookup by removing the deprentied service dyndns and add dynu ipv4 and ipv6. This will "break" lookup for some, and they will need to revist their dDNS config.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to …
> dns/ddclient: empty ip send to dns provider & replace dyndns by dynu

- security/acme-client/src/opnsense/mvc/app/library/OPNsense/AcmeClient/LeAutomation/ConfigdReloadCaddy.php
- security/acme-client/src/opnsense/mvc/app/models/OPNsense/AcmeClient/AcmeClient.xml
I would like to revisit this: https://github.com/opnsense/plugins/pull/3877
As new changes I made in Caddy will guide users with DNS Providers more to the os-acme-client, I would like them to find the correct reloading option so that they do not choose to restart caddy instead.
I could probably also solve this with documentation, but this is better UX.
More context: https://github.com/opnsense/plugins/pull/4691
Thank you for your consideration.
> security/acme-client: reload www/caddy automation added

- security/tailscale/src/opnsense/mvc/app/controllers/OPNsense/Tailscale/forms/dialogSubnet4.xml
The original help text appears to be a potential copy-and-paste leftover from an unrelated subnet field for some kind of DHCP configuration dialog.
Changes the help text so that it is contextually relevant to the plugin.
> security/tailscale: Fix subnet router dialog help text

- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/general.volt
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
Some general cleanups so that the button in general settings also uses the refactored spinner checkmark styling of the simpleActionButton.
Remove onAction in template since we use data-service-widget instead.
> www/caddy: Use simpleActionButton in general.volt

- net/frr/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf
Fixes: https://github.com/opnsense/plugins/issues/4762
I asked OP to test, so lets wait first, but when looking at the frr documentation its indeed at the wrong spot.
> net/frr: Activate peergroup in address family

- www/caddy/Makefile
- www/caddy/pkg-descr
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogAccessList.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogBasicAuth.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHandle.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogHeader.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogLayer4.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogReverseProxy.xml
- www/caddy/src/opnsense/mvc/app/controllers/OPNsense/Caddy/forms/dialogSubdomain.xml
- www/caddy/src/opnsense/mvc/app/views/OPNsense/Caddy/reverse_proxy.volt
Some small display fixes, use pixel instead of em values.
Also uses $field instead of field for some option fields in the formatter for after this commit:
https://github.com/opnsense/core/commit/f17bd8ef05f18ffaffd4509d19803fb47f2e0fea
> www/caddy: Change em into px, fix key/value display in formatter

- sysutils/nut/src/opnsense/service/templates/OPNsense/Nut/upsmon.conf
this PR relies on opnsense/core/pull/8948 
according to #4513 nut's netclient option needs IPv6 to be in brackets
considering the line in `/usr/local/etc/nut/upsmon.conf`
is `UPSName@[2001:db8::1]:3493` with a port and all it's probably save to assume it does need brackets
Closes #4513
> sysutils/nut(fix): IPv6 addresses in Netclient

- security/crowdsec/src/opnsense/mvc/app/views/OPNsense/CrowdSec/alerts.volt
Fixes: https://github.com/opnsense/plugins/issues/4837
@fichtner Not our fault in terms of framework but an easy fix so I quickly did it.
> security/crowdsec: Fix alert time not showing in grid

- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/diagnostics.volt
and remove some data-width as they break the grid
Fixes: https://github.com/opnsense/plugins/issues/4841
Already tested by me.
> net/frr: Change column ids in ospf diagnostics as frr10 returns different keys

- security/netbird/Makefile
- security/netbird/src/opnsense/service/templates/OPNsense/Netbird/netbird
This change fixes an issue that prevented the NetBird service from starting normally using `service netbird start`.
The configuration template was incorrectly referencing the service enable flag using:
```jinja
{% if OPNsense.netbird.general.enable == '1' %}
```
This resulted in `netbird_enable="NO"` always being rendered, regardless of the actual enabled state in the UI settings. Consequently, the service could not be started using:
```
service netbird start
```
and instead required manual invocation via:
```
service netbird onestart
```
The template has been corrected to:
```jinja
{% if OPNsense.netbird.settings.general.enable == '1' %}
```
This ensures the `netbird_enable` flag correctly reflects the enabled state, allowing the service to be started normally.
Closes: …
> security/netbird: Fix service startup failure

- www/nginx/Makefile
- www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php
What the title says, cleans up the PHP errors noise in the crash reporter.
From ${var} to {$var}
> nginx: fix PHP 8.2+ deprecation warnings

- security/clamav/Makefile
- security/clamav/pkg-descr
- security/clamav/src/opnsense/mvc/app/controllers/OPNsense/ClamAV/forms/general.xml
- security/clamav/src/opnsense/mvc/app/models/OPNsense/ClamAV/General.xml
- security/clamav/src/opnsense/service/templates/OPNsense/ClamAV/clamd.conf
Fixes: https://github.com/opnsense/plugins/issues/4833
This option was renamed for some reason and thus not working.
https://blog.clamav.net/2018/12/clamav-01010-has-been-released.html
> Clamav: fix DetectBrokenExecutables option

- net-mgmt/telegraf/Makefile
- net-mgmt/telegraf/pkg-descr
- net-mgmt/telegraf/src/opnsense/mvc/app/controllers/OPNsense/Telegraf/forms/input.xml
- net-mgmt/telegraf/src/opnsense/mvc/app/models/OPNsense/Telegraf/Input.xml
- net-mgmt/telegraf/src/opnsense/service/templates/OPNsense/Telegraf/telegraf.conf
Fixes: https://github.com/opnsense/plugins/issues/4849
The telegraf team had mislabeled this option. The current version of this option has the same effects as before.
In contrast to the previous documentation by telegraf, this is not a recommended option due to its low accuracy and the already low resources required by the module.
> telegraf: fix internet speed tests saving mode

- net/frr/src/opnsense/mvc/app/controllers/OPNsense/Quagga/forms/dialogEditOSPFInterface.xml
- net/frr/src/opnsense/mvc/app/models/OPNsense/Quagga/OSPF.xml
- net/frr/src/opnsense/mvc/app/views/OPNsense/Quagga/ospf.volt
- net/frr/src/opnsense/service/templates/OPNsense/Quagga/ospfd.conf
This PR adds support for specifying the additional arguments delay-reflood and non-broadcast for the point-to-multipoint network type. These options are now available: https://docs.frrouting.org/en/latest/ospfd.html#clicmd-ip-ospf-network-broadcast-non-broadcast-point-to-multipoint-delay-reflood-non-broadcast-point-to-point-dmvpn
> net/frr: ospfd add point-to-multipoint options

- net/siproxd/Makefile
- net/siproxd/src/opnsense/mvc/app/models/OPNsense/Siproxd/User.xml
Fix: https://github.com/opnsense/plugins/issues/4599
siproxd supports those, and I don't think they would break anything on the opnsense side.
> siproxd: add commonly used username characters

- net/haproxy/src/opnsense/mvc/app/models/OPNsense/HAProxy/HAProxy.xml
'Required' --> 'required'
Using the OpnSense web interface to set a client certificate as 'required' results in the error below. Fixing the casing of the XML tags to align with HAProxy https://www.haproxy.com/documentation/haproxy-configuration-tutorials/security/authentication/client-certificate-authentication/#verify-client-certificates
[NOTICE] (18212) : haproxy version is 3.0.11-9e587df
[NOTICE] (18212) : path to executable is /usr/local/sbin/haproxy
[ALERT] (18212) : config : parsing [/usr/local/etc/haproxy.conf.staging:66] : 'bind 0.0.0.0:123' in section 'frontend' : 'verify' : unknown verify method 'Required', only 'none', 'optional', and 'required' are supported
[ALERT] (18212) : config : Error(s) found in configuration file : /usr/local/etc/haproxy.conf.staging
[ALERT] (18212) : …
> HAProxy: Fix frontend client cert 'required' casing

- security/netbird/src/opnsense/mvc/app/controllers/OPNsense/Netbird/forms/settings.xml
two small fixes in the header for the firewall toggle. Added the missing second "l" and used a capital F in for Firewall, so that it matches the other headers.
> security/netbird: Fix typo in firewall settings label

- www/caddy/pkg-descr
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/caddy_certs.php
- www/caddy/src/opnsense/scripts/OPNsense/Caddy/setup.sh
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/Caddyfile
- www/caddy/src/opnsense/service/templates/OPNsense/Caddy/includeLayer4
This fixes multiple things:
- When running as www:www user, the interaction with the admin socket could fail, now we do not touch /var/run/caddy and let it be handled by the permissions set in the rc.d script
```
2025-08-24T11:39:27Errorcaddy"error","ts":"2025-08-24T09:39:27Z","logger":"admin.api","msg":"request error","error":"loading config: loading new config: starting caddy administration endpoint: unable to set permissions (--w--w----) on /var/run/caddy/caddy.sock: chmod /var/run/caddy/caddy.sock: operation not permitted","status_code":400}
```
Fixes: https://github.com/opnsense/plugins/issues/4402
- When restarting/reloading caddy, permissions and ownerships would be changed every time, possibly breaking the storage if caddy writes at the same time
- The custom certificates are now …
> www/caddy: Fix setup.sh script interaction with files and directories in caddy storage

- net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/General.xml
- net/shadowsocks/src/opnsense/mvc/app/models/OPNsense/Shadowsocks/Local.xml
**PR objective:**
This PR is to align the OPNSense WEB UI cipher list for ShadowSocks with the cipher list of the plugin.
https://github.com/shadowsocks/shadowsocks-rust?tab=readme-ov-file#supported-ciphers
Some deprecated cipher were removed, new one added.
edit: this PR works now, thanks to @Monviech tip.
> Shadowsocks   update web UI ciphers to match shadowsocks rust

- net-mgmt/zabbix-proxy/src/opnsense/mvc/app/controllers/OPNsense/Zabbixproxy/forms/general.xml
- net-mgmt/zabbix-proxy/src/opnsense/mvc/app/models/OPNsense/Zabbixproxy/General.xml
- net-mgmt/zabbix-proxy/src/opnsense/service/templates/OPNsense/Zabbixproxy/zabbix_proxy.conf.in
Zabbix Proxy was crashing because of lacking of VMwareCacheSize on my setup and manually adding that option to config at every change was painful, so I implemented it with other VMware options. I would appreciate it if this could be merged into the main repository.
> net-mgmt/zabbix-proxy: Add VMware parameters
